### ISSUE TITLE
Getting errors while installing from Flathub

### ISSUE THREAD

**Issue by spamegg1** [organicmaps/organicmaps#5818] opened 2023-08-25 04:52 UTC
**Describe the issue**
When using
```
flatpak install flathub app.organicmaps.desktop
```
I constantly get either "Server returned 404 not found" or "exceeded maximum size of ... bytes" errors.

**Steps to reproduce**
1. Open Terminal
2. Run the command `flatpak install flathub app.organicmaps.desktop`
3. See error

**Expected behavior**
Should install normally.

**Screenshots**
![Screenshot from 2023-08-25 07-49-15](https://github.com/organicmaps/organicmaps/assets/4255997/9d92207d-a886-481f-b797-891dfb1e7f96)

**System information:**
```
inxi -S                                                                                                          
System:
  Host: spam-B450M-S2H Kernel: 5.15.0-79-generic x86_64 bits: 64
    Desktop: Cinnamon 5.8.4 Distro: Linux Mint 21.2 Victoria
```

**Additional context**
Others have the issue as well: https://forums.linuxmint.com/viewtopic.php?p=2365589#p2365589

**Comment by navy676aw** [comment] 2023-08-28 01:02
I was able to install the beta following [github.com/flathub/app.organicmaps.desktop](https://github.com/flathub/app.organicmaps.desktop) it throws an error when trying to change the stable to beta because it isn't installed but it does just end up installing beta OrganicMaps

**Comment by biodranik** [comment] 2023-08-30 05:17
@Ferenc- can you please help? We got one more exceeded maximum size error report by email.

**Comment by Ferenc-** [comment] 2023-08-30 13:10
This is a duplicate of https://github.com/flathub/app.organicmaps.desktop/issues/56 which is a `flathub` infrastructure problem.
So let's continue the discusison on the `flathub` GH issue.  Also on discord I will raise this, and ask for more attention.

**Closed** 2023-08-30 15:58 UTC
Labels: Linux Desktop
