### ISSUE TITLE
Display bathroom gender

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8679] opened 2024-07-11 11:23 UTC
> OpenStreetMap metadata tags for bathroom gender aren't shown, some airports or malls in Asia have very distantly spaced gendered bathrooms.

**Comment by dvdmrtnz** [comment] 2024-08-13 14:08
* Duplicate of https://github.com/organicmaps/organicmaps/issues/5693

**Closed by dvdmrtnz** 2024-08-13 14:08 UTC
Labels: Map Data, POI Info
