### ISSUE TITLE
OrganicMaps should allow normal map usage on the phone when it is not actually being shown on the the Carplay screen

### ISSUE THREAD

**Issue by ansonl** [organicmaps/organicmaps#7136] opened 2024-01-11 06:22 UTC
**Describe the issue**
OrganicMaps iOS app shows Carplay icon on screen and does not allow user interaction on phone screen when connected to Carplay but OrganicMaps is not active on the Carplay screen. This prevents normal use of OrganicMaps on the phone when it is not actually being used on the the Carplay screen or doing routing through Carplay. 

Other map applications allow normal use of the map on the phone screen when the app is not actively shown on the carplay screen or routing on carplay. 

**Steps to reproduce**
1. Connect iphone to Carplay
2. Don't use OrganicMaps on Carplay. Just stay on the home dashboard or use another app. 
3. Start OrganicMaps on the iOS
4. OrganicMaps blocks user interaction even though it is not being used on Carplay because the iphone is connected to Carplay. 

**Expected behaviour**
OrganicMaps should allow normal usage on the phone screen when the app is not actively shown on carplay screen or providing directions to the carplay screen. 

**Screenshots**
None needed, just the normal carplay icon blocking usage is shown when it shouldn't be. 

**System information:**
 - Operating system and its version: ios 17.2.1
 - Organic Maps version: 2023.12.22-2
 - Device Model: iphone se gen3

**Additional context**
N/A

**Comment by Jean-BaptisteC** [comment] 2024-01-11 07:09
Duplicate of #763

**Closed** 2024-01-11 09:23 UTC
