### ISSUE TITLE
City of a place is not shown anywhere

### ISSUE THREAD

**Issue by nandlab** [organicmaps/organicmaps#7963] opened 2024-04-20 15:13 UTC
**Describe the issue**
If you click on a building or any place in Organic Maps, you can see the street and the house number, but **neither the city, postcode nor country is shown**. This can be confusing if there is the same street in two different cities.

**Steps to reproduce**
Click on a place or open a shared link in Organic Maps.

**Expected behavior**
I would expect to see the city, postcode and country when I click on a place.

**Screenshots**
Just as an example, in the screenshot you can see a pharmacy in Dortmund, Germany. The city, postcode and country is not written anywhere on the screen. 
![organic_maps_pharmacy](https://github.com/organicmaps/organicmaps/assets/81931312/9331b414-07cf-4135-8f34-0971138c8004)

**System information:**
 - Operating system and its version: GrapheneOS based on Android 14, build number: 2024040900
 - Organic Maps version: 2024.03.31-8-FDroid
 - Device Model: Google Pixel 7a

**Comment by Jean-BaptisteC** [comment] 2024-04-20 20:29
Duplicate of #321

**Closed by Jean-BaptisteC** 2024-04-20 20:29 UTC
