### ISSUE TITLE
Possibility to follow tracks (for loops for instance) 

### ISSUE THREAD

**Issue by AnnaTartine** [organicmaps/organicmaps#6456] opened 2023-11-02 22:13 UTC
I love the app a lot for biking especially. However something is stoping me to adopt Organic Maps at 100% 

I like that i can import GPX tracks, but i'm not being able to follow that track by launching an itinerary.

Especially when i want to make a loop. Geo vélo (a binking app) allows me to make loops arround my position, i can then export them to GPX, but i can't follow it through OM.

With the new background voice instruction, i really like to use OM with needing to stop to figure out where i have to go. And i can't doing it with loops or specific track i'd like to follow

On the geo vélo app, after creating a loop, i can start it from the app, with voice instruction and informations about the altitude or the time it takes

![Screenshot_2023-11-02-23-04-46-412_fr geovelo](https://github.com/organicmaps/organicmaps/assets/72700208/21b9c8db-2be7-41b0-80cd-5fbc05f61702)

Perhaps it is useful for people to ne able to do such things directly in OM.

I think it could be interesting for people who plans trips in advance, for hiking for instance.

**Comment by biodranik** [comment] 2023-11-02 22:59
Is it only about track navigation (see https://github.com/organicmaps/organicmaps/issues/1360 ) or also about non-working loop routes?

**Comment by AnnaTartine** [comment] 2023-11-03 08:15
Oh i couldn't find a similar issue sorry !!

I guess if this feature is implemented, the loop would work. Maybe the only thing would be a possibility to chose in which direction you want to take the loop

Thanks a lot, sorry i'm not very good with github. The discussion you mentionned in interesting, i will keep an eye on it

**Comment by RedAuburn** [comment] 2024-05-21 23:44
closing as duplicate of https://github.com/organicmaps/organicmaps/issues/1360

**Closed by RedAuburn** 2024-05-21 23:44 UTC
Labels: Enhancement
