### ISSUE TITLE
[ios] Recent Track disappears when re-opening Organic Maps

### ISSUE THREAD

**Issue by Swamp2k9** [organicmaps/organicmaps#8064] opened 2024-05-02 19:32 UTC
⚠ Have you searched for similar, already existing issues?

**Is your feature request related to a problem? Please describe.**
Whenever I close and reopen the app, my Recent_Track data is removed/deleted. I have it set to save up to 1 day. I tend to close Organic Maps whenever I reach a destination and reopen it whenever I'm ready to depart. I'm usually at a destination from a few minutes to a couple of hours.

**Describe the ideal solution**
Have the tracking data saved and accessible once the app is reopened (and deleted within the set timeframe (1 hour, 2 hours, 6 hours, 12 hours, 1 day).

**Describe alternatives you have considered**
My workaround has been to have the app opened in the background while at my destination.

**Comment by biodranik** [comment] 2024-05-02 19:35
You're speaking about iOS, right? Are you sure that there is a way to record track without an app running in the background? Are you aware of such apps on iOS?

**Comment by Swamp2k9** [comment] 2024-05-02 19:40
Hi!

Yes, I'm on iOS. Apologies for me not mentioning my device.

If the app is closed, then I wouldn't want it to track my location. When the app is reopened, it could have my previous travel history available. 

Go Map!! has this functionality atm. I use it to add new POIs. (loving your UI btw - You have me adding store hours and websites for local businesses 😎). 

A quick side-note: Whenever I add hotels/motels in OSM, will Organic Maps automatically generate a Kayak.com link, or would I have to add additional information to the POIs?

**Comment by biodranik** [comment] 2024-05-02 20:37
The recent track should not be cleared when you restart OM. It should stay there. That is strange. Does it always reproduce? Anything specific that you're doing? How are you killing the app?

**Comment by Swamp2k9** [comment] 2024-05-03 22:34
The recent track has been disappearing for me for quite some time. I was starting to think that it was meant to operate that way. 

I'm killing the app by swiping up. Here's a [video](https://owncloud.marshweb.co.nz/s/CnuD9CLcrpJoIbU) comparing Organic Maps and Go Map!!

**Comment by biodranik** [comment] 2024-05-04 08:54
That is definitely a bug. The recent track is not cleared on my device (and it shouldn't). Looks like the app can't save the track file for some reason (or it is corrupted and can't be loaded back on restart) and only draws it from memory. Can you please export/backup all your bookmarks and tracks, delete OM, and reinstall it back again, and tell us if it helps?


@kirylkaveryn @dvdmrtnz @fabwu @rtsisyk did you observe a track disappearance on your devices?

**Comment by Swamp2k9** [comment] 2024-05-04 21:50
Hi!

I've followed your instructions and now it's working fine. 

Cheers for your help! 🥳

**Comment by biodranik** [comment] 2024-05-04 21:57
Good. We still don't know why that issue appeared. You didn't manipulate with OM files using File Sharing, right?

**Comment by Swamp2k9** [comment] 2024-05-04 22:02
No. I haven't done any file-sharing. I forgot to mention that I'm using the Test Flight version am I've been using the iOS public beta versions.

**Comment by biodranik** [comment] 2024-06-07 10:50
@rtsisyk @kavikhalique Maybe the same issue can be reproduced on Android when testing the recent track implementation #8214

The current C++ implementation should be investigated to understand the reason. Hypothesis:
1. The file is corrupted when it is written (e.g. only a portion of data is saved) for some reason.
2. The file-loading code is not robust enough and fails in some cases.

Even if a file with recent track data is corrupted for whatever reason, the loading code should detect it and trim either only the unreadable data or trim the whole file, to allow saving the recent track in all subsequent sessions.

Of course, the saving code should be fixed to be written in a way that always provides a guarantee that the data was written/stored properly.

**Closed** 2024-08-11 17:35 UTC
Labels: iOS, Track Recording
