### ISSUE TITLE
Display highway icons over naligation line

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#7806] opened 2024-04-04 08:20 UTC
Display highway icons (traffic lights, bump, etc.) over naligation line.

You can show only those icons that are on the way and their direction coincides with the direction of movement (for example, do not show traffic lights that are intended for oncoming traffic)

**Comment by Jean-BaptisteC** [comment] 2024-04-04 09:39
Duplicate of #3987

**Closed by Jean-BaptisteC** 2024-04-04 09:39 UTC
Labels: Enhancement
