### ISSUE TITLE
Bus route navigation

### ISSUE THREAD

**Issue by dfbgcnff** [organicmaps/organicmaps#9219] opened 2024-09-04 01:47 UTC
I have used the subway navigation feature, and it's very useful, but I wish I was able to do that, but with buses. The data is available on openstreetmap.

**Comment by map-per** [comment] 2024-09-04 18:55
Yes, closing as duplicate of #3160 to keep the discussion in one place

**Comment by map-per** [comment] 2024-09-04 18:55
Duplicate of #3160

**Closed by map-per** 2024-09-04 18:55 UTC
Labels: Enhancement
