### ISSUE TITLE
Support "landuse=retail" tag

### ISSUE THREAD

**Issue by hujan86** [organicmaps/organicmaps#8967] opened 2024-08-15 11:03 UTC
Unlike commercial areas, Organic Maps can't display the name of areas designated as "retail" in OpenStreetMap. The retail area's name didn't even appear in the search result. 

Implementation could be the similar to "landuse=commercial" but only need add the "retail" tag. 
[retailarea](https://github.com/user-attachments/assets/8b986d16-1982-48bb-916e-35ef9927875b)

**Comment by Jean-BaptisteC** [comment] 2024-08-15 13:33
Duplicate of #4146

**Closed by Jean-BaptisteC** 2024-08-15 13:33 UTC
Labels: Enhancement
