### ISSUE TITLE
The position arrow is wrongly placed at the top in the landscape mode

### ISSUE THREAD

**Issue by Zuthos** [organicmaps/organicmaps#4794] opened 2023-03-16 08:18 UTC
**Describe the issue**
Hello, when I use the application in landscape mode, the cursor is placed at the top of the screen. It is therefore impossible to see the route to be taken.
Is it possible to place it at the bottom of the screen?

**Steps to reproduce**
1 Put the application in landscape mode
2 Indicate a direction
3 Start route guidance

**Expected behavior**
Have visibility of the route to be taken

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: Android 11,
 - Organic Maps version: 2023.03.05-Google
 - Device Model: Samsung A40
![Screenshot_20230316-074933_Organic Maps](https://user-images.githubusercontent.com/7036341/225556234-a42bcc82-c19d-4000-b8aa-787b1647fa23.jpg)

**Additional context**
Please add any other context and important details/notes/comments about the problem here.

**Comment by Jean-BaptisteC** [comment] 2023-03-16 13:23
Not reproduced on my Pixel 6 - Android 13
Maybe it's appears when users start routing, when he move with car

**Comment by biodranik** [comment] 2023-03-16 14:25
Can someone reproduce it in walking nav mode?

**Comment by Altonss** [comment] 2023-03-16 14:49
> Can anyone else reproduce it?

Couldn't reproduce it either... (it only switches to the top if I click on a house number (and the corresponding bottom window opens) for example)

**Comment by biodranik** [comment] 2023-03-20 14:56
It could be related to the screen size. Can please anyone test it on a similar device (Samsung A40), or on the emulator with the following screen size:

5.9 inches
1080 x 2340 pixels, 19.5:9 ratio (~437 ppi density)

**Comment by biodranik** [comment] 2023-03-25 14:35
@rtsisyk It reproduces on my Android 8 too:
1. Rotate to the landscape.
2. Build a driving route (notice related issue here: the route is not centered on the screen, we might need to create another issue for it)
3. Start navigation.

**Comment by biodranik** [comment] 2023-04-24 10:23
The problem is in the code that moves up the center for the position when the Place Page is open and then does not correct back the center position when the Place Page is closed. It reproduces on the current master in all scenarios (portrait and landscape), for example:

1. Center position on the map by pressing the position button under + and -
2. Open the Place Page by selecting any object (and optionally expand it) and notice how the arrow moves up to stay in the center of the screen.
3. Close the Place Page and see that the arrow stays in the same position (not in the center).

At this moment, our "center in the map" mode has already broken: the location button shows that the "center on the map" mode is active (blue arrow icon), while physically the current position is not at the center of the screen. Logically, either the current location mode should be changed to "Not following" (meaning the blue arrow icon under +/- should change to crosshair), or the position should move back to the center of the screen when PP was hidden.

@arnaudvergnet Looks like the original behavior of moving down the current position arrow when Place Page is closed or almost closed was broken during refactorings.

**Comment by rtsisyk** [comment] 2023-04-26 20:01
> The problem is in the code that moves up the center for the position when the Place Page is open and then does not correct back the center position when the Place Page is closed. It reproduces on the current master in all scenarios (portrait and landscape), for example:
> 
>     1. Center position on the map by pressing the position button under + and -
> 
>     2. Open the Place Page by selecting any object (and optionally expand it) and notice how the arrow moves up to stay in the center of the screen.
> 
>     3. Close the Place Page and see that the arrow stays in the same position (not in the center).
> 
> 
> At this moment, our "center in the map" mode has already broken: the location button shows that the "center on the map" mode is active (blue arrow icon), while physically the current position is not at the center of the screen. Logically, either the current location mode should be changed to "Not following" (meaning the blue arrow icon under +/- should change to crosshair), or the position should move back to the center of the screen when PP was hidden.
> 
> @arnaudvergnet Looks like the original behavior of moving down the current position arrow when Place Page is closed or almost closed was broken during refactorings.

I don't see any reason for changing viewport when PP is open. This just doesn't provide any value.

**Comment by biodranik** [comment] 2023-04-28 05:51
The value is that you always see the selected object on the map. And you always understand what is this PP about. All other maps do that.

**Comment by biodranik** [comment] 2023-05-10 15:15
@Zuthos can you please check if this bug reproduces in the latest May release or beta?

**Comment by rtsisyk** [comment] 2023-09-10 09:09
This issue is already fixed by #3462

**Closed by rtsisyk** 2023-09-10 09:09 UTC
Labels: Android, Navigation, UI
