### ISSUE TITLE
Sticky-headers-recyclerview deprecated & slowing down builds

### ISSUE THREAD

**Issue by n1snt** [organicmaps/organicmaps#4700] opened 2023-03-05 18:29 UTC
**Describe the issue**
sticky-headers-recyclerview is not being maintained since 2016 we need to start looking for an alternative.
This library is also slowing down builds because to keep this library we need to set the enableJetifier option in gradle.properties. 

**Sources:**
[sticky-headers-recyclerview](https://github.com/timehop/sticky-headers-recyclerview)
[enableJetifier](https://developer.android.com/studio/build/optimize-your-build)

**Comment by Jean-BaptisteC** [comment] 2023-03-05 19:03
Duplicate of #4686

**Closed** 2023-03-08 06:19 UTC
