### ISSUE TITLE
[android] Attempt to invoke virtual method 'int app.organicmaps.bookmarks.data.Track.getColor()' on a null object reference

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#9323] opened 2024-09-19 21:11 UTC
Found by monkey. Probably caused by https://github.com/organicmaps/organicmaps/pull/9033.

https://storage.cloud.google.com/test-lab-tfv1dx2ft95t8-yibm740y7szh2/2024-09-19_20%3A37%3A44.052028_UYdS/bluejay-32-en-portrait/video.mp4

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int app.organicmaps.bookmarks.data.Track.getColor()' on a null object reference
     FATAL EXCEPTION: Thread-5
Process: app.organicmaps.beta, PID: 24201
java.lang.NullPointerException: Attempt to invoke virtual method 'int app.organicmaps.bookmarks.data.Track.getColor()' on a null object reference
	at app.organicmaps.widget.placepage.EditBookmarkFragment.lambda$selectBookmarkColor$5(EditBookmarkFragment.java:308)
	at app.organicmaps.widget.placepage.EditBookmarkFragment.$r8$lambda$pdBMtZdk9ttNJeHEw1_RDJZCB2o(EditBookmarkFragment.java:0)
	at app.organicmaps.widget.placepage.EditBookmarkFragment$$ExternalSyntheticLambda2.onBookmarkColorSet(R8$$SyntheticClass:0)
	at app.organicmaps.widget.placepage.BookmarkColorDialogFragment.lambda$buildView$0(BookmarkColorDialogFragment.java:66)
	at app.organicmaps.widget.placepage.BookmarkColorDialogFragment.$r8$lambda$vQ-_ZUSQqKOIU0YjDuTUCMjjZVg(BookmarkColorDialogFragment.java:0)
	at app.organicmaps.widget.placepage.BookmarkColorDialogFragment$$ExternalSyntheticLambda0.onItemClick(R8$$SyntheticClass:0)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3190)
	at android.widget.AbsListView$3.run(AbsListView.java:4156)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:7)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:23)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

CC: @kavikhalique

**Comment by kavikhalique** [comment] 2024-09-19 21:59
The provided link is broken

**Comment by kavikhalique** [comment] 2024-09-19 23:34
The issue is probably caused due to missing of few commits while squashing and merging them into master of PR (https://github.com/organicmaps/organicmaps/pull/9033)

```
switch (mType)
    {
      case 1:
      {
        dialogFragment.setOnColorSetListener(colorPos -> {
          final Icon newIcon = BookmarkManager.ICONS.get(colorPos);
          final String from = mTrack.getName();
          final String to = newIcon.getName();
          if (TextUtils.equals(from, to))
            return;

          mIcon = newIcon;
          refreshColorMarker();
        });
      }
      case 2:
      {
        dialogFragment.setOnColorSetListener(colorPos -> {
          int from = mTrack.getColor();
          int to = BookmarkManager.ICONS.get(colorPos).argb();
          if (from == to)
            return;
          mColor = to;
          refreshTrackColor();
        });
        break;
      }
    }
```

The issue is caused due to the missing break in this above switch case present at this place [link](https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/java/app/organicmaps/widget/placepage/EditBookmarkFragment.java#L290). I remember i fixed this issue while working on the PR and committed it too but i cannot see those changes into master. @rtsisyk

**Closed** 2024-09-23 14:10 UTC
Labels: Android, CrashReports
