### ISSUE TITLE
Short Hills Provincial Park has way to many labels 

### ISSUE THREAD

**Issue by unbeatable-101** [organicmaps/organicmaps#4177] opened 2022-12-31 23:39 UTC
This must be because the park is a multipolygon with many different areas making it up.
![7881CAF8-E0F5-468A-B2DF-FB5C279B418E](https://user-images.githubusercontent.com/58151048/210157631-15b64126-f1c8-46b5-a69e-3898dcb93a20.png)
43.100995, -79.284413

**Comment by Jean-BaptisteC** [comment] 2023-01-01 08:35
Happy new year 🎉

Yes, this issue is caused by multipolygon, i guess we don't use correctly relation to show name
https://www.openstreetmap.org/relation/14194395#map=15/43.0993/-79.2806

cc @vng

**Comment by Jean-BaptisteC** [comment] 2023-11-26 21:16
Duplicate of #4128

**Closed by Jean-BaptisteC** 2023-11-26 21:16 UTC
Labels: Bug, Map Data, Generator
