### ISSUE TITLE
Arrow in place page missing on tablet

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#4340] opened 2023-01-25 22:50 UTC
I noticed that the arrow showing the direction from my current location to a POI is missing on my tablet (Samsung Galaxy S6lite 2022 running Android 13). 
In both portrait and landscape mode.  

I checked version 2022.12.08-12-Google and 2023.01.25-18-Google-beta.

![arrow](https://user-images.githubusercontent.com/7961926/214711564-3d9298a3-13db-44e3-a9d2-e2c32d62e8ba.jpg)

**Comment by Jean-BaptisteC** [comment] 2023-01-26 16:37
Duplicate of #4301

**Comment by biodranik** [comment] 2023-01-26 17:39
Sensors: Accelerometer, proximity, gyro

Your tablet doesn't have a compass sensor. So it is not possible to detect the direction of the device.

**Closed by biodranik** 2023-01-26 17:39 UTC
Labels: Won't fix
