### ISSUE TITLE
[UX] Before deleting a bookmark list, ask the user for confirmation

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#5990] opened 2023-09-09 16:15 UTC
A list can be "accidentally" deleted by clicking on delete instead of export. This action should be protected by a confirmation dialog if the user really wants to delete the bookmark list, especially because there is no automatic backup.

**Comment by pastk** [comment] 2023-09-10 18:57
Closing as a duplicate of #5735

**Closed by pastk** 2023-09-10 18:57 UTC
