### ISSUE TITLE
Hide items (ie. electric cars stations)

### ISSUE THREAD

**Issue by Kalytis** [organicmaps/organicmaps#4105] opened 2022-12-18 00:41 UTC
The display of multiple items is still messy, and in order to prevent that (and to make the map more readable) I'd love to be able to hide certain items of my choice.

For example, charge stations for electric cars. I don't have an electric car. Please allow me to get rid of them.

**Comment by Jean-BaptisteC** [comment] 2022-12-18 08:47
Do you know if others routing apps used this feature ?
Do you want hide these POI during routing ?

**Comment by Kalytis** [comment] 2022-12-18 09:16
I'm not sure other routing apps allow to do this, no.

I'd like to hide them during routing, map scrolling, driving, always.

**Comment by twikedk** [comment] 2022-12-21 07:36
OsmAnd has something called 'Show POI overlay' which does what you ask for. I always have that disabled as I'm not interested in any POI showed on my map.

**Comment by biodranik** [comment] 2022-12-21 08:27
Customizing displayed icons takes a lot of time to implement, and doesn't look easy to use for everyone. Let's brainstorm better options, focused on the use case and the intent of the user. E.g.:
1. You can set up a car type somewhere in settings (RV, truck, electric, gasoline) and all unnecessary POIs will be filtered. Routing and navigation will also take it into an account.
2. Selecting the appropriate style (driving, public transport, hiking, city tourism, cycling, etc.) can hide some irrelevant icons.

**Comment by pastk** [comment] 2023-09-08 11:49
Duplicate of #2355

**Closed** 2023-09-09 10:52 UTC
Labels: Icons, UX, Styles
