### ISSUE TITLE
Empty OpenStreetMap changesets created

### ISSUE THREAD

**Issue by starsep** [organicmaps/organicmaps#2349] opened 2022-04-05 21:20 UTC
I noticed that Organic Maps creates empty changesets.
Some examples:
https://www.openstreetmap.org/changeset/119291583
https://www.openstreetmap.org/changeset/119280841
https://www.openstreetmap.org/changeset/119280583
https://www.openstreetmap.org/changeset/119278042
I was using the app and was logged in to OpenStreetMap.
I didn't make any edits then.
This bug is also a bit of privacy concern as it shows when the app is used.

Version: Organic Maps android 2022.03.23-4-Web

**Comment by biodranik** [comment] 2022-04-06 00:03
Very strange. There should be no uploads at all if you didn't edit features. What is displayed when you type `?edits` in the search? There were other successful edits before, right?

**Comment by starsep** [comment] 2022-04-06 05:24
Yes, I made edits before. 
Is it caused by this error? Does the app retry upload and fails, again and again, which causes empty changesets? Rest of objects have Uploaded status.
![Screenshot_2022-04-06-07-19-52-92_75d0290a7c00525acd83c0ab8700d64c](https://user-images.githubusercontent.com/2798728/161901182-49bb252a-1e26-4233-a111-36a37ce33265.jpg)

**Comment by biodranik** [comment] 2022-04-06 06:36
Yes, looks like it's the reason. Can you please enable logs recording in OM settings, try to reproduce the issue, and share logs with us? Or reproduce it while recording logs locally with `adb logcat` and send us the log? Looks like our code can't parse the server's response.
Also, if you remember what was that feature, maybe you can tell us how to reproduce it locally (where and what exactly did you edit in OM).

**Comment by starsep** [comment] 2022-04-06 07:09
I edited this museum https://openstreetmap.org/node/475376666 specifically opening hours.

Logs:
```
2022-04-06 08:59:11.777 Thread-3: W/MapsmeCore: editor/osm_editor.cpp:783 operator()()  ModifyElementHasFailed /home/runner/work/organicmaps/organicmaps/editor/server_api.cpp:83, "ModifyElement request has failed: (400, Cannot parse valid node from xml string <?xml version="1.0"?>
<osm>
<node id="475376666" visible="true" version="9" changeset="119371595" timestamp="2019-03-12T19:41:12Z" user="b-jazz-bot" uid="9451067" lat="50.1067852" lon="14.4475546">
  <tag k="addr:city" v="Praha" />
  <tag k="addr:conscriptionnumber" v="793" />
  <tag k="addr:country" v="CZ" />
  <tag k="addr:housenumber" v="793/1" />
  <tag k="addr:place" v="Hole??ovice" />
  <tag k="addr:postcode" v="17000" />
  <tag k="addr:street" v="Poup??tova" />
  <tag k="addr:streetnumber" v="1" />
  <tag k="addr:suburb" v="Praha 7" />
  <tag k="description:en" v="Centre for Contemporary Art" />
  <tag k="email" v="infocentrum@dox.cz" />
  <tag k="name" v="DOX" />
  <tag k="opening_hours" v="We-Su 12:00-18:00" />
  <tag k="phone" v="+420 295 568 123" />
  <tag k="ref:ruian:addr" v="22303413" />
  <tag k="source:addr" v="cuzk:ruian" />
  <tag k="tourism" v="museum" />
  <tag k="website" v="https://www.dox.cz/" />
  <tag k="wheelchair" v="yes" />
  <tag k="wikidata" v="Q11722838" />
  <tag k="wikipedia" v="cs:Centrum sou??asn??ho um??n?? DOX" />
  <tag k="description" v="?Centre for Contemporary Art" />
</node>
</osm>
. Fatal error: Input is not proper UTF-8, indicate encoding !
Bytes: 0x81 0x43 0x65 0x6E at :25.) for <?xml version="1.0"?>
<node id="475376666" visible="true" version="9" changeset="119371595" timestamp="2019-03-12T19:41:12Z" user="b-jazz-bot" uid="9451067" lat="50.1067852" lon="14.4475546">
  <tag k="addr:city" v="Praha" />
  <tag k="addr:conscriptionnumber" v="793" />
  <tag k="addr:country" v="CZ" />
  <tag k="addr:housenumber" v="793/1" />
  <tag k="addr:place" v="Hole??ovice" />
  <tag k="addr:postcode" v="17000" />
  <tag k="addr:street" v="Poup??tova" />
  <tag k="addr:streetnumber" v="1" />
  <tag k="addr:suburb" v="Praha 7" />
  <tag k="description:en" v="Centre for Contemporary Art" />
  <tag k="email" v="infocentrum@dox.cz" />
  <tag k="name" v="DOX" />
  <tag k="opening_hours" v="We-Su 12:00-18:00" />
  <tag k="phone" v="+420 295 568 123" />
  <tag k="ref:ruian:addr" v="22303413" />
  <tag k="source:addr" v="cuzk:ruian" />
  <tag k="tourism" v="museum" />
  <tag k="website" v="https://www.dox.cz/" />
  <tag k="wheelchair" v="yes" />
  <tag k="wikidata" v="Q11722838" />
  <tag k="wikipedia" v="cs:Centrum sou??asn??ho um??n?? DOX" />
  <tag k="description" v="?Centre for Contemporary Art" />
</node>
"
```

**Comment by biodranik** [comment] 2022-04-06 07:49
By any chance, do you have root access? If yes, can you please check the contents of edits.xml file in /data/data/app.organicmaps/files ?

**Comment by starsep** [comment] 2022-04-06 07:52
Unfortunately I don't have root accessApr 6, 2022, 09:50 by ***@***.***:

**Comment by biodranik** [comment] 2022-04-06 09:15
It looks like an encoding problem. Somehow an invalid UTF-8 character was saved in edits.xml and now it fails to upload, OSM server rejects it.
Which Android device and OS version do you have? What languages/locales? Can you please send us a log via "?" -> Report a bug?

As a fix you may try to type `?eclear` in the search to clear failed edit. It would be interesting if you try to repeat the same edit and see if the error reproduces again.

**Comment by starsep** [comment] 2022-04-06 20:14
I send details via email.
I cleared failed edit. I could reproduce error with the same edit.
Correct opening hours are We-Su 12:00-18:00 fyi.

**Comment by biodranik** [comment] 2022-04-07 22:51
Thanks for the bug report, we found and fixed a nasty bug in the core!

**Comment by biodranik** [comment] 2022-04-07 22:55
The bug with empty changesets is another one, and it should be fixed separately. The current implementation doesn't detect the failure properly for some reason.

**Closed** 2022-04-08 04:44 UTC
Labels: Bug, Editor
