### ISSUE TITLE
Add isolines for Alaska

### ISSUE THREAD

**Issue by person142** [organicmaps/organicmaps#6271] opened 2023-10-09 00:35 UTC
**Is your feature request related to a problem? Please describe.**
Isolines are disabled for Alaska - this appears to be because of size constraints:

https://github.com/organicmaps/organicmaps/pull/4580#issuecomment-1637065954

**Describe the solution you would like**
Isolines enabled for Alaska - or at least some parts of it.

**Describe alternatives you have considered**
I use other maps for topographical data.

**Additional context**
A lot of hiking in Alaska is off-trail, so without topographical data you're flying pretty blind. For example, a commonly-climbed off-trail peak around Anchorage is Mount Williwaw:

https://omaps.app/0oznse0M59/Mount_Williwaw

and the map is largely blank for that area.

I'm happy to make PRs to get Alaska supported, though I'm not sure how deep the rabbit hole goes with the space tradeoffs needed. For Alaska in particular I'd guess that people would happily accept a larger map size in exchange for isolines.

**Comment by pastk** [comment] 2023-10-10 14:58
@vng

**Comment by vng** [comment] 2023-10-10 16:31
I tried a _useless_ poor profile (500m) before and the size increase was insane (something like 150 -> 300 Mb)
Probably, we can try to turn on isolines for some parts (tiles) only ..

**Comment by person142** [comment] 2023-10-11 05:19
Some interesting bounding boxes:

### The national parks

- Denali national park: https://nominatim.openstreetmap.org/search.php?q=denali+national+park&format=jsonv2
- Gates of the Arctic national park: https://nominatim.openstreetmap.org/search.php?q=gates+of+the+arctic+national+park&format=jsonv2
- Glacier bay national park: https://nominatim.openstreetmap.org/search.php?q=glacier+bay+national+park&format=jsonv2
- Katmai national park: https://nominatim.openstreetmap.org/search.php?q=katmai+national+park&format=jsonv2
- Kenai Fjords national park: https://nominatim.openstreetmap.org/search.php?q=kenai+fjords+national+park&format=jsonv2
- Kobuk Valley national park: https://nominatim.openstreetmap.org/search.php?q=kobuk+valley+national+park&format=jsonv2
- Lake Clark national park: https://nominatim.openstreetmap.org/search.php?q=lake+clark+national+park&format=jsonv2
- Wrangell St Elias National park: https://nominatim.openstreetmap.org/search.php?q=Wrangell+-+St+Elias+national+park&format=jsonv2
- Chugach state park: https://nominatim.openstreetmap.org/search.php?q=chugach+state+park&format=jsonv2

### The state parks (that I could find OSM bounding boxes for)

- Chugach state park: https://nominatim.openstreetmap.org/search.php?q=chugach+state+park&format=jsonv2
- Kachemak Bay state park: https://nominatim.openstreetmap.org/search.php?q=kachemak+bay+state+park&format=jsonv2
- Shuyak Island state park: https://nominatim.openstreetmap.org/search.php?q=Shuyak+Island+State+Park&format=jsonv2
- Denali state park: https://nominatim.openstreetmap.org/search.php?q=denali+state+park&format=jsonv2

That's probably still... a lot... of stuff; I wonder how much that'd blow the size up.

**Comment by biodranik** [comment] 2023-10-11 06:17
Is the big overhead caused by "close to the north Mercator bound" coordinates?

**Comment by vng** [comment] 2023-10-11 11:47
@person142 Cool!
Now could you please help to transform it to the list of 1-degree tiles? Like here:
https://github.com/organicmaps/organicmaps/blob/master/data/conf/isolines/countries-to-generate.json#L3368

There is a list of bottom-left (lat-lon) points of 1-degree SRTM tiles, that will be included in isolines generation. Having this list, I can run an isolines generator with say 50 meters step.

Defining (lat, lon) tile means that (lat, lon, lat + 1, lon + 1) bounding box will be with isolines.

Or write some Python script to fetch a list of tiles (with neighbors) from the list of POIs :)

**Comment by person142** [comment] 2023-10-12 04:43
List of tiles here:

[tiles.json](https://github.com/organicmaps/organicmaps/files/12877158/tiles.json)

Code here:

https://gist.github.com/person142/f2e874ff8d08af4fdefffbe8fe71a0f7

so I can easily regenerate the list if something is amiss - I spot checked the tile locations, but easy to miss something.

**Comment by vng** [comment] 2023-10-12 12:26
Great! Could you please make one unique tiles list, like:
```
"key": "US_Alaska",
        "value": {
            "profileName": "normal",
            "tileCoordsSubset": [
...
```

**Comment by person142** [comment] 2023-10-12 15:59
This should do the trick:

[tiles.json](https://github.com/organicmaps/organicmaps/files/12884585/tiles.json)

**Comment by vng** [comment] 2023-10-12 17:41
So, _normal_ profile (50m) for these tiles will add approx 150Mb.

**Comment by pastk** [comment] 2023-10-12 18:05
So same size as adding 100m for the whole Alaska.

**Comment by person142** [comment] 2023-10-12 20:02
Interesting; I've seen the discussions https://github.com/organicmaps/organicmaps/issues/6157 and https://github.com/organicmaps/organicmaps/issues/4163 about isoline density - Alaska is definitely one of those steep places where denser isolines are nice, so going less than 50m might be a bummer (and going to 10m when the improvements ^ happen would be awesome).

i.e. if the 150Mb increase is acceptable I'd probably rather have the 50m lines on a smaller area than less-dense lines on a larger area.

**Comment by vng** [comment] 2023-10-15 15:46
![Screenshot_20231015_124548_Organic Maps.jpg](https://github.com/organicmaps/organicmaps/assets/175612/3fcc98b5-c2da-4815-9301-4661cb532dbe)

**Comment by person142** [comment] 2023-10-16 15:57
Awesome! Got curious and compared:

![Denali](https://github.com/organicmaps/organicmaps/assets/15134881/caee339f-e2cd-4f64-8581-feb502d7b007)

Looks like that’s 100m - how much did it end up adding?

**Comment by vng** [comment] 2023-10-16 17:03
Actually, 50 meters, they are visible from 200m zoom.
As I estimated before plus 150M. Now Alaska is 300M.

**Comment by pastk** [comment] 2023-10-17 10:13
Please make a PR to merge all isolines profiles changes into the master.

**Closed** 2023-10-23 11:54 UTC
Labels: Elevation

**Comment by person142** [comment] 2023-12-22 03:04
I've had an injury and hadn't been able to enjoy the new isolines yet, but now I've had a chance to try out some route planning with them, and they're awesome! Thank you for adding.
