### ISSUE TITLE
Music player control

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#7138] opened 2024-01-11 09:27 UTC
Build into the program a simple mp3 player or (even better) control buttons for the current player.  So that you can switch music directly from the navigator, like in Yandex navigator, and you don’t have to minimize the program

**Comment by Jean-BaptisteC** [comment] 2024-01-11 10:02
Duplicate of #1336

**Closed by Jean-BaptisteC** 2024-01-11 10:02 UTC
Labels: Enhancement
