### ISSUE TITLE
[ios] Make text readable

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6213] opened 2023-10-05 09:56 UTC
So far I see two options (do you have better ideas?):
1. Make the text shorter and require no more than X characters (need to mention it in the strings.txt comment for other translators).
2. Automatically reduce the text size to fit into the line.

![выява](https://github.com/organicmaps/organicmaps/assets/170263/f81d52e9-4429-4264-a140-b4ffef0e2e3b)

**Comment by Yash-28-gits** [comment] 2023-10-17 21:40
I  think expanding the row would be good option so that it wont be difficult for users.

**Comment by biodranik** [comment] 2023-10-17 22:25
Removing моïм may solve the issue.

**Comment by Yash-28-gits** [comment] 2023-10-18 05:01
I think moving location to the next line looks more representable.
![Screenshot_2023-10-18-10-26-15-840_com google android googlequicksearchbox-edit](https://github.com/organicmaps/organicmaps/assets/127411198/9a7beaf8-2471-4399-ace0-fc56c70f4ebd)

**Comment by biodranik** [comment] 2023-10-18 05:58
1. It will increase the height of the cell and make it less convenient to tap upper cells.
2. It is more complex to implement.

**Comment by HimanshuKhatarkar** [comment] 2023-12-29 07:42
@biodranik  out of the two option I think you should go with the 2nd one, as there are few languages where Share my Location is that long. Plus you can use "GeoTag" a single word that roughly means "Share this Location". If the word/String is going out of bounds we can use ellipsis ("...") at the end. Doing this when the users hover over the word... they will see  a tag with full name/ String in it.

**Comment by HimanshuKhatarkar** [comment] 2023-12-29 07:43
@biodranik claim

I'd Like to work on this Issue. If no one is working on this and the issue is open please assign this to me.

**Comment by Jean-BaptisteC** [comment] 2024-03-25 19:07
Duplicate of #7605

**Closed by Jean-BaptisteC** 2024-03-25 19:07 UTC
Labels: Good first issue, iOS, Translations, UI
