### ISSUE TITLE
Bookmark icons disappear on Nexus 5 after dragging

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1782] opened 2022-01-04 21:47 UTC
After adding bookmark is displayed. But after a zoom, it disappears in the top and center part of the screen and becomes visible only in the bottom part of the screen. Look like it is reproduced only on Nexus 5 with Android 6.0.

See video:
https://user-images.githubusercontent.com/170263/148128133-659c322f-200a-4bee-8bd0-d898d5915d70.mp4

**Comment by biodranik** [comment] 2022-11-08 16:48
A similar issue is reproduced also on https://www.gsmarena.com/samsung_i9505_galaxy_s4-5371.php

with Lineage OS 18.1 (although the official max Android version is 5.0)

```
Android version: 11 (API 30), security patch level: 2022-10-05, os.version: 3.4.113-gf25a38e2a57
Device: Samsung GT-I9505 (jflte)
Supported ABIs: armeabi-v7a armeabi
App version: app.organicmaps 2022.11.02-2-FDroid
```

**Comment by biodranik** [comment] 2023-01-22 06:36
The same issue is reproduced on another device:
Galaxy S4 GT-I9515 with custom ROM Resurrection Remix Nougat Android 7.1.2 based on Lineage (RR-N-v5.8.4-20170826-jfvelte-Official)

https://user-images.githubusercontent.com/170263/213903895-4eacb074-bfb1-4f39-b055-70c4e934278d.mp4

**Comment by biodranik** [comment] 2023-01-22 06:41
The common thing between all these devices is that they were initially Android 4.4 devices.

Also the interesting fact is that one user confirms that the same bug is NOT reproduced in MapsMe.

**Comment by Jean-BaptisteC** [comment] 2024-01-15 11:40
Duplicate of #1112

**Closed by Jean-BaptisteC** 2024-01-15 11:40 UTC
Labels: Bug, Drape
