### ISSUE TITLE
[Feature Request] Set the color for all bookmarks in a list.

### ISSUE THREAD

**Issue by gabriel-de-luca** [organicmaps/organicmaps#2472] opened 2022-04-28 03:04 UTC
I would like to be able to assign a color to all symbols in a list of bookmarks.

It would be very handy if, when you save or move a site to one list, the color of its symbol changes to that of the list it belongs to.

Thank you for your development.

**Comment by biodranik** [comment] 2022-04-28 18:06
I think it's a duplicate of #1805 

Some people want all bookmarks in one color in the same list. Some people use different colors. How would you implement it?

Regarding moving, it can also be a bad idea to change the already set color.

**Comment by gabriel-de-luca** [comment] 2022-04-29 00:20
> I think it's a duplicate of #1805

Yes, it is. Sorry, I couldn't find that issue before.

> Some people want all bookmarks in one color in the same list. Some people use different colors. How would you implement it?
> 
> Regarding moving, it can also be a bad idea to change the already set color.

I can think of a new color for the bookmarks, something like "List color". And in the lists settings, in addition to the name and description, a color which may be random by default.  

I will propose it in the previously created issue,
Thank you

**Closed** 2022-04-29 00:30 UTC
Labels: Duplicate, Bookmarks
