### ISSUE TITLE
[Android Auto] Search only works when car is parked

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7204] opened 2024-01-19 21:09 UTC
> Search does not function properly when the gear selector is not set
to Parking. When using Google Assistant to search, the search menu fails
to appear, and even when using the Search button, nothing shows up
either. However, as soon as the car is set to Parking mode, the search
menu and results for the latest query become visible.

**Comment by AndrewShkrob** [comment] 2024-04-29 19:26
> Search does not function properly when the gear selector is not set
to Parking.

It is an intended behavior. Due to security reasons, you can't use a keyboard while driving. Only your voice.

> When using Google Assistant to search, the search menu fails to appear

Unfortunately, it's a problem with this driving mode. The whole interface starts to work slower. I've made some tests for the voice search case:
21:12:47.025 - Intent received
21:12:47.038 - Intent is processed and the search screen is pushed to AA to be displayed
21:12:49.329 - Search screen is displayed
2.3s delay on AA side

21:14:48.850 - Intent received
21:14:48.856 - Intent is processed and the search screen is pushed to AA to be displayed
21:14:58.860 - Search screen is displayed
4s delay

And I experienced delays of 10-20 seconds. We can't do anything about that.
But I feel that AA started to work faster since the ticket creation, so maybe in 1 year, it will work without a delay at all 😁 

> and even when using the Search button, nothing shows up either

I don't know what the user meant with this. The search screen displays recent searches in driving mode. For me, it works fine.

Taking all this into consideration, I'm closing the issue as nothing to fix.

**Closed by AndrewShkrob** 2024-04-29 19:26 UTC
Labels: AndroidAuto

**Comment by biodranik** [comment] 2024-04-29 20:09
What causes these delays in AA? Does an empty mock template app also hangs for several seconds in a similar case?

**Comment by patepelo** [comment] 2024-05-14 15:53
> It is an intended behavior. Due to security reasons, you can't use a keyboard while driving. Only your voice.

What if it's the passenger who is assisting?

**Comment by AndrewShkrob** [comment] 2024-05-15 05:34
> > It is an intended behavior. Due to security reasons, you can't use a keyboard while driving. Only your voice.
> 
> What if it's the passenger who is assisting?

You can ask Google 🙂 : https://issuetracker.google.com/issues?q=status:open%20componentid:460472&s=created_time:desc
I cannot do anything about this
