### ISSUE TITLE
Alignment Discrepancy of Bottom-Side Buttons in Maps Application Between iOS 17 and Android 10

### ISSUE THREAD

**Issue by Yashbhosale00** [organicmaps/organicmaps#8044] opened 2024-04-30 19:55 UTC
**Issue:-Bottom-Side Button Alignment Issue: iOS 17 vs Android 10**

**In iOS 17, while testing a maps application, I discovered a bug where the alignment of the bottom-side buttons on the map is not set properly compared to the Android system. On Android, these bottom-side buttons are well-aligned, but on iOS, they are not.**

**System information:**
 - Operating system and its version: [iOS 17, Android 10]
 - Device Model: [iPhone 15, Samsung S9+]

1st Screenshot IOS-17
2nd Screenshot ANDROID-10

**Screenshots**
![WhatsApp Image 2024-05-01 at 1 08 49 AM](https://github.com/organicmaps/organicmaps/assets/121059725/8c9fd5de-586a-4ee9-8844-3a0f5b9371cf)

![WhatsApp Image 2024-05-01 at 1 08 06 AM](https://github.com/organicmaps/organicmaps/assets/121059725/4c2d5d2d-c5ac-4377-8848-7a88d7bd5915)

**Comment by Jean-BaptisteC** [comment] 2024-04-30 21:59
@kirylkaveryn is it possible to fix easily?

**Comment by kirylkaveryn** [comment] 2024-05-01 05:26
> @kirylkaveryn is it possible to fix easily?

I'm totally disagree that this alignment should be changed in iOS.
All applications in iOS have an equal distribution for the tab bar items and it will be _nonnative_ for many iOS users if changed. Why we should recreate 100% identical interface? 
I think that we should save traits for both systems while designing applications both for android and iOS and do not break the native elements style, behaviour and animations.

**Comment by RedAuburn** [comment] 2024-05-05 23:40
closing as intended

**Closed by RedAuburn** 2024-05-05 23:40 UTC

**Comment by biodranik** [comment] 2024-05-06 12:14
The question is: should we distribute buttons on Android in the same way as it is done on iOS?

A more important question: which 5th button would you add?

@RedAuburn @euf @kirylkaveryn @Jean-BaptisteC

**Comment by euf** [comment] 2024-05-06 12:18
I've never seen a problem like "which 5th button should we add". Normally it's the other way, like "where do we put that extra button", because generally the less buttons is the better. Main screen is already full of controls anyway, there's no need to worry about the free screen estate on bigger devices

**Comment by biodranik** [comment] 2024-05-06 12:24
@euf maybe move layers button at the bottom, and show the current layers on it? ;-)
