### ISSUE TITLE
Display adresses with "contact:"prefix

### ISSUE THREAD

**Issue by CapitaineMoustache** [organicmaps/organicmaps#1960] opened 2022-01-28 13:01 UTC
It would be useful to display adresses on POI's with "contact:" prefix!
It's quite common in Western Europe to map adresses on POI's with that prefix (about 20000 POI's according to TagInfo, see here: https://taginfo.openstreetmap.org/keys/contact%3Ahousenumber#overview).

It's the same than with "addr:":

contact:housenumber
contact:street
contact:postcode
contact:city
etc...

Keep going your fantastic job!

**Comment by biodranik** [comment] 2022-01-28 17:22
contact:housenumber is a draft in OSM, no?
Do you want to see it on the Place Page when the place's address is displayed? Which problem do you want to solve?

**Comment by CapitaineMoustache** [comment] 2022-01-28 18:57
You're right, it's a draft!
In France, this method is used to avoid to have duplicated data about adresses.
Adresses are considered as unique features. One housenumber, one "addr:" (point, line or polygon).
Some apps already display it: [Qwant Maps](https://www.qwant.com/maps/place/osm:node:9283700483@Ma_Rouxtine#map=16.96/46.0989436/4.3229978), [OpenStreetBrowser](https://www.openstreetbrowser.org/#shop/w366198037&map=18/46.15306/4.15700&categories=shop)...

I started a topic on French OSM forum to attempt to clarify the situation and write it on the OSM wiki, work in progress :) !
https://forum.openstreetmap.fr/t/adresses-des-poi-et-contact/7493

**Comment by CapitaineMoustache** [comment] 2022-01-28 19:08
In a nutshell, it is a alternative way to precise adresses on POI's and it would be nice to see it on Organic Maps where adresses are usually displayed!

**Comment by biodranik** [comment] 2022-01-28 20:55
Sorry, from your examples it's not clear to me, why normal addr:street and addr:housenumber are not used on these POIs instead of contact:* tags.

**Comment by matkoniecz** [comment] 2022-01-29 09:54
`contact:housenumber` is explicitly described as NOT an address:

https://wiki.openstreetmap.org/wiki/Key:contact

> For use when the contact address is not the same as the address of the physical location.

It mist not be displayed as an address or in way that can be confused with an actual address

**Comment by CapitaineMoustache** [comment] 2022-01-29 12:45
I agree with you @matkoniecz, the documentation in English is clear. However in France, it is used like I have told.
I think it refers to an old (2013) draft called [Bremen Schema](https://wiki.openstreetmap.org/wiki/Proposed_features/House_numbers/Bremen_Schema).
Somehow, the proposition met a certain success to some french contributors seeking for a way to not create duplicated adresses.

**Comment by biodranik** [comment] 2022-01-29 13:10
But in your examples there is no normal address, only a contact: one. It would be really confusing for users.

**Comment by CapitaineMoustache** [comment] 2022-01-29 13:23
The purpose is to use `addr:` only to map adresses itself, independently. By example, a mall will have a point to its main entrance with all `addr:` tags.
And all shops in will only have `contact:` tags to avoid to have 50 same `addr:housenumber`.

Sorry to be unclear, my English is a bit broken :) !

**Comment by CapitaineMoustache** [comment] 2022-01-29 13:30
The POI's "normal" adress is given by `contact` tags with this scheme. It is perhaps clearer like that!

**Comment by biodranik** [comment] 2022-01-29 15:39
Let's formalize it. There are different cases, and there are several places where addresses are used. What should be the correct behavior in these cases?
1. Should these addresses be searchable?
2. If POI has both `addr:` and `contact:`, what should be displayed in search results and in the Place Page?
3. If POI has only `contact:`, but its building has a different `addr:`, what should be displayed in search results and in the Place Page?
4. In the Place Page there is a title, subtitle, and a cell with the address (where the address is displayed now). They are used differently now depending on the feature type. How `contact:` address should be displayed here to avoid confusion?

A tricky question: a building and POI inside have different addresses. Which address should I tell a taxi driver to arrive at my destination without surprises?

**Comment by matkoniecz** [comment] 2022-01-30 07:37
> However in France, it is used like I have told.

Then French community should stop misusing this tag for different purpose.

Supporting such tag misuse in data consumers is not a good solution, please do not encourage this misuse that seems to be limited to France.

Please use standard addr: tags 

Or make a new tagging scheme (maybe `poi:housenumber`?) 

Or do not tag addressing info where it is already tagged on building polygon or a single node within building.

**Comment by CapitaineMoustache** [comment] 2022-11-15 02:37
My answer at last (sorry for the delay! :$)
I quickly resume the conception of the use of addresses with `contact:` key, such as described in the ["Schéma de Charlieu"](https://wiki.openstreetmap.org/wiki/Le_Sch%C3%A9ma_de_Charlieu_:_une_proposition_autour_des_adresses) page:

- `addr:` addresses should be mapped separately, following the OSM idea: ["One feature, one OSM element"](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element), notably in order to allow more precise mapping of addresses for routing and also avoid some duplicates.
- `contact:` addresses on POI's should be considered simply as attribute data: it's the main address where the POI can be found or contacted.

I add that this schema is more and more used in Western Europe (see [TagInfo](https://taginfo.openstreetmap.org/keys/contact:housenumber#chronology) more than 30000 worldwide, especially in France) in the way I described: almost all POI's with `contact:` addresses (**94%**) don't have `addr:` tags according to TagInfo).
![2](https://user-images.githubusercontent.com/72600146/201810058-228411ec-d134-48a3-b3f1-20fd69e86f29.png)
![Screenshot 2022-11-15 at 02-56-06 contact housenumber Keys OpenStreetMap Taginfo](https://user-images.githubusercontent.com/72600146/201808060-18f8398a-b892-42ec-9c4b-0cba03876a3d.png)
![Screenshot 2022-11-15 at 02-55-59 contact housenumber Keys OpenStreetMap Taginfo](https://user-images.githubusercontent.com/72600146/201808062-11e4ec82-cd2e-4ecb-84f0-3b4f3c934ffc.png)



> Let's formalize it.

Let's go :)

1.  I would say `contact:` addresses should not be used for routing (in the way it's done with `addr:`) but it would be useful to display corresponding POI in the search bar.
2. If POI has both `addr:` and `contact:`, `contact:` addresses should be primarily displayed for Place Page, if `contact:` absent, `addr:` can still be displayed instead (following classic schema).
3. Just as for 2, `contact:` addresses on POI's should be always be primarily displayed.
4. Use also `contact:` address primarily.

As examples, [Qwant Maps](https://www.qwant.com/maps/place/osm:node:5253578496@Linvosges#map=17.74/48.1138240/-1.6781852) already primarily display keys `contact:` for POI's addresses, then `addr:` if `contact:` keys are absent then address extrapolation if none, as far as I know.
![Screenshot 2022-11-15 at 03-26-13 Le Carnet à Spirales](https://user-images.githubusercontent.com/72600146/201811393-f067d5ff-9474-41c7-868f-cff2453232e4.png)

[OpenStreetBrowser](https://www.openstreetbrowser.org/#gastro/n2959298153/details&map=18/46.15807/4.17301&categories=gastro) simply displays both when `addr:` and `contact:` are present.
![Screenshot 2022-11-15 at 03-25-55 OpenStreetBrowser](https://user-images.githubusercontent.com/72600146/201811403-80ce3d16-9afb-49d1-99ee-6342e4658798.png)



English is not my first language, far from it, however I hope to help this fantastic app to be... even more fantastic!

**Comment by matkoniecz** [comment] 2023-04-29 11:33
> addr: addresses should be mapped separately, following the OSM idea: ["One feature, one OSM element"](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element), notably in order to allow more precise mapping of addresses for routing and also avoid some duplicates.

If someone really want to map address of a poi, then they should use addr: tags - this does not violate "One feature, one OSM element" as address is attribute of a a POI.

Mapping actual addresses with contact: that is for contact address, distinct from physical address is very unhelpful and French community should not expect anyone to support them. And as is, they are more likely to cripple contact:* usage for anything rather than redefine it as duplicate of addr:*

**Comment by map-per** [comment] 2023-08-29 19:51
I'm a little confused here:
Looking at (1) https://www.openstreetmap.org/node/677967806 it looks like OM already supports `contact:housenumber`. And for building areas `contact:housenumber` is rendered just like `addr:housenumber` ((2) https://www.openstreetmap.org/way/492064420).

But using github search I can't find any occurance of contact:housenumger in the code. Why does this happe so often, that I can't find the code section?

| (1)| (2)|
|--------|--------|
| ![Screenshot_2023-08-29-11-04-18-377_app organicmaps](https://github.com/organicmaps/organicmaps/assets/79519062/1eb463f6-f6f4-4996-bf44-8d21e6febff6) | ![Screenshot_2023-08-29-11-43-24-656_app organicmaps](https://github.com/organicmaps/organicmaps/assets/79519062/456e50aa-6315-41d3-82a1-17991a052201) |

**Comment by biodranik** [comment] 2023-08-29 22:11
@map-per its WIP experimental changes as a part of search refactoring and improvements.

**Comment by cayenne17** [comment] 2024-05-05 08:58
@CapitaineMoustache, @Jean-BaptisteC Now it's displayed. Can the problem be closed?

**Closed** 2024-05-12 17:59 UTC
Labels: Regional, Address

**Comment by CapitaineMoustache** [comment] 2024-05-13 18:24
I come a bit too late surely!
But `contact:housenumber` should not be displayed on the map, `addr:housenumber` is more relevant, anyway, it's fine to see POI's addresses displayed on popup boxes and in search bar, great work!

**Comment by biodranik** [comment] 2024-05-13 18:54
Can you please provide examples where it is displayed? Let's create another issue for it.
