### ISSUE TITLE
Unnecessary SlightTurn directions in some situations

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2262] opened 2022-03-18 09:04 UTC
For some reason I have notification 'Keep left' here, moving by main road to cross-road.
Take a note that this is Cyprus (left-side driving).
In fact a lot such kind of notifications can be heard.
Maybe this is somehow related to the fact that most of roads in Cyprus are not straight.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/85622715/158972165-7ec4fd46-cbb3-4bd8-ab24-cc58f41f600e.png">

https://omaps.app/4yxfvno7P6/Strovolou_Avenue
om://4yxfvno7P6/Strovolou_Avenue

**Comment by CorruptComputer** [comment] 2022-03-18 14:51
I think this is a duplicate of #2238

**Comment by AntonM030481** [comment] 2022-03-18 16:49
Agree. Very similar one.
Route:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=35.14404%2C33.34396%3B35.14498%2C33.34465

**Comment by AntonM030481** [comment] 2022-03-18 17:23
My suggestion is to not voice if:
all roads except 1 deviate more then (90 - alpha) degrees from current direction
and 1 road deviates less then (alpha) degrees from current direction

if there is 1 main road road we increase alpha trying to follow main road.
E.g. for alpha = 10

2 equal roads angles:  
5, 85 - no voice.
5, 75! - voice
15!, 85 - voice

2 roads. first primary. alpha increase to 20 trying to follow main road
15, 75 - no voice
25!, 75 - voice
15, 65! - voice
75!, 5 - voice
85, 15! - voice

**Comment by biodranik** [comment] 2022-03-20 22:45
The problem is not in the voice but in the underlying directions. There are some unnecessary directions inserted by the algorithm. More examples where other routers don't have unnecessary turns, but OM has them, will be helpful.

Announcing a turn on the main road with clearly visible secondary roads is completely unnecessary, right? If there are no directions, then it means "continue forward on the current road", right?

**Comment by AntonM030481** [comment] 2022-03-21 20:15
Exactly!

**Comment by AntonM030481** [comment] 2022-03-24 12:05
Is it correct that white arrows - guidance points? If so it's I can easily provide a lot of examples. 
![image](https://user-images.githubusercontent.com/85622715/159912060-da61b6ae-109a-4486-9e4f-b917254c6e82.jpeg)
https://omaps.app/wyxfvwrQz-/

**Comment by AntonM030481** [comment] 2022-03-24 12:26
![image](https://user-images.githubusercontent.com/85622715/159915882-582b088b-8807-4365-a771-eb7d10491f2c.png)

**Comment by biodranik** [comment] 2022-03-24 19:50
> Is it correct that white arrows - directions points? If so it's I can easily provide a lot of examples.

Correct, thanks!

**Comment by AntonM030481** [comment] 2022-03-24 22:48
Can you explain current algorithm of determination of directions?
Looks like it is now: 
for all intersections:
 if abs(path change angle) > alpha:
  direction = true
 else:
  direction = false

**Comment by AntonM030481** [comment] 2022-04-13 17:20
I checked the code for function **GetTurnDirection**.
It uses the function **KeepTurnByHighwayClass**
I have created function **KeepTurnByAlignedAlternatives** using the same design and tested it. It fixed most of issues for me.
```
/// * \returns true when
/// * - any alternative turn to bigger road
/// * - or any alternative turn to similar road if turns less then 70 degress (wider than SlightTurn)
/// * - or any alternative turn to smaller road if turns less than SlightTurn
/// * Returns false otherwise.
/// \param possibleTurns is all possible ways out from a junction.
/// \param turnInfo is information about ingoing and outgoing segments of the route.
bool KeepTurnByAlignedAlternatives(TurnCandidates const & possibleTurns, TurnInfo const & turnInfo,
                           NumMwmIds const & numMwmIds)
{
  // Note. The bigger road the less HighwayClass value.
  ftypes::HighwayClass m_smallestRouteRoadClass =
      static_cast<ftypes::HighwayClass>(max(static_cast<int>(turnInfo.m_ingoing.m_highwayClass),
                                            static_cast<int>(turnInfo.m_outgoing.m_highwayClass)));

  // The turn should be kept if there's no any information about feature id of outgoing segment
  // just to be on the safe side. It may happen in case of outgoing segment is a finish segment.
  Segment firstOutgoingSegment;
  if (!turnInfo.m_outgoing.m_segmentRange.GetFirstSegment(numMwmIds, firstOutgoingSegment))
    return true;

  Segment inversedLastIngoingSegment;
  if (!turnInfo.m_ingoing.m_segmentRange.GetLastSegment(numMwmIds, inversedLastIngoingSegment))
    return true;
  inversedLastIngoingSegment.Inverse();

  for (auto const & t : possibleTurns.candidates)
  {
    // Let's consider all outgoing segments except for
    // (1) route outgoing segment
    // (2) a U-turn segment (inversedLastIngoingSegment)
    if (t.m_segment == firstOutgoingSegment || t.m_segment == inversedLastIngoingSegment)
      continue;
    ftypes::HighwayClass const highwayClass = t.m_highwayClass;
    // Note. The bigger road the less HighwayClass value.
    if (static_cast<int>(highwayClass) < static_cast<int>(m_smallestRouteRoadClass))
    {
      // any alternative turn to bigger road causes keep turn
      return true;
    }
    else if (static_cast<int>(highwayClass) == static_cast<int>(m_smallestRouteRoadClass))
    {
      // any alternative turn to similar road causes keep turn if turns less then 70 degress (wider than SlightTurn)
      if (fabs(t.m_angle) < 70)
        return true;
    }
    else
    {
      // any alternative turn to smaller road causes keep turn if turns less than SlightTurn
      if (IsGoStraightOrSlightTurn(IntermediateDirection(t.m_angle)))
        return true;
    }
  }
  return false;
}
```

**Comment by biodranik** [comment] 2022-04-14 00:08
Awesome! What cases are still not detected properly?

CC @vng

**Comment by vng** [comment] 2022-04-14 06:54
@AntonM030481 Please, make a PR with your changes.

**Comment by AntonM030481** [comment] 2022-04-14 07:02
In fact it solved all my cases with unnecessary SlightTurns. Compare:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/85622715/163331347-6856830b-ad64-4802-b23b-2a48a90e4ad1.png"> <img width="408" alt="image" src="https://user-images.githubusercontent.com/85622715/163330863-3664149e-ca22-4a5d-b8be-cec40f0aa4fb.png">

**Comment by AntonM030481** [comment] 2022-04-14 07:34
BTW this helped me to identify road mapping issues.
E.g. here turn is kept, because of allowance of going back using the primary road link.
The question is only about TurnSlightLeft direction.
Maybe we need to convert it to GoStraight if all alternatives turn more then 90 degress:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/85622715/163334447-5c0a6b80-b927-439a-9980-2a12bb83d61d.png">

This is more tricky one. Let's agree that direction is still needed here.
But TurnSlightLeft is questionable again.
Maybe we need to convert it to GoStraight if all alternatives turn more then current turn in the same direction:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/85622715/163335771-b92607f3-a81f-48fb-bdde-1c53fcb1aa93.png">

**Comment by biodranik** [comment] 2022-04-14 11:54
Probably "go straight" is a good option.
Alternatively, using Keep Left in the first one would be safer for drivers if there is an alternative right turn/U-turn (the idea is to avoid a wrong right turn). In the second example, the current instruction is obviously a bug, the proper instruction should be Keep **Right**, not Left, to avoid the obviously incorrect left turn/link. *Keep Straight* would also be ok.

**Comment by biodranik** [comment] 2022-04-14 11:55
In any case, your current implementation is better than the existing one. Let's check it in reality. Can you please create a PR?

**Comment by AntonM030481** [comment] 2022-04-14 15:11
> In any case, your current implementation is better than the existing one. Let's check it in reality. Can you please create a PR?

Sure. This is my 1st pull request to GitHub, so it's a bit challenging :)
#2397

**Closed** 2022-04-15 19:11 UTC
Labels: Navigation
