### ISSUE TITLE
Alert if over speed limit on Android

### ISSUE THREAD

**Issue by IronMaltese** [organicmaps/organicmaps#4628] opened 2023-02-27 01:46 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example:
I'm always frustrated when [...]

I want to know if I’m above 10 over the speed limit or any amount above the speed limit, so this should be configurable to avoid blissfully driving too fast in areas

**Describe the solution you would like**
A clear and concise description of what you want to see in Organic Maps.

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
- Attach any examples, screenshots, or screen recordings from other apps that help us to better understand the idea.

**Additional context**

**Comment by Altonss** [comment] 2023-02-27 12:11
This seems to be duplicate of https://github.com/organicmaps/organicmaps/issues/3711, and from reading this issue it already seems to be implemented (by a red warning)...

**Comment by ddpasa** [comment] 2023-04-03 18:05
> This seems to be duplicate of #3711, and from reading this issue it already seems to be implemented (by a red warning)...

It's not implemented in Android.  It only alerts if there is a speed camera coming up, but not generally.

**Closed** 2023-07-09 10:08 UTC
Labels: Duplicate
