### ISSUE TITLE
Confirmation on deleting bookmark

### ISSUE THREAD

**Issue by Wrobin88** [organicmaps/organicmaps#7488] opened 2024-02-27 17:08 UTC
It is too easy to accidentally delete a saved bookmark from the Map screen - just tap the "Delete" star at the bottom of the screen and it's gone.  Could there be a confirmation message before the bookmark is deleted, like "Delete bookmark?"  with a button to confirm.  This would save some aggravation!
Thanks.

**Comment by Jean-BaptisteC** [comment] 2024-02-27 17:47
Duplicate of #1173

**Closed by Jean-BaptisteC** 2024-02-27 17:47 UTC
Labels: Enhancement
