### ISSUE TITLE
(Android) Completely disable locations services popup

### ISSUE THREAD

**Issue by ghtesting2020** [organicmaps/organicmaps#4664] opened 2023-03-01 19:36 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i launch Organic Maps and i don't have locations services on which is about 99% of the time and i try to use Organic Maps for fun or trip planning. I don't think it happens every time but maybe after a user change and back or restart. Drived me crazy. I know location isn't on. There's a very clear button for it in the bottom right. On top of that the message is in a bright white box. When using dark mode it's intrusive.

**Describe the solution you would like**
Please add a toggle in options to never be alerted by the pop up. You can leave it for the iKiddies but at least in Android for the love of God make it toggleable.

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
I press close on that goddamned button 5 times a day and swear under my breath.

**Additional context**
This is my only issue with Organic Maps. Othwrwise it is 10/10

**Comment by Altonss** [comment] 2023-03-02 08:56
> On top of that the message is in a bright white box. When using dark mode it's intrusive.

This specific issue has already been detected in #4562 and being worked (in https://github.com/organicmaps/organicmaps/pull/4665 for example) :)

**Comment by biodranik** [comment] 2023-03-14 17:54
@ghtesting2020 Does it reproduce when you close OM with the location disabled (a crossed crosshair button under zoom buttons)?

**Comment by rtsisyk** [comment] 2023-06-04 08:02
This is the same issue as in #4390. Can we close this ticket and track this issue in #4390?

**Comment by rtsisyk** [comment] 2023-11-17 08:31
This is a duplicate of https://github.com/organicmaps/organicmaps/issues/1128 and it will be fixed by https://github.com/organicmaps/organicmaps/pull/6435. Please subscribe.

**Closed by rtsisyk** 2023-11-17 08:31 UTC
Labels: Duplicate, Android, GPS
