### ISSUE TITLE
Strange display of the bottom panel

### ISSUE THREAD

**Issue by neonxp** [organicmaps/organicmaps#972] opened 2021-07-31 22:29 UTC
![IMG_8381](https://user-images.githubusercontent.com/190940/127753827-80dde946-9d0c-454b-ae9b-11242b3f8ca4.jpg)

Device: Farcar s400
OS: Android 10
Display: 1024x768

**Comment by biodranik** [comment] 2021-08-01 09:49
Thanks! Looks like some layout issue. We can try to reproduce it in the Emulator with the same OS and resolution.

**Comment by Endem10n** [comment] 2021-08-01 10:08
@biodranik we already fixed this bug in https://github.com/organicmaps/organicmaps/pull/828/commits/c477c0b80d8ab18bbdd4655417c02f390da88345
This fix will be delivered to users with next app update.

**Comment by biodranik** [comment] 2021-08-01 10:23
Awesome! @neonxp please let us know if the bug was fixed in the upcoming update.

**Comment by neonxp** [comment] 2021-08-07 11:05
Just updated from play store. Bug is gone 👍

**Comment by biodranik** [comment] 2021-08-07 13:15
Great, thanks!

**Closed by biodranik** 2021-08-07 13:15 UTC
Labels: Bug, Android, UI
