### ISSUE TITLE
opening_hours parser can't parse some "off" cases

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#1612] opened 2021-11-24 16:39 UTC
If "off" day is the first item in `opening_hours` then it's not parsable by OM.

## Case good
E.g. https://www.openstreetmap.org/node/4318534651 → `Tu-Su 11:00-01:00; Mo off`
Monday is snown as off day:

![mo_off_good](https://user-images.githubusercontent.com/720808/143278295-4f4b382d-fc58-43a5-8dd1-de2e77bcd621.png)

## Case bad
With museum https://www.openstreetmap.org/node/6403156110 → `Mo off; Tu-Fr 10:00-19:00; Sa,Su 10:00-14:00`
Opening hours are unparsed:
![mo_off_bad_2](https://user-images.githubusercontent.com/720808/143278833-857bb347-f7f9-4968-8f33-59b9b815f821.png)

**Comment by biodranik** [comment] 2021-11-24 17:55
Isn't it a duplicate?

**Comment by strump** [comment] 2021-11-24 20:05
I thought about #1575 but can't tell if it duplicates this issue.

**Comment by biodranik** [comment] 2021-11-24 21:36
Interesting, looks like an Android-only bug, because it works on iOS.

**Comment by mehmetozturk-re** [comment] 2021-11-25 09:10
Can i work on this?

**Comment by biodranik** [comment] 2021-11-25 17:46
Anyone can work on anything :) Please don't ask, just do it!

**Comment by strump** [comment] 2021-11-27 20:29
> Interesting, looks like an Android-only bug, because it works on iOS.

@biodranik it’s reproducible on my iPad. Probably caused by `3party/opening_hours` code. Where this parsing code came from?

![1E5D87A7-1BC1-433A-96CF-6BD3867A96D9](https://user-images.githubusercontent.com/720808/143721363-938e6478-ed77-4ec5-9f4d-ce072dd0e446.jpeg)

**Comment by biodranik** [comment] 2021-11-27 23:30
You're right, this one reproduces on my iPhone too. That code was written by one of the mailru devs. Despite my strong resistance, he chose boost spirit parser. The current implementation has many bugs and doesn't parse everything. We even disabled unit tests for it.

**Comment by gpesquero** [comment] 2024-03-22 17:33
@strump: Please review [PR 7652](https://github.com/organicmaps/organicmaps/pull/7652) and check if we can close this issue.

**Closed** 2024-06-02 13:39 UTC
Labels: Opening Hours
