### ISSUE TITLE
Node links in Organic Maps do not link to nodes

### ISSUE THREAD

**Issue by Gnorv** [organicmaps/organicmaps#3344] opened 2022-09-04 22:07 UTC
When selecting a node in Organic Maps and opening its openstreeetmap link from the pull up menu, this link does not refer directly to the node itself but to the coordinates where the node is. I think it would be preferable to link to the node directly, or offer both options. Often I want to open a node on the OSM website to see if it is of a newer version than inside Organic Maps, or to see its previous edits. I included a screemshot below with this link [https://osm.org/go/0ChUqfxa-?m=](https://osm.org/go/0ChUqfxa-?m=) marked red. It links to coordinates, not to the railway station I selected in Organic Maps.
![Screenshot_20220905-000403_Organic Maps](https://user-images.githubusercontent.com/48286377/188335216-d9b58d62-f554-478c-b45d-3eacf17d2b17.jpg)

**Comment by jpds** [comment] 2022-09-04 23:07
Duplicate of #2421 - OM doesn't store OSM IDs.

**Comment by Gnorv** [comment] 2022-09-05 21:44
> Duplicate of #2421 - OM doesn't store OSM IDs.

As I habe understood from the older issue the OSM IDs are not stored inside OM data. How hard would it be to add them to the dataset? Also, if the ID is not stored, how does OM know what OSM node to associate changes I did inside OM, for example when I added business hours? I thought for this the node ID is needed.

**Comment by endim8** [comment] 2022-09-10 20:29
> As I habe understood from the older issue the OSM IDs are not stored inside OM data. How hard would it be to add them to the dataset? Also, if the ID is not stored, how does OM know what OSM node to associate changes I did inside OM, for example when I added business hours? I thought for this the node ID is needed.

This comment: https://github.com/organicmaps/organicmaps/issues/1597#issuecomment-983148035
says that storing all OSM IDs 'will notably increase maps data size'

it also describes how the editor associates changes with the OSM database 👍

also kinda duplicate of https://github.com/organicmaps/organicmaps/issues/1597

**Closed** 2022-09-11 07:05 UTC
