### ISSUE TITLE
Opening hours not processed & impossible to edit

### ISSUE THREAD

**Issue by Kazing** [organicmaps/organicmaps#1366] opened 2021-09-30 11:26 UTC
opening_hours data of a POI cannot be processed correctly by the Android app : 
* OSM node : https://www.openstreetmap.org/node/3097464312
* Opening hours :  `Mo-Fr 11:30-14:00, Mo-Su 18:00-22:30`

It shows like that : 
![screenshot1](https://user-images.githubusercontent.com/41507326/135441396-6dc608bd-b145-4b20-89d5-41c1ba2f85b4.png)

This syntax seems to be correct, according to this tool : https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2011%3A30-14%3A00%2C%20Mo-Su%2018%3A00-22%3A30

Also when I try to edit the opening hours, it show a blank page
1. Click "Edit this place"
1. Click "Edit business hours"
2. A blank page appear :
![screenshot2](https://user-images.githubusercontent.com/41507326/135441428-08ea323e-ece7-4753-8e60-593b78e07b3a.png)

Could be related to #970

## System

* OS: Android 9
* Organic Maps version: 2021.09.14-4-FDroid
* Data Version: 210825

**Comment by kudlav** [comment] 2021-10-04 19:58
duplicate of https://github.com/organicmaps/organicmaps/issues/1247

**Comment by biodranik** [comment] 2022-04-11 06:05
It may be related to 1247, but not necessarily. Here there are no months, just time.

**Comment by rmh2022** [comment] 2022-06-06 20:04
The following string produces same problem (blank screen) as reported by OP:

Mo-Fr 06:00-22:45; Sa,Su,PH 09:00-20:00

@biodranik said it might be related to the PH token

**Comment by rmh2022** [comment] 2022-06-08 09:37
I found another way to trigger the blank screen:

1. Open (or create) a POI with no opening_hours
2. Tap on "Business Hours"
3. Tap on "ADVANCED MODE"
4. Tap on the edit box with "24/7"
5. Type something
6. Poof. Blank screen.

Using recent git (commit 377cf0f348c8c65ceedc075b13cd003ce554f766).

**Comment by BelKed** [comment] 2023-07-17 06:57
This seems to be a duplicate of #3077 and was resolved in #3159.
Is there anything preventing it from being closed?

**Comment by rmh2022** [comment] 2023-07-17 08:36
Hi

With my current version (2023.07.13-4-FDroid) I can't reproduce this anymore:

> I found another way to trigger the blank screen:
> 
>     1. Open (or create) a POI with no opening_hours
> 
>     2. Tap on "Business Hours"
> 
>     3. Tap on "ADVANCED MODE"
> 
>     4. Tap on the edit box with "24/7"
> 
>     5. Type something
> 
>     6. Poof. Blank screen.
> 
> 
> Using recent git (commit [377cf0f](https://github.com/organicmaps/organicmaps/commit/377cf0f348c8c65ceedc075b13cd003ce554f766)).

**Closed** 2023-10-20 18:42 UTC
Labels: Bug, Core, Editor
