### ISSUE TITLE
Feature idea: maps MWM files import/share (a la GPX/KML/KMZ)

### ISSUE THREAD

**Issue by akruphi** [organicmaps/organicmaps#8742] opened 2024-07-21 07:01 UTC
Idea after yesterday problem maps downloading on Android 7- https://github.com/organicmaps/organicmaps/issues/8737

May be add possibility to work with __*.mwm__ files a la __gpx__/__kml__/__kmz__?

Import __*.mwm__ will be quick alternative if user have problem with direct download from OM site maps repository.

Share region map will give ability to quick share map to neighbour people (with same OM version) in places with bad/roaming/restricted internet.

**Comment by Jean-BaptisteC** [comment] 2024-07-21 07:56
Duplicate of #1801

**Closed by Jean-BaptisteC** 2024-07-21 07:56 UTC
Labels: Enhancement
