### ISSUE TITLE
[iOS] can not log in to OpnStreetMap account

### ISSUE THREAD

**Issue by pointlessone** [organicmaps/organicmaps#797] opened 2021-07-03 10:05 UTC
I’m getting “Invalid username or password” message.

The credentials are correct. I can log into my OSM account in Safari.

This happens both in the stable and beta versions of the app.

I run iOS 15 public beta 2. I don’t know if this is relevant or whether the issue is present on stable iOS.

**Comment by biodranik** [comment] 2021-07-03 10:59
This is a new bug caused by changes in OSM login flow by OSM developers. We've prepared a fix, please wait for the update.

**Comment by jancborchardt** [comment] 2021-07-05 12:40
@biodranik I'm also getting the issue "Login error" on Android (already since 1-2 weeks). I assume it's the same issue as with iOS, and the fix is also upcoming? Thank you! :)

**Comment by biodranik** [comment] 2021-07-05 12:40
Yes

**Comment by rtsisyk** [comment] 2021-07-13 09:38
This problem has been fixed in the latest update. Please update.

**Closed by rtsisyk** 2021-07-13 09:38 UTC
