### ISSUE TITLE
Display speed limitation

### ISSUE THREAD

**Issue by Djey51** [organicmaps/organicmaps#8024] opened 2024-04-28 13:06 UTC
Hi,

Could you please add the folowing feature?
Add an option to display the dynamic speed limitation near the current speed in mode car navigation. And also a setting to alert the driver when the current speed is x>speed limitation where x can be set in the option menu.

Thanks

**Comment by Jean-BaptisteC** [comment] 2024-04-28 14:18
Duplicate of #952

**Closed by Jean-BaptisteC** 2024-04-28 14:18 UTC
Labels: Enhancement
