### ISSUE TITLE
Map fling gesture not working on Samsung S21 Ultra

### ISSUE THREAD

**Issue by jfitie** [organicmaps/organicmaps#987] opened 2021-08-02 19:04 UTC
No inertia, scroll stops immediately after lifting finger. Works just fine on other devices I tested (Samsung A12, S9+, S8). Latest version from Google Play Store.

**Comment by biodranik** [comment] 2021-08-05 21:03
Are there any specific settings for this device that may control the inertia? Like a battery-saving mode that disables animations, or some specific development settings?

**Comment by jfitie** [comment] 2021-08-06 04:26
@biodranik No, and it works fine in other apps like Google Maps. Had the same issue in Maps.me.

**Comment by biodranik** [comment] 2021-08-06 09:11
Interesting. Can you please enable logs in settings and share them with us either here or at bugs@organicmaps.app?

**Comment by robsmith11** [comment] 2022-03-01 05:25
I have the same issue on my Samsung Fold 3.  I've sent the logs to the email address provided.

**Comment by biodranik** [comment] 2022-03-01 07:51
Are there any swing/fling options/gesture sensitivity in device's settings -> display -> navigation bar -> more options? Did you try to change them?

**Comment by robsmith11** [comment] 2022-03-01 09:18
No,  I don't see anything like that.  The closest setting is that I have animations turned off.   I turned animations back on, but it made no difference.

**Comment by biodranik** [comment] 2022-03-01 09:54
Interesting, that only some newest Samsung devices have this issue. Looks like Samsung has changed something, or added some specific settings. And it's hard to debug without such a device in our hands.

Can you please try to install this debug version (it will be a separate application), enable logs, restart the app, reproduce the issue several times, and then send us logs back?
https://cdn.organicmaps.app/apk/OrganicMaps-22022702-google-debug.apk

**Comment by robsmith11** [comment] 2022-03-01 11:24
Hmm.. I get an error trying to install it "There was a problem parsing the package".

I've been putting off upgrading to Android 12.  Maybe I should wait until i do that to debug more.

**Comment by biodranik** [comment] 2022-03-01 12:04
@robsmith11 please try again the apk from the above link, I've updated it with all ABI architectures. Maybe it was the issue.

**Comment by endim8** [comment] 2022-08-20 19:40
same as https://github.com/organicmaps/organicmaps/issues/2652

**Comment by RedAuburn** [comment] 2023-11-03 12:10
Fixed by https://github.com/organicmaps/organicmaps/pull/6237

**Closed by RedAuburn** 2023-11-03 12:10 UTC
Labels: Bug, Android
