### ISSUE TITLE
Inconsistent display of names at larger zoom levels

### ISSUE THREAD

**Issue by kmpoppe** [organicmaps/organicmaps#9042] opened 2024-08-21 12:13 UTC
**Describe the issue**
Notes [3932565](https://www.openstreetmap.org/note/3932565) & [4392618](https://www.openstreetmap.org/note/4392618) complained that the German city of "Hameln" was displayed as "Hamelin" in Organic Maps.

It would seem that the decision what name to display (`name` or `name:en`) is inconsistent in the app, the City of "Hannover" is correctly tagged with `name:en=Hanover`, but that isn't shown in the zoom level where Hamelin is shown.

**Steps to reproduce**
Move the map to have roughly "Springe" in the center of the screen with Hameln and Hannover equi-distant from it as shown in the image below, zoom out until the name of Hameln changes to Hamelin.

**Expected behaviour**
The app is forced to run in German, it seems strange to have the map show English town names, even more so, when `name` as the local name and `name:de` exist.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/1b129d94-2333-458b-90ae-36b9fd5e08b5)

**System information:**
 - Android 12 on Samsung M33
 - Organic Maps version 2024.08.15-21-FDroid

**Comment by biodranik** [comment] 2024-08-21 12:19
1. What are your system languages?
2. How did you "force" the DE language for OM on Android 12?

**Comment by kmpoppe** [comment] 2024-08-21 12:31
The system language is English. Samsung Android App Settings allow you to set the Language the app shall run in is diffrent from the system default. It's set to German (Germany) and perfectly displays all strings in the app in German.

Additionally, reporters of the above mentioned Notes wrote their text in German, my best guess is that their app also ran in German, whether forced or due to system default.

Before forcing the App the run in German (i.e. it showing the application strings in English) the town centre had "Hamelin" in slightly larger letters displayed above "Hameln" in slightly smaller letters, which seems like a good UI decision.

**Comment by biodranik** [comment] 2024-08-21 12:39
What happens if the system language is set to German? Maybe Samsung's "force language" feature only forces app string resources, without changing the locale retrieved from the app's code.

**Comment by kmpoppe** [comment] 2024-08-21 13:01
No change compared to the screenshot above when changing the System language to German, sorry.

**Comment by biodranik** [comment] 2024-08-21 13:09
@kmpoppe note that the app should be killed/restarted for system changes to take effect.

Your issue does not reproduce with the system language set to German.

**Comment by kmpoppe** [comment] 2024-08-21 13:12
Of course I killed the app before restarting it after changing the System Language

For me, the issue is reproduceable.

**Comment by biodranik** [comment] 2024-08-21 13:21
Can you please connect a usb cable, restart OM, and check the `adb logcat` output for a string `System languages` and see which language is printed there? Or enable logs in OM settings, restart OM, and then send logs to us or to yourself and check the same string value?

**Comment by kmpoppe** [comment] 2024-08-21 13:26
`08-21 15:24:02.786 (main) I/OMcore: map/framework.cpp:352 Framework(): System languages: de_DE`

**Comment by map-per** [comment] 2024-08-21 19:17
The `name:de` was added to Hameln only recently (on July 9.) (https://pewu.github.io/osm-history/#/node/1409665812), so maybe that's the problem. Is your World map up to date? (Your screenshot shows three maps that are not up to date).

I can't reproduce that problem with the latest 2024.08.17-4-Google version but the error shows up in an old debug version (2024.04.04-65-FDroid-debug).

**Comment by kmpoppe** [comment] 2024-08-22 05:32
Yep, the World Update fixed that - presumably with newer data.
I guess the behaviour itself will still be there, alas, there are no other `place` nodes in Germany, that have `name`, a different `name:en` but no `name:de` and that are large enough to be displayed in the world-scale (10 km).
So ... Yay?

**Comment by map-per** [comment] 2024-08-22 06:56
It looks like OM falls back to English if no local language is specified in the OSM data. That's a very reasonable design decision in my opinion, so I would close this issue.

As soon as an object in OSM has multilingual names also the language from `name` should be added (in this case `name:de`). So this was a quality assurance problem in the OSM database.

**Closed by map-per** 2024-08-22 06:56 UTC
Labels: Core

**Comment by biodranik** [comment] 2024-08-22 07:14
OM falls back to international first, and to English second.
