### ISSUE TITLE
Don't show app before lock screen when using isn't in navigation mode

### ISSUE THREAD

**Issue by Outlet2048** [organicmaps/organicmaps#2139] opened 2022-02-18 10:45 UTC
The latest update changed it so that the app will be shown without having to unlock your screen. Which is great when you're navigating

Buuut when I'm just looking up what stores are open near me, then lock the screen im expecting my phone to be locked properly instead of showing me organic maps again before unlocking the phone.

My suggestion: this "always unlocked" mode should only be active when the user is currently using navigation mode

**Comment by pastk** [comment] 2022-02-18 12:34
Yeap I'm having a short look at the map often (no navigation) and then turn off the screen and put it into my pocket to pull it out again a few minutes later... And for me its very convenient that now I don't have to unlock the phone every time.

**Comment by AlertSubject** [comment] 2022-02-18 16:18
I'm not a fan of my phone appearing unlocked when all I want to see is the lock screen.

Let's say I scroll the map to see something but without using navigation. After that I lock the phone because I'm done with what I needed the app for
And later I want to check the lock screen or use another app

In this case I click the on/off button and get greeted with an app already running, have swipe up as if I were to minimize the app, and then I'm greeted with a lock screen again

And if I want to actually unlock the phone to use another app, I still have to enter my passcode / fingerprint

Therefore, not minimizing the app before locking my phone = having to spend more time to get where I want to get the next time I pick up my phone


The only time Where's it's useful to be presented with the app right away is when I'm in navigation
(which is also how other apps handle this)

Changing the default behavior to "unlocked during navigation only" might also be less confusing to new users or users less familiar with these options. A new user migit wonder as to why his lock screen has been replaced with a maps app for no good reason, especially when no other app handles it like this

**Comment by biodranik** [comment] 2022-02-18 16:36
Some users actively use maps without navigation, especially in longer hikes, to save the battery. For them, it would be preferable to always see the map after unlock.

I think we can cover all cases by changing the current on/off setting to a 3-ways setting. The default value can stay the same as it is now, to make it more discoverable by users. Those who don't like it can easily turn it off, or change to a "nav-only" mode.

**Comment by TheLastProject** [comment] 2022-05-01 18:58
I think the main thing that needs to be thought of with this feature is: is the screen the current user is on sensitive enough to protect by a lock screen?

Currently, Organic Maps always calls `Utils.showOnLockScreen` in every single activity (through the base activity) without any concern as to how private or not the screen is.

For starters, the Settings screen should probably never be above the lock screen as you wouldn't want a random person to be able to change your settings while your device is unlocked.

**Comment by RedAuburn** [comment] 2024-03-22 15:59
duplicate of https://github.com/organicmaps/organicmaps/issues/1578

**Closed by RedAuburn** 2024-03-22 15:59 UTC
Labels: Android, UX
