### ISSUE TITLE
Split screen support in carplay

### ISSUE THREAD

**Issue by ghobs91** [organicmaps/organicmaps#7141] opened 2024-01-11 17:00 UTC
Right now it only supports being in full screen mode, so there's no way to have organic maps on one side and music/podcast player on the other.

Apple Maps, Google Maps, and Magic Earth support this, if a reference is needed.

**Comment by fabwu** [comment] 2024-01-16 04:36
@Jean-BaptisteC This is a duplicate of https://github.com/organicmaps/organicmaps/issues/6184 and can be closed

**Closed** 2024-01-16 05:36 UTC
Labels: Duplicate, CarPlay
