### ISSUE TITLE
Localize UI strings in the desktop version

### ISSUE THREAD

**Issue by papoteur-mga** [organicmaps/organicmaps#9908] opened 2024-12-20 10:38 UTC
**Describe the issue**
Although my desktop is configured in French, the launched application is in English. I expect it in French.
Through "Help", "Preferences", I can set the language for the maps, it is already set to French.

**Steps to reproduce**
1. Launch from menu
2. See "Help", should be "Aide"

**System information:**
 - Operating system and its version: Mageia Cauldron
 - Organic Maps version: 20241127
 - Device Model: Linux

**Additional context**
Qt 6.7

**Comment by map-per** [comment] 2024-12-21 13:52
Took a look at the code: The strings in the desktop version are not localized and always shown in English.

**Comment by pastk** [comment] 2024-12-23 08:34
- a duplicate of #2561

Please track it there.

**Closed by pastk** 2024-12-23 08:34 UTC
Labels: Translations, Desktop, UI
