### ISSUE TITLE
Search in bookmarks list doesn't search for tracks

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8962] opened 2024-08-14 20:02 UTC
1. Import several tracks, add several bookmarks with different names.
2. Search for tracks
3. Observe that only bookmark names are matched by the search

CC @vng

**Comment by Jean-BaptisteC** [comment] 2024-08-15 07:29
Duplicate of #2079

**Closed by Jean-BaptisteC** 2024-08-15 07:29 UTC
Labels: Bookmarks and Tracks, Core
