### ISSUE TITLE
Bad bicycle routes due to ignoring except=bicycle on restrictions

### ISSUE THREAD

**Issue by tguen** [organicmaps/organicmaps#7091] opened 2024-01-06 06:25 UTC
Bicycle routing uses turn restrictions even if they are tagged `except=bicycle`. This is particularly annoying due to OsmAnd having the same issue, despite it being [reported in 2017](https://github.com/osmandapp/OsmAnd/issues/3882).

[Example relation](https://www.openstreetmap.org/relation/9569893)
![Screenshot_20240105-221501_1](https://github.com/organicmaps/organicmaps/assets/57420975/31230802-67ce-4e27-bf6f-b672348ce995)

v 2023.12.18-11-Web

**Comment by biodranik** [comment] 2024-01-07 06:25
Where is the documentation for the `except` osm tag? There are around 15K worldwide uses.

**Comment by svenpilz** [comment] 2024-02-18 21:38
Maybe duplicate of https://github.com/organicmaps/organicmaps/issues/6522?

**Closed** 2024-02-23 22:42 UTC
Labels: Routing, Cycling
