### ISSUE TITLE
(Linux flatpak desktop) squealing sound when launch or using scroll wheel to zoom in out

### ISSUE THREAD

**Issue by ghtesting2020** [organicmaps/organicmaps#6782] opened 2023-12-05 13:55 UTC
**Describe the issue**
This happens whenever i launch Organic Maps desktop for a little while and then when using the scroll wheel on mouse to zoom in or out. Assuming it is caused by loading. There is a harsh squealing sound. I tried it on a school computer in Vm and happens there too so it is not just me.

**Steps to reproduce**
1. install flatpak from flathub
2. launch organic maps and squealing sound
3. use mouse scroll wheel to zoom in or out and squealing sound

**Expected behaviour**
no squealing sound

**Screenshots**
not applicable

**System information:**
Linux flatpak desktop from flathub
Version: 2023.11.17-1-1a466dce-dirty-Linux

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by RedAuburn** [comment] 2023-12-05 14:39
whaat? can you try and record it?

**Comment by RedAuburn** [comment] 2024-01-19 14:19
@ghtesting2020 can you still reproduce this?

**Comment by Misalf-git** [comment] 2024-01-19 20:37
On certain PC hardware combinations with an amplifier + speakers plugged into Audio-out, I disabled the sound card's unused Audio-in and/or Mic-in via driver settings to eliminate a hissing sound that was produced whenever the mouse was moved, presumably caused by inadequate circuit isolation.

**Comment by RedAuburn** [comment] 2024-01-24 18:29
closing as not really an OM issue

**Closed by RedAuburn** 2024-01-24 18:29 UTC
Labels: Desktop
