### ISSUE TITLE
man_made:bridge is not rendered 

### ISSUE THREAD

**Issue by euf** [organicmaps/organicmaps#3322] opened 2022-09-02 08:56 UTC
I think there is an issue with rendering bridges. It can be seen with Благовещенский мост in St. Petersburg, Russia. 

https://www.openstreetmap.org/relation/3284878

Organic maps doesn’t render the bridge outline, so footways are just floating above the water. 

![1018E668-21E5-4381-9AFE-6A2C6C919ADF](https://user-images.githubusercontent.com/11754264/188102639-9619bcdc-bfd6-4004-8557-0684f235545f.png)

https://omaps.app/04zNK491xl/Благовещенский_мост
om://04zNK491xl/Благовещенский_мост

As far as I can tell, other large bridges in St. Petersburg are affected as well.

**Comment by biodranik** [comment] 2022-09-02 11:08
Please check our issues for duplicates and reference them.

**Comment by Jean-BaptisteC** [comment] 2022-09-02 15:58
Duplicate of #3023

**Comment by euf** [comment] 2022-09-03 17:19
Sorry for the duplicate, my bad

**Comment by euf** [comment] 2022-09-03 18:47
Sorry for the duplicate, my bad

**Comment by matkoniecz** [comment] 2023-04-11 11:35
@euf If it is a duplicate - can you close it?

**Closed** 2023-04-11 14:49 UTC
Labels: Map Data
