### ISSUE TITLE
"https://" removed from URL after updating hours on business

### ISSUE THREAD

**Issue by KwisatzJim** [organicmaps/organicmaps#6502] opened 2023-11-07 01:07 UTC
**Describe the issue**
I used Organic Maps to update the hours on a local business. I only updated the hours for the business and saved. I later received a message "Hi, it looks like you removed the "https://" part of the website URL. That is required for URLs on OSM"

**Steps to reproduce**
1. top on business in Organic Maps
2. Click on 'Edit Place'
3. Change hours
4. Click 'Done'
5. Click 'Save'

**Expected behaviour**
make changes without removing the "https://" from URL

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Operating system and its version: iOS 17.1
 - Organic Maps version: 2023.09.22-20
 - Device Model: iPhone 13

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by biodranik** [comment] 2023-11-10 00:59
@strump can you please check it?

**Comment by strump** [comment] 2023-11-10 16:17
@KwisatzJim  can you share POI (coordinates, or OSM ID) you are trying to edit? I can't reproduce the issue.

**Comment by strump** [comment] 2023-11-14 16:09
Hi @KwisatzJim 
I still can't reproduce the issue. I modified opening hours and URL is unchanged:

<video src="https://github.com/organicmaps/organicmaps/assets/720808/02f500da-1233-428e-a64c-0a19a3a1b56f">
</video>

What version of OrganicMaps do you use?

**Comment by RedAuburn** [comment] 2024-04-13 17:13
Closing as unreproducible

**Closed by RedAuburn** 2024-04-13 17:13 UTC
Labels: Bug, Editor

**Comment by map-per** [comment] 2024-09-18 20:07
This bug looks like #8102. The `website` tag was overwritten with the old value it hat back when the Organic Maps map data was generated.
