### ISSUE TITLE
Add OpenTopoMaps

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#927] opened 2021-07-25 17:19 UTC
Organic Maps:

![1](https://user-images.githubusercontent.com/1799054/126907686-5c7ef420-3176-4d24-a66d-ec6541fd3862.jpg)

Mapy.cz:

![2](https://user-images.githubusercontent.com/1799054/126907687-e583ced4-cc08-4c07-bddd-460d5b92d3b2.jpg)

https://t.me/OrganicMapsRu/5757

**Comment by RedAuburn** [comment] 2024-01-19 14:06
Partially resolved by outdoors style, remaining part is duplicate of https://github.com/organicmaps/organicmaps/issues/4163

**Closed by RedAuburn** 2024-01-19 14:06 UTC
Labels: Elevation
