### ISSUE TITLE
Auto-Import / -Export of a bookmark list for synchronization

### ISSUE THREAD

**Issue by martin-braun** [organicmaps/organicmaps#5460] opened 2023-07-05 10:43 UTC
**Is your feature request related to a problem? Please describe.**
I use Maps on multiple devices and wish to sync a bookmark list. I have Syncthing that [handles potential conflicts fine](https://docs.syncthing.net/users/syncing.html?#conflicting-changes).

**Describe the solution you would like**
Just an auto export when I change anything on a bookmark list as well as an auto import when a change outside of the app is detected. This would be sufficient to avoid conflicts while both devices are online. If both are offline and change stuff, they should just export as usual. It's the responsibility of the sync software to handle conflicts.

**Describe alternatives you have considered**
As of now I'm doing all this by hand. Since I decide to edit my bookmarks only on one device, it is okay. But it is still annoying to always remember to import on the other device.

**Additional context**
There is also #5407 which would prevent conflicts in the first place, but it will require to setup a server which is not required with Syncthing, I love Syncthing for this particular reason and prefer to manually solve conflicts if I end up with any. I basically do the same for KeePass and it works pretty well for me.

Btw, [I have discussed the very same proposal for OpenContacts](https://gitlab.com/sultanahamer/OpenContacts/-/issues/256) in which I explained in detail how this can be done. The same would apply for bookmarks or any data in general.

**Comment by Jean-BaptisteC** [comment] 2023-07-05 10:56
Please check similar issues

**Comment by martin-braun** [comment] 2023-07-05 11:04
@Jean-BaptisteC I searched for "export" and "sync" and issue 5407 is the only thing that I found, which is not 100% about what I'd like to have. Am I missing something? I kindly ask you to redirect me to the right issue then. Thanks.

**Comment by Jean-BaptisteC** [comment] 2024-02-27 19:36
Duplicate of #622

**Closed by Jean-BaptisteC** 2024-02-27 19:36 UTC
Labels: Duplicate
