### ISSUE TITLE
[Desktop] Fedora 40: Unable to build desktop/generator

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#7998] opened 2024-04-26 14:15 UTC
getting:

```bash
harry@framework-13:~/Documents/Git/organicmaps$ ./tools/unix/build_omim.sh -cr generator_tool
-- The C compiler identification is GNU 14.0.1
-- The CXX compiler identification is GNU 14.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using compiler GNU 14.0.1
-- Using Unity Build with batch 50, export UNITY_DISABLE=1 or use -DUNITY_DISABLE=ON to disable it.
-- export COLORS_DISABLE=1 or use -DCOLORS_DISABLE=ON to disable colored compiler output.
-- Build type: Release
-- Using ld.gold
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib64/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib64/libxkbcommon.so (found suitable version "1.6.0", minimum required is "0.5.0") 
-- Found WrapVulkanHeaders: /usr/include  
-- Found the following ICU libraries:
--   uc (required): /usr/lib64/libicuuc.so
--   i18n (required): /usr/lib64/libicui18n.so
--   data (required): /usr/lib64/libicudata.so
-- Found ICU: /usr/include (found version "74.2") 
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.13.2") 
CMake Error at /usr/lib64/cmake/harfbuzz/harfbuzz-config.cmake:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "@PACKAGE_INIT@".
Call Stack (most recent call first):
  CMakeLists.txt:316 (find_package)


CMake Error at CMakeLists.txt:316 (find_package):
  find_package Error reading CMake code from
  "/usr/lib64/cmake/harfbuzz/harfbuzz-config.cmake".
```

on Fedora 40. all deps in INSTALL.md installed

**Comment by RedAuburn** [comment] 2024-04-26 14:20
harfbuzz already installed:

```
Package harfbuzz-8.3.0-5.fc40.x86_64 is already installed.
```

**Comment by RedAuburn** [comment] 2024-04-26 16:59
still happens after rec-cloning repo

**Comment by RedAuburn** [comment] 2024-04-26 17:14
looks like it's a fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=2277316

**Comment by map-per** [comment] 2024-04-26 17:36
Good to know, I will stick with Fedora 39 for now.

**Comment by Ferenc-** [comment] 2024-04-26 19:50
1. Issue.
Workaround [the fedora harfbuzz bug]( https://bugzilla.redhat.com/show_bug.cgi?id=2277316) simply by overwriting `/usr/lib64/cmake/harfbuzz/harfbuzz-config.cmake` with this:
````cmake
add_library(harfbuzz::harfbuzz SHARED IMPORTED)
set_target_properties(harfbuzz::harfbuzz PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
  IMPORTED_LOCATION "/usr/lib64/libharfbuzz.so.60830.0")

add_library(harfbuzz::icu SHARED IMPORTED)
set_target_properties(harfbuzz::icu PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
  INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
  IMPORTED_LOCATION "/usr/lib64/libharfbuzz-icu.so.60830.0")

add_library(harfbuzz::subset SHARED IMPORTED)
set_target_properties(harfbuzz::subset PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
  INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
  IMPORTED_LOCATION "/usr/lib64/libharfbuzz-subset.so.60830.0")

add_library(harfbuzz::gobject SHARED IMPORTED)
set_target_properties(harfbuzz::gobject PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
  INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
  IMPORTED_LOCATION "/usr/lib64/libharfbuzz-gobject.so.60830.0")
````
2. Issue
Workaround the expat issue.
For some reason expat gets configured on this version of fedora with `HAVE_ARC4RANDOM_BUF`, when it shouldn't be.
While we are digging for the root cause of this issue, this can be workarounded with a simple patch like this in `cd 3party/expat`:

````diff
diff --git a/expat/lib/xmlparse.c b/expat/lib/xmlparse.c
index 2951fec7..b1e62b82 100644
--- a/expat/lib/xmlparse.c
+++ b/expat/lib/xmlparse.c
@@ -64,6 +64,7 @@
 #define XML_BUILDING_EXPAT 1
 
 #include "expat_config.h"
+#undef HAVE_ARC4RANDOM_BUF
 
 #if ! defined(XML_GE) || (1 - XML_GE - 1 == 2) || (XML_GE < 0) || (XML_GE > 1)
 #  error XML_GE (for general entities) must be defined
 ````
 
3.  Issue
At this point you should be able to compile, but running it will lead you to https://github.com/organicmaps/organicmaps/issues/7838, because of Qt 6.7.

**Comment by Ferenc-** [comment] 2024-04-27 15:21
UPDATE: Issue 2, is a bug in expat's detection of `SYS_getrandom`, I have opened an upstream PR for that.

**Comment by biodranik** [comment] 2024-04-28 10:44
@Ferenc- thanks! Can you please reference it here, so we can update Expat as soon as it's merged?

**Comment by Arthur-GYT** [comment] 2024-05-02 07:25
> 1. Issue.
>        Workaround [the fedora harfbuzz bug](https://bugzilla.redhat.com/show_bug.cgi?id=2277316) simply by overwriting `/usr/lib64/cmake/harfbuzz/harfbuzz-config.cmake` with this:
> 
> 
> ```cmake
> add_library(harfbuzz::harfbuzz SHARED IMPORTED)
> set_target_properties(harfbuzz::harfbuzz PROPERTIES
>   INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
>   IMPORTED_LOCATION "/usr/lib64/libharfbuzz.so.60830.0")
> 
> add_library(harfbuzz::icu SHARED IMPORTED)
> set_target_properties(harfbuzz::icu PROPERTIES
>   INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
>   INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
>   IMPORTED_LOCATION "/usr/lib64/libharfbuzz-icu.so.60830.0")
> 
> add_library(harfbuzz::subset SHARED IMPORTED)
> set_target_properties(harfbuzz::subset PROPERTIES
>   INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
>   INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
>   IMPORTED_LOCATION "/usr/lib64/libharfbuzz-subset.so.60830.0")
> 
> add_library(harfbuzz::gobject SHARED IMPORTED)
> set_target_properties(harfbuzz::gobject PROPERTIES
>   INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
>   INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
>   IMPORTED_LOCATION "/usr/lib64/libharfbuzz-gobject.so.60830.0")
> ```
> 
>     2. Issue
>        Workaround the expat issue.
>        For some reason expat gets configured on this version of fedora with `HAVE_ARC4RANDOM_BUF`, when it shouldn't be.
>        While we are digging for the root cause of this issue, this can be workarounded with a simple patch like this in `cd 3party/expat`:
> 
> 
> ```diff
> diff --git a/expat/lib/xmlparse.c b/expat/lib/xmlparse.c
> index 2951fec7..b1e62b82 100644
> --- a/expat/lib/xmlparse.c
> +++ b/expat/lib/xmlparse.c
> @@ -64,6 +64,7 @@
>  #define XML_BUILDING_EXPAT 1
>  
>  #include "expat_config.h"
> +#undef HAVE_ARC4RANDOM_BUF
>  
>  #if ! defined(XML_GE) || (1 - XML_GE - 1 == 2) || (XML_GE < 0) || (XML_GE > 1)
>  #  error XML_GE (for general entities) must be defined
> ```
> 
>     3. Issue
>        At this point you should be able to compile, but running it will lead you to [[desktop][drape] Black screen with new Qt 6.7 #7838](https://github.com/organicmaps/organicmaps/issues/7838), because of Qt 6.7.

The first workaround don't work for me. Do I need to replace all the file with the given content ?

**Comment by Ferenc-** [comment] 2024-05-02 07:27
> The first workaround don't work for me. Do I need to replace all the file with the given content ?
Yes.

**Comment by Arthur-GYT** [comment] 2024-05-02 07:30
> > The first workaround don't work for me. Do I need to replace all the file with the given content ?
> 
> Yes.

When I try to run `./tools/unix/build_omim.sh -r generator_tool`
![image](https://github.com/organicmaps/organicmaps/assets/116185937/2232c546-7c4c-428e-9aba-a23d83f872c6)

**Comment by Ferenc-** [comment] 2024-05-02 07:40
> > > The first workaround don't work for me. Do I need to replace all the file with the given content ?
> > 
> > 
> > Yes.
> 
> When I try to run `./tools/unix/build_omim.sh -r generator_tool` ![image](https://private-user-images.githubusercontent.com/116185937/327347868-2232c546-7c4c-428e-9aba-a23d83f872c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MzUzMDIsIm5iZiI6MTcxNDYzNTAwMiwicGF0aCI6Ii8xMTYxODU5MzcvMzI3MzQ3ODY4LTIyMzJjNTQ2LTdjNGMtNDI4ZS05YWJhLWEyM2Q4M2Y4NzJjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwNzMwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2NlNTMwOGExM2MyOGNlMTVkYjMxNDcyMGZiN2ViMTNkNmVlMDc5YTBlYWQzNjZiYWI2ZmE2NmMxODMzNzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ar6wKmMa-cmg0H8Zk2hsmhB96sduReqHxODy8BRGDNg)

That is not the first, but the second issue. Plus this (second) is fixed in https://github.com/organicmaps/organicmaps/pull/8057

**Comment by RedAuburn** [comment] 2024-05-02 12:33
Can confirm expat issue is fixed, tyvm Ferenc :)

(make sure to clean before building with new expat with `-c`)

**Comment by Arthur-GYT** [comment] 2024-05-02 14:57
> Can confirm expat issue is fixed, tyvm Ferenc :) (make sure to clean before building with new expat with `-c`) (also, black screen is still a thing)

Clear with `./tools/unix/build_omim.sh -c` ?

**Comment by RedAuburn** [comment] 2024-05-02 15:46
> Clear with `./tools/unix/build_omim.sh -c` ?

yup, or you can do it while building eg. `./tools/unix/build_omim.sh -cr desktop`

**Comment by Arthur-GYT** [comment] 2024-05-02 16:05
Same thing when I try to run this command with the workaround and recent changes on master...
![image](https://github.com/organicmaps/organicmaps/assets/116185937/aacaf1f5-eec4-4a2e-bb4a-e9e835a5c2c7)

**Comment by Arthur-GYT** [comment] 2024-05-02 16:17
For this, do I need to install QT creator or there is another way (`sudo ./tools/unix/build_omim.sh -r generator_tool`) ?
![image](https://github.com/organicmaps/organicmaps/assets/116185937/a441ced1-7503-456e-9663-c472c4d18df7)

**Comment by RedAuburn** [comment] 2024-05-30 22:45
harfbuzz was updated, and the temporary cmake file above no longer works:

use this now:

```cmake
add_library(harfbuzz::harfbuzz SHARED IMPORTED)
set_target_properties(harfbuzz::harfbuzz PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
  IMPORTED_LOCATION "/usr/lib64/libharfbuzz.so.0")

add_library(harfbuzz::icu SHARED IMPORTED)
set_target_properties(harfbuzz::icu PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
  INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
  IMPORTED_LOCATION "/usr/lib64/libharfbuzz-icu.so.0")

add_library(harfbuzz::subset SHARED IMPORTED)
set_target_properties(harfbuzz::subset PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
  INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
  IMPORTED_LOCATION "/usr/lib64/libharfbuzz-subset.so.0")

add_library(harfbuzz::gobject SHARED IMPORTED)
set_target_properties(harfbuzz::gobject PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/harfbuzz"
  INTERFACE_LINK_LIBRARIES "harfbuzz::harfbuzz"
  IMPORTED_LOCATION "/usr/lib64/libharfbuzz-gobject.so.0")
```

**Comment by RedAuburn** [comment] 2024-11-13 20:38
Build is working on Fedora 41 (Silverblue) so closing. Pls comment if it doesn't work for you & I'll reopen it

**Closed** 2024-11-13 20:38 UTC
Labels: Linux Desktop
