### ISSUE TITLE
Could you add monthly map data updates 

### ISSUE THREAD

**Issue by Asteliks** [organicmaps/organicmaps#2260] opened 2022-03-17 22:30 UTC
It would be great if we could have automated and app update independent map data updates. Currently new map data can be downloaded only ones the app itself is updated. In general what I ask for is for an independent automated process that would create map data updates at least ones a month, optimally ones a week. In places with poor connection a predictable date of the update would be great.

**Comment by pastk** [comment] 2022-03-18 17:05
Duplicate of #851

Its being worked on in #404 at the moment.

Also please check #835 for a broader overview.

**Closed** 2022-03-18 17:07 UTC
Labels: Downloader
