### ISSUE TITLE
One only backup file for all countries (points of interest)

### ISSUE THREAD

**Issue by serrq** [organicmaps/organicmaps#6865] opened 2023-12-17 15:31 UTC
I have at least 25 countries saved locally. 25 "import" actions must I doing?

![1000102027](https://github.com/organicmaps/organicmaps/assets/113377431/d2a4dbb8-7fcc-4796-8835-3cc08a44ed49)

**Comment by biodranik** [comment] 2023-12-18 00:18
Closing as a duplicate of #995

**Closed by biodranik** 2023-12-18 00:18 UTC
Labels: Duplicate

**Comment by biodranik** [comment] 2023-12-18 09:05
What else do you need to backup in Organic Maps in addition to Bookmarks?
