### ISSUE TITLE
The house numbers get out of place because they are too big

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#5293] opened 2023-06-09 10:32 UTC
**Describe the issue**
The house numbers are almost bigger than the buildings itself.

**Steps to reproduce**
1. Check houses
2. Zoom until you see the numbers
3. Experience the error

**Expected behavior**
We should make the required zoom level higher to show house numbers.

**Screenshots**
![Screenshot_2023-06-09-12-20-34-85_75d0290a7c00525acd83c0ab8700d64c.jpg](https://github.com/organicmaps/organicmaps/assets/76624594/a6a67b34-66cc-4b25-ab2d-e859cc11b89d)

We should look for something like this size
![Screenshot_2023-06-09-12-20-46-46_75d0290a7c00525acd83c0ab8700d64c.jpg](https://github.com/organicmaps/organicmaps/assets/76624594/0681a699-8889-4cf0-a9bc-24d0ffba272a)

It also happens when disabling make the text bigger on maps feature:
![Screenshot_2023-06-09-12-21-40-38_75d0290a7c00525acd83c0ab8700d64c.jpg](https://github.com/organicmaps/organicmaps/assets/76624594/b57eb831-d1eb-4c71-916d-d87d0cc4ae40)

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.06.04-13-FDroid
 - Device Model: OnePlus 8

**Additional context**
Please add any other context and important details/notes/comments about the problem here.

-

**Comment by Jean-BaptisteC** [comment] 2023-07-29 08:54
@pastk from which level we see house numbers ?

**Comment by pastk** [comment] 2023-07-29 12:10
Yes it looks ugly with small houses but we need house numbers shown early for cases of big apartment blocks..
I think its a duplicate of #1935

**Comment by d4f5409d** [comment] 2023-08-07 19:45
> Yes it looks ugly with small houses but we need house numbers shown early for cases of big apartment blocks..
> I think its a duplicate of #1935

We could develop something that detects of a house is tiny or not and calculates the size of it accordingly

**Closed** 2023-09-16 22:42 UTC

**Comment by d4f5409d** [comment] 2023-09-17 09:48
Thanks
