### ISSUE TITLE
Road not connected in OM but is connected on OSM

### ISSUE THREAD

**Issue by mamarguerat** [organicmaps/organicmaps#5842] opened 2023-08-27 14:37 UTC
**Describe the issue**
In a village in Switzerland (don’t know if anywhere else) a road is not connected as expected

**Steps to reproduce**
1. I found the bug in 46°45′15.44″N 06°56′20.04″E (https://osm.org/go/0CS9~k8V-?m=)
2. Couldn’t find it anywhere else

**Expected behavior**
As the road is connected in OSM with a small turnabout, it should be connected the same way in Organic Maps

**Screenshots**
![IMG_7029](https://github.com/organicmaps/organicmaps/assets/49449909/adcccd15-f832-44fc-b749-54240d16d4ae)
![IMG_7030](https://github.com/organicmaps/organicmaps/assets/49449909/3da8ffaf-87bb-445f-834c-793978614b64)

**System information:**
 - Operating system and its version: iOS 17.0 (21A5319a)
 - Organic Maps version : ⁦2023.08.18-7⁩
 - Device Model: iPhone 13 Pro Max

**Comment by mamarguerat** [comment] 2023-09-17 17:25
Similar behavior in 46°30′15.47″N 07°17′22.01″E (https://osm.org/go/0CYMr0UE-?m=). The main road (Dorfstrasse) seems to not be connected to the road in south-east (Grubenstrasse). The navigation in OM doesn’t accept turning from the main road to to « Grubenstrasse ».

**Comment by mamarguerat** [comment] 2023-09-22 16:30
Thanks for the quick fix.
I can confirm it has been fixed for the first comment of the issue, but the second one is still present.

**Comment by biodranik** [comment] 2023-09-22 20:03
Routing works for me in the latest September 20 data version. How did you test it?

**Comment by mamarguerat** [comment] 2023-09-25 07:41
@biodranik I use the latest iOS TestFlight beta, with maps updated.
When I try to navigate between two points (see screenshot below) the navigation goes by a long path instead of the shortest. And when we zoom on the map at the crossing, we can see an unconnected road. What is expected is that the navigation cross the train path to go directly to the destination
It’s at the crossing 46°30′15.47″N 07°17′21.98″E
![IMG_7163](https://github.com/organicmaps/organicmaps/assets/49449909/ef2004b7-a40a-41a4-a32e-6baa3f38e0ec)
![IMG_7164](https://github.com/organicmaps/organicmaps/assets/49449909/84d26bef-fc1b-4d4b-9d14-71c3374b478d)

**Comment by biodranik** [comment] 2023-09-25 08:16
The issue here is caused by motor_vehicle=no at this road: https://www.openstreetmap.org/way/54263532

If you're local, and it's incorrect mapping, then please remove that vehicle restriction from the OSM data and you'll get a correct route in the next version.

**Comment by biodranik** [comment] 2023-09-25 08:20
@pastk @vng is it possible to draw roads impassable by vehicle in a different style (maybe red?) at least in vehicle map style, so users can immediately see that something is not passable on the map?

**Comment by mamarguerat** [comment] 2023-09-25 08:31
Thank's for the answer. I didn't check this part of the road before creating this issue, my apologies.

**Comment by vng** [comment] 2023-09-25 11:29
@mamarguerat There are several more roads with motor_vehicle=no/destination tags
https://www.openstreetmap.org/way/463318951
https://www.openstreetmap.org/way/611882746
https://www.openstreetmap.org/way/54258086

_destination_ means that you can not pass through these roads, so it is also sensitive for the route. Please, check it out if you are familiar with that area.

@biodranik We don't store these tags in the classifier, used only to build road graph. Planning to store some separate access tags in future.

**Comment by mamarguerat** [comment] 2023-09-25 11:59
@vng Thank's. I will not modify them, because I'm not local to this area. I jusk knwo that I accessed the road mentioned by biodranik last week and it was allowed for everyone to go through this road. The others that you mentioned could probably use the *destination* tag, but I'll have to check on site. Thank's for your help.

**Comment by biodranik** [comment] 2023-09-30 06:00
@mamarguerat you can create an OSM note with a question if these roads have a proper access tag. If you drove it and didn't see any restriction signs, then the access info in OSM may likely be outdated (it happens often).

**Comment by biodranik** [comment] 2023-09-30 06:05
> We don't store these tags in a feature and don't define in the classifier, used only to build road graph. Planning to store some separate access tags in future.

Drawing some big icons on the areas when the route turns/avoids, like we do now for paid roads, may be a good idea.

**Comment by Jean-BaptisteC** [comment] 2024-03-25 18:04
Fixed in 2024.03.18-5-Google version

**Closed by Jean-BaptisteC** 2024-03-25 18:04 UTC
Labels: Map Data, Routing, Generator
