### ISSUE TITLE
[android] Improve navigationBarColor 

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3354] opened 2022-09-05 18:33 UTC
<img src="https://user-images.githubusercontent.com/87148630/188500327-c25a205a-cff8-4543-ae68-7030fa931abd.png" height="500"/><img src="https://user-images.githubusercontent.com/87148630/188500373-8df40750-fe67-4974-afe6-978289815044.png" height="500"/>

Navigation bar doesn't follow theme color
Just need to add new item on Android themes, like this `<item name="android:navigationBarColor">[add here colorBackground]</item>` (minSDKVersion is 21)

More information [here](https://medium.com/androiddevelopers/translucent-systembars-the-right-way-across-api-levels-and-themes-6d7ddda21396)

cc @arnaudvergnet

**Comment by arnaudvergnet** [comment] 2022-09-06 07:42
Is this issue still relevant after https://github.com/organicmaps/organicmaps/pull/2905? The bottom menu has been replaced by floating buttons.

**Comment by arnaudvergnet** [comment] 2022-09-06 16:12
Yes but as there is no bottom menu anymore, is it a problem that it stays black?

**Comment by Jean-BaptisteC** [comment] 2022-09-06 16:36
On main IHM, it's ok, but on search or settings we have difference between background color and navigation Bar Color.

**Comment by arnaudvergnet** [comment] 2022-09-09 15:06
Closing this issue as it is a duplicate of https://github.com/organicmaps/organicmaps/issues/3029

**Closed by arnaudvergnet** 2022-09-09 15:06 UTC
Labels: Android, UI
