### ISSUE TITLE
Sandy footways render as paved surfaces

### ISSUE THREAD

**Issue by fizwidget** [organicmaps/organicmaps#9368] opened 2024-09-26 22:33 UTC
**Describe the issue**
Footways tagged with `surface=sand` seem to render the wrong colour. 

**Steps to reproduce**
1. Navigate to [this way](https://www.openstreetmap.org/way/484287810) (or similar) in OM. 
2. Observe that it renders as a dotted white line rather than a brown one. 

**Expected behaviour**
A maybe I’ve got this wrong, but I expected brown? (Brown means unpaved these days?)

**Screenshots**
![IMG_6422](https://github.com/user-attachments/assets/e9932f46-b92e-4876-950c-d59fc5078461)

**System information:**
 - Operating system and its version: iOS 18.0
 - Organic Maps version: ⁦2024.09.08-2⁩
 - Device Model: iPhone XS Max

**Additional context**
I have the latest OM maps data and the way is years old, so I don’t think it’s an out-of-date data problem. 

Also noticed the way is tagged with `ford=yes` - maybe that’s confusing things? Though I’d also expect a ford to render as brown rather than white.

**Comment by vng** [comment] 2024-09-26 23:36
CC @pastk

**Comment by pastk** [comment] 2024-09-27 09:51
Yeap this is because of ford tagging.
So effectively its duplicate of
- https://github.com/organicmaps/organicmaps/issues/7877

**Closed** 2024-09-27 09:52 UTC
Labels: Duplicate, Styles, Generator
