### ISSUE TITLE
Don't render building=train_station as a train station itself

### ISSUE THREAD

**Issue by AlertSubject** [organicmaps/organicmaps#3497] opened 2022-09-27 16:05 UTC
It seems like these buildings are used as buildings related to train stations
https://www.openstreetmap.org/way/192232785
Usually only https://wiki.openstreetmap.org/wiki/Tag:railway%3Dstation should be rendered as a station 

![IMG_20220927_180406.jpg](https://user-images.githubusercontent.com/72819077/192577867-59773bf8-6f23-49c3-b381-da7e4484d6f6.jpg)
![Screenshot_2022-09-27-18-04-21-66_014aeb6b5e04ee7837dcdaecc5244511.jpg](https://user-images.githubusercontent.com/72819077/192577880-bc546375-8c6c-47e9-aa74-2863f9bd4fb2.jpg)

**Comment by biodranik** [comment] 2022-09-29 22:33
Duplicate of #3297

**Closed** 2022-10-14 07:06 UTC
