### ISSUE TITLE
[android] Empty navigation panel and start button

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8815] opened 2024-08-01 07:54 UTC
1. Select a remote destination
2. Route To
3. Do not download proposed maps (press Later)
4. Select and try to share any place on the map
5. Close the Place Page
6. Observe the screenshot. Starting navigation shows empty UI elements

The bottom panel should not be visible without an active route. 

![Screenshot_20240801_095110_Debug Organic Maps.jpg](https://github.com/user-attachments/assets/0bd215a4-2edc-4f42-a6c3-42fa70f8c2e0)

**Comment by Jean-BaptisteC** [comment] 2024-08-01 08:11
Duplicate of #3394

**Closed by Jean-BaptisteC** 2024-08-01 08:11 UTC
Labels: Good first issue, Android, Navigation, UI
