### ISSUE TITLE
Hide current street name while navigating in landscape mode

### ISSUE THREAD

**Issue by Raphael0** [organicmaps/organicmaps#5089] opened 2023-05-05 14:13 UTC
**Is your feature request related to a problem? Please describe.**
When navigating using a phone in landscape mode (especially on smaller phones and when turning off perspective view) the box showing the name of the current street at the top of the screen takes up a large amount of valuable screen space to see the road ahead. The remaining space is so small that it can make it difficult to use a phone for navigation in landscape mode.

Screenshot showing "space ahead" on an iPhone 12 mini in landscape mode:
<kbd>
  <img src="https://user-images.githubusercontent.com/23408445/236476952-56293455-16ff-498d-90d1-f91cddad93e6.PNG" width="500"/>
</kbd>

As a comparison, screenshot showing "space ahead" on an iPhone 12 mini in portrait mode:
<kbd>
  <img src="https://user-images.githubusercontent.com/23408445/236476816-62339803-8819-457d-98a4-57c3acd7552d.PNG" width="200"/>
</kbd>

**Describe the solution you would like**
Hide the box with the name of the street that one is currently located on when using a phone in landscape mode. In my view, this information is less valuable than seeing more of the road ahead.

**Describe alternatives you have considered**
- Reduce the height of the white box in which the street name is shown: this would likely make it difficult to read the street name and would not be enough to solve the problem 
- Reduce the amount of the map shown behind the user (display the position marker and map "further down" on the screen) when using landscape mode: this would likely not be enough to solve the problem
- Hide current street name while navigating in landscape mode _only when cycling_: I believe that this information is especially less valuable when on a bike. For the sake of simplicity I would however exclude this alternative.

**Additional context**
None

**Comment by biodranik** [comment] 2023-05-05 15:19
Thanks! Did you check all similar and related issues?

**Comment by Raphael0** [comment] 2023-05-05 15:24
Hi, as it turns out I did not for this issue: this has already been mentioned in #2177 Apologies for the double-posting and thanks for the great work! Should I close the issue?

**Comment by Jean-BaptisteC** [comment] 2023-12-29 19:06
I close this issue because it's a duplicate of #2177
The problem is present on IOS and Android, we need to find the right way to have the good size of street name in portrait and landscape

**Closed by Jean-BaptisteC** 2023-12-29 19:06 UTC
Labels: Duplicate
