### ISSUE TITLE
Display problem of Chinese

### ISSUE THREAD

**Issue by wanzh5** [organicmaps/organicmaps#7261] opened 2024-01-28 15:38 UTC
Some Chinese characters were incorrectly displayed as another character or garbled characters.
In the following screenshots, all the character "云"(U+4E91,yun) in the map were displayed as "垦"(U+57A6,ken) or garbled character. You can find this area on the map in Baiyun district(白**云**区), Guangzhou city(广州市), Guangdong province, PRC.
When the application is restarted, displayed character may change. It looks like it's random.
following are the screenshots.
"垦"
![Screenshot_20240128_230451_app organicmaps](https://github.com/organicmaps/organicmaps/assets/106989902/f25771e2-b7ce-4122-9797-1e1a0593ef21)

garbled characters
![Screenshot_20240128_231116_app organicmaps](https://github.com/organicmaps/organicmaps/assets/106989902/6a565721-80a8-4be3-858d-73d55abe8178)

"云"(correct display)
![Screenshot_20240128_232209_app organicmaps](https://github.com/organicmaps/organicmaps/assets/106989902/465159eb-4cd5-4c26-8719-899d9166d444)

**Comment by Jean-BaptisteC** [comment] 2024-01-28 15:56
Duplicate of #732 ?

**Comment by wanzh5** [comment] 2024-01-28 16:00
> Duplicate of #732 ?

Oh, yes. Sorry, I didn't see it then.

**Comment by Jean-BaptisteC** [comment] 2024-01-28 16:02
No problem :), we tried to reduce the number of issues and centralize information in same place.

**Closed by Jean-BaptisteC** 2024-01-28 16:02 UTC
Labels: Duplicate
