### ISSUE TITLE
Misses bookmark when tap on a building 

### ISSUE THREAD

**Issue by dmitrygribenchuk** [organicmaps/organicmaps#7215] opened 2024-01-20 13:51 UTC
**Describe the issue**
Hello. Have an issue with select a building with a bookmark. To select a building with a bookmark I need to tap exactly on a build number.

**Steps to reproduce**
1. Tap to building on number
2. Add to bookmark
3. Tap to building on another area (without a number)
4. See a missed bookmark 

**Screenshots**

https://github.com/organicmaps/organicmaps/assets/15670247/07711f48-2d6a-43be-9884-cb3b71b815ff

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2024.01.18-9-Google-beta
 - Device Model: Xiaomi Redmi Note 12 Pro 64GB

**Comment by Jean-BaptisteC** [comment] 2024-01-20 15:20
Duplicate of #4141

**Closed by Jean-BaptisteC** 2024-01-20 15:20 UTC
