### ISSUE TITLE
[android] Add language selection in app

### ISSUE THREAD

**Issue by SilmorSenedlen** [organicmaps/organicmaps#641] opened 2021-06-19 08:11 UTC
Good day
Is there any plans to add manual language selection in app?
It would be very nice to have this feature.

**Comment by biodranik** [comment] 2021-06-19 10:07
A duplicate of #391. What is your exact use case? What is wrong with the existing approach? (please leave comments in #391)

**Closed by biodranik** 2021-06-19 10:07 UTC
