### ISSUE TITLE
[ios] An educational hint that explains how to make routes without Point2Point tab

### ISSUE THREAD

**Issue by kirylkaveryn** [organicmaps/organicmaps#6256] opened 2023-10-07 15:09 UTC
Caused by: https://github.com/organicmaps/organicmaps/issues/5954 and https://github.com/organicmaps/organicmaps/pull/6220

Point to point tab from the bottom tabbar will be removed soon, so it needs to explain to users how to make routes easily.

There are some ways to do that:
1. popover view (it is more suitable than an alert or toast) with a short explanation text that hides when the user taps on the screen (may contain some additional controls, links, buttons, etc)
<img width="377" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/c9dd1c63-e927-4053-b7a9-ea9b139a7a54">

2. add red-dot badge to the "?" tab and the same educational text inside the "about" screen which hides after reading
<img width="356" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/91327ef9-a8d9-4a30-a3d7-e2791ab4e317">

Is there any other suggestions or comments on how this can be implemented?

**Comment by biodranik** [comment] 2023-10-07 17:37
Popup may be easier to implement, and it may point exactly at the place where button was located. But it's a bit intrusive to see it on startup after the upgrade. And many users may dismiss it without reading longer text. 

Showing a red dot on the question (help) button and then show a full screen dialog about the changes may be strategically more beneficial to add other important announcements, changes anf updates.

**Comment by kirylkaveryn** [comment] 2023-10-13 19:24
@biodranik I've made a default implementation of the self-sizing popup view (with max recommended width of 320 or less)
And dd some logic to handle popup opening only on current version changing (when the user updates an app from an older version to a newer one, skipping the first install)

But I have some questions:
1. now I use a delay of 1.5 sec, but it is probably too much is it OK to show it after the main screen appears?
2. should I disable all controls before Popuop appears? For example, the user can tap on the "?" tab and miss the popup. Probably using of smaller delay should solve this problem
3. Maybe some ideas for popup text content and how we are making localizations?

![Simulator Screen Recording - iPhone 14 Pro - 2023-10-13 at 16 07 08](https://github.com/organicmaps/organicmaps/assets/79797627/4a500475-ed34-4ba4-a832-3751d2f2d6fc)
![Simulator Screen Recording - iPhone 14 Pro - 2023-10-13 at 16 06 31](https://github.com/organicmaps/organicmaps/assets/79797627/aa401209-144c-4cc6-aba4-a4ffdaa4ddb6)

**Comment by biodranik** [comment] 2023-10-14 00:24
Good start, I like how it looks, but it is a bit intrusive. It would be great to compare it with an alternative approach.

Note that there is #1105, and there are new users too who won't know at all how to build a route. Ideas about the improvement:

1. Show that popup _once_ to anyone (new and existing users). New users also may not know about the routing and they also need to be educated.
2. Change text to explicitly mention the "Route To" button. That is optional because nobody will read longer texts. So we come to...
3. Highlight the "Route To" button in a way to attract user attention. It can be highlighted until user clicks on the button.
4. Show popup only after the current position is detected. That is required for Route To to work. Otherwise, user needs to press Route From first.
5. Fix the very annoying bug on the first launch (actually, it also reproduces on any launch): #794, because it will interfere with the popup display (a location not found dialog will be on top).

The cons of the popup are still there:
1. When to show it without irritating users?
2. When/how to close it? Users won't read longer texts.

Considering your questions, such a popup could be a good replacement for our existing "toast-like" notification in some other scenarios/cases.

An alternative approach could be less intrusive, and require fewer changes/conditions. For example:
1. Highlight a red dot on the "?" button for old and new users (a dot can be changed to a number later, when we make a button like on Android).
2. Show a full-screen (or half-screen?) hint view on the "?" tap. That hint view includes the necessary text and even may have an (animated?) image explaining something to a user. Starting with text-only now is good enough.
3. Use the standard Close button to close it manually.
4. Show the current About dialog after the hint view was closed.
5. The red dot disappears after user taps on "?" and sees the hint. Next tap on "?" doesn't show that hint anymore.

A possible text:

Tap or long-tap on the map, or select the search result to build a route.

**Comment by kirylkaveryn** [comment] 2023-10-18 23:00
@biodranik let's look at the beta implementation of the alternative approach with the red badge at "?" and the popover view that I've done:
1. use as a reference style of Apple's new native TipKit popovers (from ios17)
<img width="581" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/265e7bb7-9e48-4fd7-9398-bfdb2f4eb4ce">

2. add a small dimming of the background when the popup appears
3. add title and message so user can see the topic of hint
4. show hint only if tap on "?" when red badge is active OR when the user taps on some object and red dot disappears

(on the first gif red dot disappears after closing of the PlacePageVC and starts from beginning)
![Simulator Screen Recording - iPhone 14 Pro - 2023-10-19 at 02 44 07](https://github.com/organicmaps/organicmaps/assets/79797627/18e70320-40e3-4cb1-bac4-c0cc9c7dda63)
![Simulator Screen Recording - iPhone 14 Pro - 2023-10-19 at 02 43 21](https://github.com/organicmaps/organicmaps/assets/79797627/5449bde0-25f4-4cf1-afae-2055a60e15ab)

<img width="362" alt="SCR-20231019-dgpa" src="https://github.com/organicmaps/organicmaps/assets/79797627/23d36367-988b-442d-b2af-64a40e60a497">
<img width="357" alt="SCR-20231019-dgzg" src="https://github.com/organicmaps/organicmaps/assets/79797627/52ca017c-137b-4621-b8d4-a9cfd7adfa84">

**Comment by biodranik** [comment] 2023-10-19 00:41
1. The contextual hint/popup looks great, thanks!
2. Showing it on POI selection with the current text to solve the issue we were discussing (highlighting the "Route To" button to teach users how to build routes) is not a good idea (too complex/intrusive). We are already highlighting the Download button on your gif, Route To can be highlighted in the same (or similar) way. Maybe with a background, maybe with the same/different color. The highlight may be reset after the first use to avoid distraction. The same "learning" highlight may be used everywhere across the app to unobtrusively attract users' attention and teach some important use cases/functionality (maybe also showing an explanation popup if it's not clear). The cons is that changing colors of the same element is not the best UX and may confuse someone. So a persistent unobtrusive solution would be better.
3. Doing different things on the "?" tap is a bad UX (the first tap shows a popup, second tap shows dialog). Sorry, I wasn't clear in the previous comment that the "About" dialog also opens on pressing "?<sup>\*</sup>", and the "hint" is displayed on top of it (covering About, or partially covering About). Now, thinking more about it, I have a better idea. We already have a FAQ in the About. What if we open About and then open the FAQ inside the About if a user presses the "?<sup>\*</sup>"? There is already a "How to build a route" answer there, and many other useful answers that may not be discovered by many users. And we plan to improve the FAQ, of course! CC @strump

**Comment by kirylkaveryn** [comment] 2023-10-19 10:25
@biodranik thanks! I will try to make one more variant
But if talking about 3, I am not sure that moving the user to FAQ inside About is good because it works more like a "link to documentation" which is really boring :) rather than an educational hint. 

So it looks like there are three main directions that we can separate from each other:
1) attract the user to tap on smth
2) educate the user and tell about locka feature/changing
3) show all documentation with all application capabilities and features/changes

I really like the way Apple goes with TipKit and on the device it looks not really intruisive but very helpful. And it is important to point out that these tips will be shown only 1 time per app lifetime.

https://developer.apple.com/videos/play/wwdc2023/10229/

<img width="463" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/b6994971-13b6-49e1-a916-f8b48f77aad2">
<img width="472" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/d26e842f-cd54-4fa4-b80b-1d3fbf102a96">

Highlighting some icons is really more minimalistic and attracts the user to tap on the button but does not explain what will happen, and does not educate clearly (we just say: _"Hey! Tap on me and let's look what happened"_).
If we want just to attract users to smth it will be good, but if we want to educate and show some "hidden features" it is not very clear.
So we can implement all of these approaches:
- show the red badge on "?" and move to FAQ if there is some new info to read (but in that case, we need to scroll and move into the current section which has new info or mark some way)
- show popup tips on some buttons/features if we want to Educate users on how to use an app
- highlight some icons if we want to indicate about smth (process of downloading etc)

What do you think about it?

**Comment by biodranik** [comment] 2023-10-19 14:48
To clarify: guiding a user for the first time in the Apple-way is a great idea. It requires careful implementation though. Will these popups work on older iOS versions too?

FAQ is good too because it also explains other important moments and teaches the user where he can check it back again if help is needed. Scrolling it where necessary is a good idea too.

So far I wanted to focus on a very specific issue: teaching users how to build a route, taking into account that we removed the route button from the main screen.

**Comment by kirylkaveryn** [comment] 2023-10-24 19:19
@biodranik So, I've spent some days trying to find out how to change the tint for the PointTo icon (it was tough to debug custom tabbar behavior...)
And here is the result (I've added small fast animation of changing color from gray to blue with default duration to make a small accent on the icon):
![Simulator Screen Recording - iPhone 14 Pro - 2023-10-24 at 23 10 39](https://github.com/organicmaps/organicmaps/assets/79797627/66bdee5f-44d5-44e5-bf77-cf7f8fedb702)
<img width="348" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/0957dac0-2751-4287-82ba-a8f7be5d8eff">

**Comment by biodranik** [comment] 2023-10-26 22:47
I think we are already tinting the Download button in PP in the same way (tap/long-tap a non-downloaded area to see it). LGTM.

**Comment by kirylkaveryn** [comment] 2023-10-27 11:40
@biodranik I used the same approach as in the Download button, but I encountered an unexpected behavior when the tint color changed 4-5 times per appearing so... 
The main trick was that tint for MWMActionButton is overriding on runtime by KVC in storyboard...  and this is really not obvious to debug when color can change value from 3-4 places %)
<img width="1330" alt="image" src="https://github.com/organicmaps/organicmaps/assets/79797627/64287ad6-417c-4e0f-8aa6-c0d8b6a9983e">

Should I create PR with this tinting?

---
And one more question:
If there are red badge on the "?" tab should I show FAQ screen immediately? 
Or About -> FAQ (in that case user will see both screens and can go back with 2 taps. Also loading of 2 VCs at one time with a lot of info can impact performance and animations...)
Here I move "How to build a route" on the top of FAQ)
![Simulator Screen Recording - iPhone 14 Pro - 2023-10-27 at 15 36 37](https://github.com/organicmaps/organicmaps/assets/79797627/7b4d0760-8907-436e-9034-9b9e0d702ea8)

**Comment by biodranik** [comment] 2023-10-28 00:50
> Should I create PR with this tinting?

Yes please!

It would be great to avoid multiple unnecessary color changes. Is that runtime attribute approach good in general or would it be better to refactor it?

> If there are red badge on the "?" tab should I show FAQ screen immediately?

Yes. Note that a similar approach will be reused later for other (rare, but critically important) announcements in the app.

**Closed** 2023-11-05 14:00 UTC
Labels: iOS, UX
