### ISSUE TITLE
Display ZIP code / full adress

### ISSUE THREAD

**Issue by famo** [organicmaps/organicmaps#7649] opened 2024-03-21 09:41 UTC
**Is your feature request related to a problem? Please describe.**
I want to retrieve the full adress of a location - including the zip code. Which is currently not possible.

**Describe the ideal solution**
Show the Zip code next to the adress (Street and Housenumber)

Thanks.

**Comment by Jean-BaptisteC** [comment] 2024-03-21 10:26
Duplicate of #321

**Closed by Jean-BaptisteC** 2024-03-21 10:26 UTC
Labels: Enhancement
