### ISSUE TITLE
Opening hours 'Su,PH off' interpreted wrong

### ISSUE THREAD

**Issue by WebFreak001** [organicmaps/organicmaps#8365] opened 2024-06-02 08:37 UTC
**Describe the issue**

A POI has opening hours `Mo-Sa 07:30-21:00; Su,PH off`

OrganicMaps interprets this as sunday being 24/7 open

**Steps to reproduce**

Look at this node for example:

<om://04DPfGwo7K/Alnatura>

https://www.openstreetmap.org/node/10220616068

**Expected behaviour**

Sunday should be closed.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**System information:**
 - Android 14 / Lineage 21-20240506-NIGHTLY-lemonade
 - Organic Maps version: 2024.05.11-3-FDroid
 - Device Model: OnePlus 9

**Additional context**

The opening hours editor inside organicmaps reinterprets the opening hours and doesn't show the original, don't look at them in raw form in organicmaps nor ever edit them through that when they are special.

**Comment by biodranik** [comment] 2024-06-02 12:56
@Jean-BaptisteC can you please check if this issue has been fixed with this PR? https://github.com/organicmaps/organicmaps/pull/8371

**Comment by Jean-BaptisteC** [comment] 2024-06-02 13:17
Problem is not fixed

**Comment by xephos1one** [comment] 2024-06-02 13:33
Duplicate of #1575

**Comment by biodranik** [comment] 2024-06-02 13:39
Thanks! So it is not related to the recent change, and should be fixed separately.

**Comment by biodranik** [comment] 2024-06-02 20:59
Let's leave this case open too.

**Comment by patepelo** [comment] 2024-06-03 05:31
@biodranik 
> Let's leave this case open too.

But isn't it still a duplicate?

**Comment by WebFreak001** [comment] 2024-06-03 11:14
yeah duplicate

**Comment by biodranik** [comment] 2024-06-03 13:18
Su off and Su,PH off are two different test cases.

**Comment by matkoniecz** [comment] 2024-06-03 16:13
> Su off and Su,PH off are two different test cases.

Then maybe making this distinction also in issue title would make sense?

**Comment by xephos1one** [comment] 2024-06-03 16:35
Every single example in both issues including https://github.com/organicmaps/organicmaps/issues/1575 is "Su,PH off"
There is none that is just "Su off"

**Comment by biodranik** [comment] 2024-06-03 19:04
Good catch! Su off was mentioned in the PR description, so I was confused. Then this can be closed.

**Closed** 2024-06-03 19:22 UTC
Labels: Opening Hours
