### ISSUE TITLE
Do not open additional menu if button clicked

### ISSUE THREAD

**Issue by Asker229** [organicmaps/organicmaps#6501] opened 2023-11-06 21:08 UTC
Please, don’t open additional menu if [this](https://github.com/organicmaps/organicmaps/assets/150078786/a615155e-80d7-4ae6-953d-9a36e9b747ae) button clicked. 

I think your app should change this layers cyclically when it is clicked.

You have only 3 positions (Undeground, landscape and off) so it will be more convenient, specially in one-hand mode.

**Comment by Jean-BaptisteC** [comment] 2023-11-07 05:51
Duplicate of #6269
I'm not sure, your proposition is adapted if we have 10 layers for example, users lost more time with your solution

**Closed by Jean-BaptisteC** 2023-11-07 05:51 UTC
Labels: Enhancement
