### ISSUE TITLE
Align opening hours

### ISSUE THREAD

**Issue by AlertSubject** [organicmaps/organicmaps#1347] opened 2021-09-26 15:15 UTC
![Screenshot_20210926-170805.jpg](https://user-images.githubusercontent.com/72819077/134813669-3ebd06fd-2fee-4e06-996b-e7bdb14f5fd6.jpg)

Currently opening hours aren't properly aligned. The position depends on text length of the week days
Proper alignment would improve readability and just looks nicer in general

**Comment by j5k** [comment] 2021-09-26 21:50
Duplicate of #1136

**Comment by Kazing** [comment] 2022-01-14 11:22
Corrected by this PR : #1599 

Issue can be closed

**Closed** 2022-01-14 14:34 UTC
