### ISSUE TITLE
Turn lane guidance don't handle multi-direction lanes

### ISSUE THREAD

**Issue by ZippyGerbil** [organicmaps/organicmaps#6365] opened 2023-10-22 16:05 UTC
**Describe the issue**
Where a single lane has multiple turn direction options (left & right), this isn't rendered correctly

**Steps to reproduce**
e.g. https://www.openstreetmap.org/way/665132473 

The middle lane is for both left and right turns. It is rendered as being left turn only, but highlighted indicating it's a possible option - leading to confusion

![Screenshot_20231022-165959](https://github.com/organicmaps/organicmaps/assets/117409656/5dd57b61-edfb-49ef-8e09-37231c21131e)

**Expected behaviour**
An icon for this scenario with both a left and right turn arrow should be created and shown in these instances

**Comment by Jean-BaptisteC** [comment] 2023-10-22 16:27
Please check similar issues

**Comment by ZippyGerbil** [comment] 2023-10-22 16:29
I have done, none cover this case

**Comment by zyphlar** [comment] 2023-11-20 22:36
Duplicate of #4873

**Closed** 2024-03-25 20:46 UTC
Labels: Duplicate
