### ISSUE TITLE
Some types are not fully displayed

### ISSUE THREAD

**Issue by ivanbarsukov** [organicmaps/organicmaps#4052] opened 2022-12-09 11:26 UTC
When you open the card of POI for the first time, part of the name is hidden after half a second

![photo_2022-12-09_17-24-26](https://user-images.githubusercontent.com/14816075/206692211-1b860213-6325-4c29-b449-4d9af284a866.jpg)
![photo_2022-12-09_17-24-26 (2)](https://user-images.githubusercontent.com/14816075/206692216-5e8c11dc-5b74-4b59-8bfa-915ca1f9f7d1.jpg)
![photo_2022-12-09_15-53-04](https://user-images.githubusercontent.com/14816075/206692223-ea81ebb3-d052-4906-822c-93d37ee2bf14.jpg)
![photo_2022-12-09_15-53-05](https://user-images.githubusercontent.com/14816075/206692227-5205690c-680e-4f4e-8db2-a82f816c3114.jpg)

**Comment by arjundevasi** [comment] 2022-12-09 14:48
hey, can i help with this?

**Comment by endim8** [comment] 2022-12-09 22:55
> hey, can i help with this?

feel free to submit a PR, https://github.com/organicmaps/organicmaps/tree/master/docs has all you need to build :)

**Comment by endim8** [comment] 2022-12-09 23:03
what device are you using? I'm not able to reproduce this with OP 8Pro

**Comment by ivanbarsukov** [comment] 2022-12-15 05:17
> what device are you using? 
I took first two screenshots with Google Pixel 4A

**Comment by endim8** [comment] 2023-02-21 13:01
maybe fixed by https://github.com/organicmaps/organicmaps/pull/4174? @ivanbarsukov can you still reproduce this issue?

**Comment by Jean-BaptisteC** [comment] 2023-07-21 14:32
@ivanbarsukov can you retry with latest version ?

**Comment by ivanbarsukov** [comment] 2023-08-27 14:26
@Jean-BaptisteC looks like it's fixed

**Closed** 2023-08-27 14:42 UTC
Labels: Good first issue, Android, UI
