### ISSUE TITLE
School areas are not visible

### ISSUE THREAD

**Issue by AntonM030481** [organicmaps/organicmaps#2279] opened 2022-03-23 20:39 UTC
Only school icon is visible, not a whole area as before.

**Comment by biodranik** [comment] 2022-03-24 06:14
Coordinates to test?

**Comment by AntonM030481** [comment] 2022-03-24 06:32
Check out
Unknown Place
35.155317, 33.351621
https://omaps.app/0yxfvv53GB/Unknown_Place
om://0yxfvv53GB/Unknown_Place

**Comment by pastk** [comment] 2022-03-31 10:43
Duplicate of #1221

**Comment by pastk** [comment] 2022-04-10 09:46
Fixed in #2341

**Closed by pastk** 2022-04-10 09:46 UTC
Labels: Styles
