### ISSUE TITLE
Removing cuisine from restaurant data does not work

### ISSUE THREAD

**Issue by Explorer256** [organicmaps/organicmaps#2842] opened 2022-06-27 16:09 UTC
When I try to remove a kitchen from the data, I uncheck the list, save the changes, but the kitchen remains in the restaurant data

**Comment by Explorer256** [comment] 2022-06-27 21:29
> Уточните, пожалуйста, это iOS или Android.

Android

**Comment by arnaudvergnet** [comment] 2022-06-30 05:57
Duplicate of https://github.com/organicmaps/organicmaps/issues/1283

**Closed** 2022-07-02 16:40 UTC
Labels: Bug, Good first issue, Android, Editor
