### ISSUE TITLE
[android] Import bookmarks button doesn't allow to select a single file

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2240] opened 2022-03-10 19:47 UTC
The current implementation allows selecting only folders, not files. Some users have issues with that. They do not understand that the folder should be selected.

**Comment by shankarpriyank** [comment] 2022-03-15 05:59
How are we planning to resolve this?

**Comment by biodranik** [comment] 2022-03-15 07:25
Well, by allowing to select file(s) in addition to directories, and by properly importing only those files that were selected.

**Comment by Jean-BaptisteC** [comment] 2024-01-16 19:29
Duplicate of #5413

**Closed by Jean-BaptisteC** 2024-01-16 19:29 UTC
Labels: Duplicate, Good first issue, Android, Bookmarks and Tracks, UX
