### ISSUE TITLE
Provide an ability to import/export maps from/to file

### ISSUE THREAD

**Issue by Uiiki-waiiki** [organicmaps/organicmaps#5959] opened 2023-09-06 22:33 UTC
Hello!

Can you please provide ability to install map data directly from file? Also it will be very helpful if it will be an option to export installed map data as file.

It will be very helpful if it is no internet at all but a person that has no internet, but has downloaded maps to share them with other people who have app installed but no maps on it.

**Comment by biodranik** [comment] 2023-09-07 06:32
Isn't it a duplicate of https://github.com/organicmaps/organicmaps/issues/1801 ?

**Comment by RedAuburn** [comment] 2023-09-09 20:05
closing as duplicate, please comment in & follow 1801 :)

**Closed by RedAuburn** 2023-09-09 20:05 UTC
Labels: Enhancement
