### ISSUE TITLE
amenity=hunting_stand together with shelter=yes is shown as weather shelter

### ISSUE THREAD

**Issue by unixasket** [organicmaps/organicmaps#6493] opened 2023-11-06 16:09 UTC
Rendering problem with openstreetmap data:

If there is a amenity=hunting_stand with extra Tag shelter=yes (which means the hunting stand has a roof) it is shown as a weather shelter. For example Node id 8094587839. By the way: In germany it is forbidden to use hunting stands as weather shelter and some of them are locked.

**Comment by pastk** [comment] 2023-11-07 10:21
It happens because `amenity=hunting_stand` has a lower priority (2350) than an `amenity=shelter` (2850).

A broader issue is that its currently impossible to distinguish between `shelter=yes` (an attribute of some "main" tag) and `amenity=shelter` (a "main" tag).

**Comment by patepelo** [comment] 2023-11-07 10:51
This happens in too many cases with [something]=yes. We should consider in separating the "replaced_text" to use only for search. Hopefully soon.

**Comment by pastk** [comment] 2023-11-07 10:57
> This happens in too many cases with [something]=yes. We should consider in separating the "replaced_text" to use only for search. Hopefully soon.

Its being tracked here:
* https://github.com/organicmaps/organicmaps/issues/1312

Maybe more cases should be added there (shelter, drinking_water, bench...) https://github.com/organicmaps/organicmaps/issues/1312#issuecomment-1706344221

**Comment by pastk** [comment] 2023-11-08 14:03
Duplicate of #1132

**Comment by RedAuburn** [comment] 2023-11-21 16:24
closing as duplicate of https://github.com/organicmaps/organicmaps/issues/1132

**Closed by RedAuburn** 2023-11-21 16:24 UTC
Labels: Styles, Classificator
