### ISSUE TITLE
Auto Updates

### ISSUE THREAD

**Issue by KillerKingSolo** [organicmaps/organicmaps#8633] opened 2024-07-04 19:38 UTC
Regarding Organic Maps data sourcing from OpenStreetMap (OSM), I think you are currently obtain updates from planet.openstreetmap.org. I'd like to implementing an automated weekly update system to ensure the app's data remains as current as possible.

OpenStreetMap sees significant contributions within just a week's time. As an active contributor myself, I frequently add and refine data such as addresses, buildings, and various bug fixes in my local area. By syncing with the latest OSM data on a weekly basis, Organic Maps could dramatically improve its accuracy and usability.

For instance, newly added addresses would become searchable within the app much sooner. While there would still be a brief delay, weekly updates would substantially reduce the gap between real-world changes and their reflection in Organic Maps.

Implementing this automated update system would greatly enhance the user experience. It would make Organic Maps more reliable for navigation, especially in rapidly developing areas or regions with active OSM communities. This feature could also be a strong selling point, differentiating Organic Maps from competitors by emphasizing its commitment to up-to-date, community-driven data.

In summary, weekly automated updates from planet.openstreetmap.org would significantly boost Organic Maps accuracy, usability, and appeal to users who rely on the most current geographical data. This improvement aligns perfectly with Organic Maps ethos of providing a high-quality open-source mapping solution.

**Comment by Jean-BaptisteC** [comment] 2024-07-04 19:46
Duplicate of #835

**Closed by Jean-BaptisteC** 2024-07-04 19:46 UTC
Labels: Enhancement

**Comment by biodranik** [comment] 2024-07-04 20:09
@KillerKingSolo hourly, daily, and weekly updates are obtained now before generating the next data update. The issue here is not with the OSM data and how it is updated.
