### ISSUE TITLE
[desktop] Text contrast issue on map download in dark mode

### ISSUE THREAD

**Issue by Altonss** [organicmaps/organicmaps#4589] opened 2023-02-24 16:25 UTC
**Describe the issue**
Text contrast issue on map download. The text in white on a light background. This is related to dark mode...

**Steps to reproduce**
1. Set system-wide dark mode
2. Download map portion
3. See the text: "Downloading ..." in white on light background

**Expected behavior**
The text should be in a darker color for better contrast.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/66519591/221231488-8f7074f3-f164-49e8-bad3-538b77e96e15.png)

**System information:**
 - Organic Maps version: 2023.02.13-1-14e0f4be-dirty-Linux (Flatpak)

**Comment by Jean-BaptisteC** [comment] 2023-12-27 19:21
Duplicate of #1057

**Closed by Jean-BaptisteC** 2023-12-27 19:21 UTC
Labels: UX, UI, Linux Desktop
