### ISSUE TITLE
[editor] Feature names are not displayed correctly

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#442] opened 2021-05-22 12:50 UTC
There are several bugs when you press Edit button on a named feature, depending on phone languages and map region (iPhone with English and By,En,Ru,De preferred list):

1. Feature with default name tag does not display its name at all in some cases (e.g. in Switzerland there are 4 empty fields in Fr,De,En,By): http://omaps.app/w4B4pH2jux/Sorell_Hotel_Zürichberg
2. Feature with default name tag displays duplicated name for another language (name in Russian is displayed in English field): http://omaps.app/05Aasn9bX4/Троицкий_Собор
3. Buildings and some other objects with names do not allow name editing at all: http://omaps.app/05Aasn9rDk/Никольская_Надвратная_Церковь

**Comment by map-per** [comment] 2024-04-25 15:06
Closing, because issues 1. and 2. are fixed with #6257 and 3. is rather intended behaviour specified in `editor.config`

**Closed by map-per** 2024-04-25 15:06 UTC
Labels: Bug, Editor
