### ISSUE TITLE
Vatican City label covers everything else on the map

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#9633] opened 2024-11-10 14:35 UTC
The map becomes unusable in the area. @vng @pastk any ideas on an elegant fix? 

1 | 2 | 3
---|---|---
![grafik](https://github.com/user-attachments/assets/252292bb-04fb-4f35-99ca-50e3a71561a3)|![grafik](https://github.com/user-attachments/assets/96a24b5a-200f-4a05-99d9-cda4d4b62971)|![grafik](https://github.com/user-attachments/assets/1310deaa-34f6-4ef7-880f-9c0598eee7a4)

**Comment by RedAuburn** [comment] 2024-11-10 19:19
duplicate of https://github.com/organicmaps/organicmaps/issues/9608 😄

**Closed by RedAuburn** 2024-11-10 19:19 UTC
Labels: Styles
