### ISSUE TITLE
Pedestrian and bike routing on areas

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#5478] opened 2023-07-07 09:21 UTC
highway=footway (or highway=pedestrian) + area=yes are not routable now in OM and most other routers (likely except [OpenTripPlanner](https://wiki.openstreetmap.org/wiki/Key:area:highway#Differentiation_area:highway_vs._area=yes_on_a_highway)). OSM community draws linear ways to satisfy non-functional routes.

It would be great to implement it in Organic Maps. See https://wiki.openstreetmap.org/wiki/Top_Ten_Tasks#Pedestrian_and_bike_routing_on_areas for more details.

**Comment by pastk** [comment] 2024-01-05 07:37
Duplicate of #4147

**Closed by pastk** 2024-01-05 07:37 UTC
Labels: Routing, Cycling, Walk Navigation
