### ISSUE TITLE
[linux][GPS] Geoclue updates location only once.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#9513] opened 2024-10-13 12:26 UTC
From user:
"
 I installed this on Linux Debian using flatpak and are quite happy with the app.

There is one issue I have: When the app starts up it tries to get a position through geoclue, which works on my touchpad through the builtin GPS.

But the app only asks for one position and disconnects from geoclue, so the position is not updated when walking or driving.
"

**Comment by Ferenc-** [comment] 2024-10-13 16:54
Well, this slightly contradicts to some other users' and my personal experience.
But, do we happen to have further details for a possible reproduction? In particular about the HW and whether A-GNSS is in use? Because my first guess would be some timeout pertaining to that device particularly.

**Comment by vng** [comment] 2024-10-13 18:19
I sent the link on this issue to the user. Hope, he will rich us here.

**Comment by cwe-skov-dk** [comment] 2024-10-15 16:28
When I use geobug, I see updated position and timestamps every second. I need to set geobug to 'Exact' before getting any data, but thereafter updates are continuously coming in.

I have added syslog output from geoclue both during the geobug run and during the organicmaps run.

[geobug.log](https://github.com/user-attachments/files/17381701/geobug.log)
[organics.log](https://github.com/user-attachments/files/17381704/organics.log)

Is there any debug in organicmaps or Qt I could enable to figure out the difference?

**Comment by cwe-skov-dk** [comment] 2024-10-16 11:01
When I enable QT_LOGGING_RULES="qt.positioning.geoclue2.debug=true", I see these messages during startup:

```
qt.positioning.geoclue2: Client path is: "/org/freedesktop/GeoClue2/Client/3"
qt.positioning.geoclue2: Client successfully started
qt.positioning.geoclue2: Old location object path: "/"
qt.positioning.geoclue2: New location object path: "/org/freedesktop/GeoClue2/Client/3/Location/0"
qt.positioning.geoclue2: New position: QGeoPositionInfo(QDateTime(2024-10-16 12:58:57.000 CEST Qt::LocalTime), QGeoCoordinate(56.7626365, 9.0991897667), Direction=2.79e+07, GroundSpeed=0, HorizontalAccuracy=-1)
qt.positioning.geoclue2: Client successfully stopped
```

It seems the positioning service is closed after the first position.

How can I enable the debug messages in organicmaps/platform/qt_location_service.cpp?

**Comment by Ferenc-** [comment] 2024-10-20 13:52
> How can I enable the debug messages in organicmaps/platform/qt_location_service.cpp?

OM needs to be re-build from source with Debug. If it is causing you troubles, then I can provide you a debug build.

What I think could be higher priority at this point is some more info on the following points:

1. What is the the exact ublox device that you are using?
2. In your [organics.log](https://github.com/user-attachments/files/17381704/organics.log) I see this:
```` gpspiper.py[2632]: BrokenPipeError: [Errno 32] Broken pipe ````
Hence the question: What is `gpspiper.py` ? It doesn't appear to be part of the `gpsd-clients` nor the `gpsd` debian package, and I couldn't find any reference of it. Would be nice to ensure, that it's not the cause of the gpspipe service deactivation, that we see right after that message.
3. When you start up OM, and you get your first position fix, could you please show me the exect parametrisation of the `gpspipe` process?

**Comment by Ferenc-** [comment] 2024-10-20 14:09
Further question:
Has any of the previous flatpak versions worked for you?
I mean the geoclue permission fix is relatively new, and that's where we introduced the functionality of only requestiong a single location first before requesting the continuous updates. In previous versions we went pretty much straight for the continuous updates. A wild idea is that old logic could help your use case. Or if you happen to have timeouts with the old logic, then perhaps some higher timeout with the old logic would work for you.

**Comment by cwe-skov-dk** [comment] 2024-10-21 06:42
The modem is a Sierra Wireless, Incorporated model: EM7305 firmware revision: SWI9X15C_05.05

gpspiper.py is a wrapper around gpspipe to filter out the json sent by gpsd initially during connecting, it is written as such:

```
process = Popen(['gpspipe', '-r'], stdin=PIPE, stdout=PIPE, env=env)

try:
        while process.returncode is None:
                process.poll()
                line = process.stdout.readline()

                if len(line) == 0:
                        # Drop empty lines
                        continue

                if line.startswith(b'$GPRMC'):
                        stdout.buffer.write(line.replace(b'\r', b''))
                        stdout.flush()

except BrokenPipeError as e:
        print(f'BrokenPipeError: {e}', file=stderr)
        stdout.close()
        pass

except Exception as e:
        print(f'Exception: {e}', file=stderr)
        pass
```
So the broken pipe message means that stdout was closed by geoclue.

A debug version of OM would be greatly appreciated, because this Touchpad I try to get this to work on is not configured as a build machine and has limited disk resources. I have not tried a previous version from flatpak, how would I install and use this?

**Comment by Ferenc-** [comment] 2024-10-21 14:24
> The modem is a Sierra Wireless, Incorporated model: EM7305 firmware revision: SWI9X15C_05.05

Oh, OK, I thought only u-blox was sold with the tablet. And it's even better, since this module could be aquired cheap if needed.

> gpspiper.py is a wrapper around gpspipe

I see, it's still a mistery why I couldn't find this earlier, but now we have it.

> A debug version of OM would be greatly appreciated

[Here](https://send.tresorit.com/a#OWdvR3vnGmhbFUos45KukQ) you go.
(Depending on your installation you might want to omit or use the `--user` switch)

1. `tar -xf x86_64-debug-repo.tar.bz2`
2. `flatpak --user install --assumeyes ./x86_64-debug-repo app.organicmaps.desktop`
3. `flatpak --user run app.organicmaps.desktop//master`
4. `flatpak --user uninstall --assumeyes app.organicmaps.desktop//master`

>  have not tried a previous version from flatpak, how would I install and use this?

1. Look for previous commit hashes: `flatpak --user remote-info --log flathub app.organicmaps.desktop`
2. Downgrade to previous commit for example: `flatpak --user update --assumeyes --commit=df7c59aeb0096c4ef8872bb929cc87b399fbb0228d4663b6477e1136dc71a583 app.organicmaps.desktop`

**Comment by cwe-skov-dk** [comment] 2024-10-21 15:35
I believe I found the error:

bool m_clientIsActive is never initialized during construction of QtLocationService. In case there is a value in memory, the service will never be started after first position.

In debug, I see the log message at line 111 in platform/qt_location_service.cpp, but no further debug messages after that.

Could you build a test version where m_clientIsActive is initialized to false in the constructor?

**Comment by Ferenc-** [comment] 2024-10-21 20:09
> Could you build a test version where m_clientIsActive is initialized to false in the constructor?

Sure, [here it is](https://send.tresorit.com/a#hwiHOksnDnzmEyNEl6Y-mQ), the patch is the following:
````diff
index 448c67cb74..eefe4f8b0f 100644
--- a/platform/qt_location_service.cpp
+++ b/platform/qt_location_service.cpp
@@ -58,7 +58,7 @@ static location::TLocationSource qStringToTLocationSource(QString const & source
 }
 
 
-QtLocationService::QtLocationService(location::LocationObserver & observer, std::string const & sourceName) : LocationService(observer)
+QtLocationService::QtLocationService(location::LocationObserver & observer, std::string const & sourceName) : LocationService(observer), m_clientIsActive(false)
 {
   QVariantMap params;
   params["desktopId"] = "app.organicmaps.desktop";
````

**Comment by cwe-skov-dk** [comment] 2024-10-22 14:35
Thank you very much. This works like expected, I now get continuous position updates. You should probably integrate this into master.

**Comment by vng** [comment] 2024-10-22 16:01
Better ```bool m_clientIsActive = false;``` in hpp file.

**Closed** 2024-10-23 19:13 UTC
Labels: GPS, Linux Phone, Linux Desktop
