### ISSUE TITLE
Map search not working properly

### ISSUE THREAD

**Issue by hialvaro** [organicmaps/organicmaps#1560] opened 2021-11-15 08:54 UTC
I want to report a series of errors that have been present in Organic Maps since first versions, and also appear on other apps such as OsmAnd. This issues are breaking usability and many users do not choose these apps because of this. I tried to convince many friends to use this app, but all of them end switching back to Google or others because of the following errors related with the search.

Searching on the map does not show correct results. It usually shows unrelated results or they are not sorted by the correct order of relevance (i.e a town should be shown before a street). I will use Barcelona as example citiy; In Barcelona there is a street called Napols:

<img width="250" src="https://i.imgur.com/80kAGps.jpg"></img>

However, searching this street does not show the street itself. The first result is a small path that has no relation with the big street shown above. All the other results have no relevance, it is taking the word "Carrer" as a search term, but it is the name used for "Street" in Catalan. So all the streets in the map are named "Carrer X". It shows one result that matches the name but it is on a completely different location and is not related to the position I am on the map (Barcelona City).

<img width="250" src="https://i.imgur.com/an8BaGS.jpg"></img>

Another example with a big famous street. Balmes is a known and big street of Bacelona:
<img width="250" src="https://i.imgur.com/Oub7Fs1.jpg"></img>

If I search "Balmes" on the search bar, nothing related is shown. The first result is a path, small and non-related (see next picture). All the other results only contain the word Balmes, but are not related to the street itself.
<img width="250" src="https://i.imgur.com/5FGg0mA.jpg"></img>
<img width="250" src="https://i.imgur.com/70cdJuO.jpg"></img>

Also, searching a street and a building number never finds the location. I have not been able to find a street and building number on the search box.

Another issue is when using Open Location Codes (OLC) does not work from the search box. I can find the OLC for a place on the map and copy it to share with others, but I can't use the codes:

I go to Google Maps and search for a famous place, la Sagrada Familia Cathedral:
<img width="250" src="https://i.imgur.com/FY8f1XG.jpg"></img>

Then I copy the OLC code shown and I paste it ont he search bar on Organic Maps:
<img width="250" src="https://i.imgur.com/oQXUpyd.jpg"></img>

Nothing is found.

**Comment by hialvaro** [comment] 2021-11-15 08:59
I think that solving issues with search on the map should be a top priority as otherwise it breaks a lot of usability.

**Comment by biodranik** [comment] 2021-11-15 10:23
Thank you very much for the detailed feedback, it will help us a lot for testing after fixing the search ranking.

1. Regarding non-found streets. They are actually found if you search on the map and drag it so the streets are in the viewport. Search engine finds them. The problem is now with the ranking code which displays garbage on top of the results list, instead of a full match. We will fix it. See related #1462, #1376, #1151, #1120, #1017. Note, that now there is a bug #1147 when not all found features are displayed in the viewport (that's why results appear and disappear when you drag the map). We need to fix it.
2. Regarding not found buildings: do they have their numbers in OSM and in OM? I've just checked in Barcelona, it works properly. The problem could be that you need to either "look at" the city where you are searching the street + number, or add a city name into the search query, or be physically somewhere nearby. Otherwise our current implementation won't guess the city and can't find the address. It can be improved though.
3. See #457 regarding non-working OLC. We just need to properly fix the search code.

**Comment by pastk** [comment] 2021-11-24 09:30
Also search related https://github.com/organicmaps/organicmaps/issues/608

**Comment by vng** [comment] 2022-07-27 16:53
Looks like search finds first suitable street (_small_ footway) and then ignores _big_ secondary.
The same issue https://github.com/organicmaps/organicmaps/issues/1028

**Comment by vng** [comment] 2022-07-27 19:53
One more example in Barcelona. Finds many unrelated stuff, but not what we need.
addr = "Carrer de les Planes 43, Sabadell, Barcelona"
street = "Carrer de les Planes, Sabadell"

**Closed** 2022-08-03 14:38 UTC
Labels: Bug, Search
