### ISSUE TITLE
As a London tube user, I want to be able to find tube exits.

### ISSUE THREAD

**Issue by bjohas** [organicmaps/organicmaps#4933] opened 2023-04-07 08:55 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I leave the tube (at platform level) and it's hard to locate the right street-level exit.

**Describe the solution you would like**

The solution has multiple components, only one related to organic maps.

**Background:** We're launching a campaign to collect London tube exit information and how to get there from the platform. The exits are typically already in OSM, but often they aren't labeled correctly/fully. For example, an exit might be labeled Aldgate East. However, the label (visible in the station) for that exit is "Exit 1, High Street (south side), Leman Street, Conference forum". To get there, you need to know to follow signs for "High Street, Leman Street". Tagging in OSM can be contentious, and we are exploring the following https://www.openstreetmap.org/node/5109686507, with a small modification to the name "Aldgate East, Exit 1", placing the following text into description:en: "Exit 1, High Street (south side), Leman Street, Conference forum. To reach this exit from the platforms, follow signs to: High Street, Leman Street."

**Request/question to OrganicMaps:** Is "description:en" rendered? If not, should the information be placed into another tag that is rendered? Or, could the "description:en" be rendered?

**Describe alternatives you have considered**

We'll make the information available outside OpenStreetMap as well, but integration into a maps-based platform would be helpful.

**Comment by biodranik** [comment] 2023-04-07 12:21
Please see #1953

**Comment by RedAuburn** [comment] 2023-10-03 17:24
gonna close as functionally a duplicate of #1953, but worth noting that subway_entrance is already rendered :)

https://github.com/organicmaps/organicmaps/issues/3419 might also be interesting

**Closed by RedAuburn** 2023-10-03 17:24 UTC
Labels: Enhancement
