### ISSUE TITLE
Distance of calculated route truncated

### ISSUE THREAD

**Issue by smartyw** [organicmaps/organicmaps#5593] opened 2023-07-23 17:09 UTC
**Describe the issue**
On using Route To or Route From, often the calculated distance is truncated as it does not fit in the available space. 

**Steps to reproduce**
1. Use Route To to calculate a route more than 10 miles/km long. Observe the distance reported.

**Expected behavior**

**Screenshots**
![Screenshot_2023-07-23-19-03-57-18_75d0290a7c00525acd83c0ab8700d64c~2](https://github.com/organicmaps/organicmaps/assets/1387793/c4b321d8-36b2-469f-ada6-b0dbdfb3a736)

**System information:**
 - Android 13
 - 2023.06.04-13-Google
 - OnePlus 9 Pro

**Additional context**
Please add any other context and important details/notes/comments about the problem here.

**Comment by Jean-BaptisteC** [comment] 2023-07-23 17:50
Duplicate of #3320

**Comment by smartyw** [comment] 2023-07-23 18:00
In my case, the value is truncated to a one digit value. But yes, it's otherwise a duplicate :-)

**Comment by Jean-BaptisteC** [comment] 2023-11-08 16:22
Fixed in latest version

**Closed by Jean-BaptisteC** 2023-11-08 16:22 UTC
Labels: Duplicate, UI, Route Planning
