### ISSUE TITLE
Fix malayalam rendering

### ISSUE THREAD

**Issue by muzirian** [organicmaps/organicmaps#516] opened 2021-06-06 20:47 UTC
Malayalam rendering looks broken on organic maps now, please help fix.
Adding location and screenshots for reference 
https://www.openstreetmap.org/#map=14/10.2833/76.2284
![photo5325944431737680942](https://user-images.githubusercontent.com/71079779/120939413-98760e80-c735-11eb-9abc-3a3d002e7366.jpg)
![Screenshot 2021-06-07 at 1 56 47 AM](https://user-images.githubusercontent.com/71079779/120939421-a166e000-c735-11eb-86da-22f298ac7e3b.jpg)

For font we can use https://www.google.com/get/noto/#sans-mlym
or anjali/manjari/meera/suruma from https://smc.org.in/fonts/

Thanks

**Comment by biodranik** [comment] 2021-06-07 07:42
This bug looks similar to drawing of الحلّة in Arabic. The issue is with some diacritics, which are not properly "merged" into one symbol rendered by our FreeType library. The proper solution will require some hard work with integrating something like HarfBuzz and probably rewriting glyph cache.

We really appreciate the help from the community :)

**Comment by biodranik** [comment] 2021-07-13 13:25
Looks like it's related to #460

**Closed** 2024-06-29 09:32 UTC
Labels: Bug, Drape, Fonts
