### ISSUE TITLE
Add online mode as in Maps.me (WITHOUT any type of external crap!)

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#6731] opened 2023-11-29 18:39 UTC
Please,
Add online mode as in Maps.me (WITHOUT any type of external crap!)

Why? Your maps data updates TOO rarely, so in some situations it will be really useful, if object just added

![IMG_1326](https://github.com/organicmaps/organicmaps/assets/152433147/8ce748bc-316b-4c61-b012-3fdd4308c1a3)

**Comment by pastk** [comment] 2023-11-30 08:57
Related to (or even a duplicate of)
- https://github.com/organicmaps/organicmaps/issues/835

**Comment by d4f5409d** [comment] 2023-12-09 21:30
> What exactly does this button do? Does it allow to see OpenStreetMap.org map data updates more frequently?

I don't know either

I think it supposed to achieve something similar OsmAnd live features do, but in my case the button seemingly have done nothing at all

**Comment by biodranik** [comment] 2023-12-10 04:51
1. Even if that button did something in old MapsMe versions, it simply duplicated the "Allow mobile internet" setting.
2. There is no such button in MapsMe now.
3. There are separate issues for more frequent map data updates.
4. Implementing online maps is a complex and completely different topic.

**Closed by biodranik** 2023-12-10 04:51 UTC
Labels: Duplicate, Enhancement, Downloader
