### ISSUE TITLE
[ios] Add Dark and Tinted Icons for iOS18

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#9329] opened 2024-09-20 20:38 UTC
![image](https://github.com/user-attachments/assets/1e97677f-37b9-4881-a4c0-a6a40928b794)

https://medium.com/@GuillemBruix/design-your-dark-and-tinted-versions-of-your-app-icon-for-ios-18-827444a31851

**Comment by RedAuburn** [comment] 2024-09-20 20:40
Duplicate of https://github.com/organicmaps/organicmaps/issues/9312 :grin:

**Closed by RedAuburn** 2024-09-20 20:40 UTC
Labels: Enhancement, iOS
