### ISSUE TITLE
Sometimes it is possible to start navigation on an empty route

### ISSUE THREAD

**Issue by deevroman** [organicmaps/organicmaps#4170] opened 2022-12-30 17:04 UTC
For example:

1. Select the destination that is in an unloaded area.
2. Cancel the offer to upload data from an unloaded region.
3. Open, for example, My Bookmarks.
4. Close it.
5. It becomes possible to start navigation on an empty route.

https://user-images.githubusercontent.com/25708359/210094918-0306f99f-f4be-4bd2-9818-9c64095c5495.mp4

2022.12.18-12-FDroid

**Comment by Jean-BaptisteC** [comment] 2022-12-30 17:44
Duplicate of #3394

**Closed** 2023-11-13 16:57 UTC
Labels: Duplicate, Routing
