### ISSUE TITLE
The no-gps-signal dialog disrespects dark mode

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#4667] opened 2023-03-01 20:53 UTC
**Describe the issue**
Please write here a clear and concise description of what the bug/issue is about.

**Steps to reproduce**
1. Turn on dark mode
2. Turn off gps
3. Click on the locate me button
4. Experience the issue

**Expected behavior**
It should be dark instead of white.

**Screenshots**
![Screenshot_2023-03-01-21-28-01-47_75d0290a7c00525acd83c0ab8700d64c.jpg](https://user-images.githubusercontent.com/76624594/222262261-3bb75a17-0ce1-4903-841c-3a7e19c0a3c7.jpg)

**System information:**
 OnePlus 8, Android 13, v2022.02.13-11F-Droid

**Additional context**
-

**Comment by Jean-BaptisteC** [comment] 2023-03-01 21:24
All alertdialog have wrong color in dark mode
Duplicate of #4562
I work on fix
Please check others issues before create new issue :)

**Comment by d4f5409d** [comment] 2023-03-02 06:08
> All alertdialog have wrong color in dark mode
> Duplicate of #4562
> I work on fix
> Please check others issues before create new issue :)

I checked! I promise 😐

**Closed** 2023-03-02 06:07 UTC
