### ISSUE TITLE
Routing for cars does not consider motor_vehicle:conditional

### ISSUE THREAD

**Issue by angoca** [organicmaps/organicmaps#5280] opened 2023-06-06 02:21 UTC
**Describe the issue**
The error appears in Bogota, Colombia, where we have the ciclovia, where traffic cars are restricted in some streets to only allow bikes on Sundays.

This is mapped the following tags:

 * motor_vehicle:conditional
 * bicycle:conditional
 * foot:conditional

The complete description of this https://wiki.openstreetmap.org/wiki/Colombia/Project-Ciclov%C3%ADas

**Steps to reproduce**
1. Starting point https://www.openstreetmap.org/#map=19/4.70915/-74.06130
2. Destination point https://www.openstreetmap.org/#map=19/4.70001/-74.07174
3. Request a route for a car on Sunday morning between 7 am and 2 pm.
4. It should not propose "Avenida Carrera 55" because cars are prohibited during this time.

![WhatsApp Image 2023-05-29 at 6 52 30 PM](https://github.com/organicmaps/organicmaps/assets/294317/5fa573a4-3adc-4c2d-91ae-25a26fd9e74a)

**Expected behavior**
Other routing applications propose different routes during this time.

**Comment by Jean-BaptisteC** [comment] 2024-02-07 21:25
Similar of #5066

**Comment by pastk** [comment] 2024-11-25 18:44
- Duplicate of https://github.com/organicmaps/organicmaps/issues/3731

Please track it there!

**Closed** 2024-11-25 18:48 UTC
Labels: Duplicate, Routing
