### ISSUE TITLE
Public Transport layer shows bezier curves instead of following the track between stations

### ISSUE THREAD

**Issue by nighto** [organicmaps/organicmaps#9774] opened 2024-11-28 13:03 UTC
⚠ Have you searched for similar, already existing issues? Yes, couldn't find anything.

**Describe the issue**
The public transport layer shows a simplified path between two stations, instead of following the actual track as defined on OSM. That on itself in general cases shouldn't be a problem, but is problematic when we have two different services on the same railway (being one regular, stopping in all stations, and another express, skipping some stations), or when we have parallel railways with a similar setting.

**Steps to reproduce**
1. Search for "Riachuelo, Rio de Janeiro"
2. Activate public transport layer
3. Zoom out a bit, you'll see a red line passing on that station and two other parallel lines (blue and green) passing on the south
4. In reality, the three lines should be parallel.

Here's a screenshot:
![image](https://github.com/user-attachments/assets/e40e8399-4717-495b-9ffe-e7da9a5201a9)

In comparison, the same area on Apple Maps:
![image](https://github.com/user-attachments/assets/aabfeb25-d9d5-44cc-bd16-0dc5e0f5b1b4)

Another example:
1. Search for "Guarulhos, São Paulo"
2. Activate public transport layer
3. Zoom in a bit, you'll see two green lines going to the airport, one that branches from the dark blue line and one that diverges all the way from "Brás" station
4. In reality, the two green lines should be parallel all the time.

Screenshot from Organic Maps:
![image](https://github.com/user-attachments/assets/71b52d3b-d27b-49a6-9f7b-5cb8f2886df5)

And the same area on Apple Maps:
![image](https://github.com/user-attachments/assets/3fec2b02-606f-48d1-9ca2-0b0f325eb779)

**Expected behaviour**
I expect that the tracks wouldn't drift off so much, making it seem parallel instead of appearing to be lines on different routes.

**Screenshots**
(Added above)

**System information:**
 - Operating system and its version: iOS 18.1.1
 - Organic Maps version: 2024.11.27-11
 - Device Model: iPhone 14 Pro

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by AndrewShkrob** [comment] 2024-11-28 17:29
What's going on with that UI? 😁

![image](https://github.com/user-attachments/assets/cb7883fb-b8bc-48da-bf01-2ce94c40e04c)

**Comment by matkoniecz** [comment] 2024-11-29 12:30
> And the same area on Apple Maps:

I strongly suspect it is also simplified

> but is problematic when we have two different services on the same railway (being one regular, stopping in all stations, and another express, skipping some stations), or when we have parallel railways with a similar setting.

why it is problematic?

**Comment by pastk** [comment] 2024-11-29 20:10
- duplicate of https://github.com/organicmaps/organicmaps/issues/7067

Please track it there!

**Closed by pastk** 2024-11-29 20:10 UTC
Labels: Duplicate, Metro

**Comment by nighto** [comment] 2024-11-30 10:44
Oh, hadn't find that issue, thanks @pastk
