### ISSUE TITLE
Wikipedia links with question mark

### ISSUE THREAD

**Issue by alnzrv** [organicmaps/organicmaps#8322] opened 2024-05-28 21:29 UTC
After I click on a "Wikipedia" link for an article with character '?' in the name I get a redirect to the incorrect URL:
https://en.wikipedia.org/wiki/Are_Years_What?_(for_Marianne_Moore)
instead of
https://en.wikipedia.org/wiki/Are_Years_What%3F_(for_Marianne_Moore)

Example:
https://www.openstreetmap.org/node/945504911
38.8889251, -77.0234446

You may find more examples with the following overpass-turbo request:
`nwr["wikipedia"~"\\?"]({{bbox}});out;
`

**Screenshots**

![image](https://github.com/organicmaps/organicmaps/assets/7187657/526b99af-a78a-406c-b877-b5a26a1d7af4)
![image](https://github.com/organicmaps/organicmaps/assets/7187657/5f70b629-329f-44c4-a9db-5a69c51af4a3)

**System information:**
2024.05.11-3-Google

**Comment by biodranik** [comment] 2024-05-28 22:13
Thanks for the detailed issue! It was easy to reproduce and fix it )

**Comment by Jean-BaptisteC** [comment] 2024-05-29 04:38
I'm not sure the problem is in Organic Maps, we have the same error when I try to open link from Osm website.

**Comment by krozhdestvenski** [comment] 2024-05-29 20:20
The problem in symbol "?", which separates the request parameters section in the url. 
As result we have this:
Url: https://en.wikipedia.org/wiki/Are_Years_What?_(for_Marianne_Moore)
host: en.wikipedia.org
path: /wiki/Are_Years_What
paremeters: _(for_Marianne_Moore)

If the url in this case cannot contain parameters, then the problem can be fixed by replacing "?" to "%3F" before opening the link.
If theoretically the parameters can be used, it is necessary to fix on the map provider side.

**Closed** 2024-05-30 05:49 UTC
Labels: Wikipedia
