### ISSUE TITLE
Map download path resets occasionally. 

### ISSUE THREAD

**Issue by ShimonHoranek** [organicmaps/organicmaps#869] opened 2021-07-16 19:25 UTC
Once in a while the path to downloaded maps changes from my internal storage to my sd card. This is even more annoying, if you consider that the app doesn't start without downloading the basic world map.

**Comment by biodranik** [comment] 2021-07-17 21:19
Does it reset AFTER moving maps to SD-card?

**Comment by ShimonHoranek** [comment] 2021-07-17 21:29
I have all the maps downloaded to internal storage and have never moved them.

**Comment by biodranik** [comment] 2021-07-18 08:26
How do you see that the path changes? Does the app start asking about downloading the world map?

**Comment by ShimonHoranek** [comment] 2021-07-18 14:10
Yes, it starts with asking to download the basic world map. If i download it and then navigate to settings, i can see that the path changed

**Comment by bcag2** [comment] 2021-12-07 12:44
Similar issue on fresh install (December 3th).
After install path was on SD card (what I want), I launch some downloads, then I should left my home, so some downloads couldn't finished.  
After restart, it switch to internal memory and require me to downloading the world map, and I can't switch back to SD card
![image](https://user-images.githubusercontent.com/5690299/145030953-f966c4ea-b55c-46c2-aa70-d33757fc6208.png), radio button seems greyed !

**Comment by biodranik** [comment] 2021-12-08 06:48
@bcag2 looks like there is not enough space on SD card. But anyway it's a bug. Can you please enable logs in app settings and share them with us (Report a bug)?

@rtsisyk @vng does our current implementation fall back to the internal memory if there is not enough space on SD? It is wrong behavior. Obviously, if user stores maps on SD, it should be used anyway, even if it's not enough space there.

**Comment by bcag2** [comment] 2021-12-08 21:06
> @bcag2 looks like there is not enough space on SD card. But anyway it's a bug. Can you please enable logs in app settings and share them with us (Report a bug)?
There was less than 100Mo. I remove downloaded files and there are now about 300Mo, then I can now selected SD card !
I am going to see to remove some files (I have got my photos galleries also on sd)
I enable logs, how retrieve log files, if it is useful for you?
Thanks a lot for this nice app with OSM (I am OSM contributor)

**Comment by bcag2** [comment] 2021-12-13 18:06
I made some tests by adding maps, but I also upgraded to version 2021.12.01-4-FDroid (thanks to make it available on F-Droid), and I don't reproduce (I have got only less than 30Mb free on sd card). It stays on SD card and I can always switch.

**Comment by pastk** [comment] 2022-07-03 19:34
Fixed in #2641

**Closed by pastk** 2022-07-03 19:34 UTC
Labels: Bug, Android
