### ISSUE TITLE
add recorded voice prompts

### ISSUE THREAD

**Issue by Stomatic** [organicmaps/organicmaps#1875] opened 2022-01-17 17:51 UTC
Hi,
I have degoogled phone (so with no tts installed); is it possible to add recorded voice prompts like OsmAnd?
This will be super usefull to many other user like me.

**Comment by arnaudvergnet** [comment] 2022-01-17 18:32
This would be very nice! I also have a phone without Google but with a shitty tts, and it is near impossible to understand it.

**Comment by biodranik** [comment] 2022-01-18 11:25
It's a duplicate of #607

See also #584 and #923 

Isn't it easier to install some other TTS service, with a better voice quality? I thought that there are plenty of them available in Fdroid, for example.

**Comment by Stomatic** [comment] 2022-01-18 11:48
Many TTS don't support Italian and many other languages, which can be supported by recorded voice prompts, besides being much more understandable while driving.
OsmAnd voice recordings are proprietary license (https://github.com/osmandapp/OsmAnd/blob/master/LICENSE) so you probably can't use them; but it can generate from TTS (as they did).

**Comment by RedAuburn** [comment] 2024-01-19 13:49
closing as duplicate of https://github.com/organicmaps/organicmaps/issues/1875

**Closed by RedAuburn** 2024-01-19 13:49 UTC
Labels: TTS
