### ISSUE TITLE
[android] missing details in PlacePageView when MapObject is a bookmark

### ISSUE THREAD

**Issue by czeidler** [organicmaps/organicmaps#3679] opened 2022-10-19 19:18 UTC
Having a landmark selected shows details such as a wikipedia description in the PlacePageView page. However, after bookmarking (saving) the landmark, the description is not displayed anymore. This is quite annoying when you want to get some more details about your saved locations.

As far as I can see the main issue is that a Bookmark MapObject has no description or other metadata set. (Probably because it is not saved in the bookmark?)

I guess the Bookmark MapObject should use the map data if a field is not overwritten in the saved bookmark?

@yunikkk there is a TODO comment on the MapObject class that seems to be related?

```
// TODO(yunikkk): Refactor. Displayed information is different from edited information, and it's better to
// separate them. Simple getters from jni place_page::Info and osm::EditableFeature should be enough.
```

**Comment by arnaudvergnet** [comment] 2022-10-19 20:19
Duplicate of https://github.com/organicmaps/organicmaps/issues/2825

Thanks for looking into it, I don't have time to work on it but maybe another contributor can (why not you ;) ).

**Comment by arnaudvergnet** [comment] 2023-02-18 22:20
Fixed by https://github.com/organicmaps/organicmaps/pull/4174

**Closed by arnaudvergnet** 2023-02-18 22:20 UTC
Labels: Duplicate, Good first issue, Android, UI
