### ISSUE TITLE
Screen turns off during navigation

### ISSUE THREAD

**Issue by sed-i** [organicmaps/organicmaps#7098] opened 2024-01-07 06:49 UTC
**Describe the issue**
- When I start navigation, the screen turns off after a while.
- After I manually turn the screen back on back on a couple of times, it then stays on during navigation.

It seems like this only happens when I use [Tower Collector](https://f-droid.org/en/packages/info.zamojski.soft.towercollector/) at the same time.

**Steps to reproduce**
1. Start navigation in organic maps.
2. Open Tower Collector and start recording.
3. Switch back to organic maps.

**Expected behaviour**
I expect the screen not to turn of while organic maps is at the foreground.

**System information:**
 - Operating system and its version: GrapheneOS [2024010400](https://grapheneos.org/releases#2024010400).
 - Organic Maps version: 2023.12.20-4-FDroid

**Comment by Jean-BaptisteC** [comment] 2024-01-07 07:16
Duplicate of #6921
Problem is fixed in the next version

**Closed by Jean-BaptisteC** 2024-01-07 07:16 UTC
