### ISSUE TITLE
Flatpak "org.kde.Platform/x86_64/6.6" dependency outdated

### ISSUE THREAD

**Issue by dCo3lh0** [organicmaps/organicmaps#9638] opened 2024-11-11 16:20 UTC
**Describe the issue**
I've tried updating organic maps and it gives me error and almost crashes the process of updating flatpak's.

**Steps to reproduce**
1. Update Flatpak's
2. Warning error saying that "org.kde.Platform/x86_64/6.6" is outdated but is still required by organic maps

**Expected behavior**
Update Flatpak's without errors

**Screenshots**
Don't think there is a need for a screenshot for a warning saying org.kde.Platform/x86_64/6.6 is deprecated.

**System information:**
 - Operating system and its version: Tuxedo OS 4 (Based on Ubuntu 24.04 and Debian 12)
 - Organic Maps version: 2024.10.23-2
 - Computer Configuration: AMD Ryzen 5700G, Nvidia RTX 2060, 64GB DDR4 RAM, 2 SSD's M.2 PCI-E 3.0, 2 HD 2TB and 8TB 
 
 
**Additional context**
Current version is "org.kde.Platform/x86_64/6.8".

**Comment by dCo3lh0** [comment] 2024-11-11 17:29
I'm sorry i didn't knew there was a issue with the 6.7 version.

**Comment by Ferenc-** [comment] 2024-11-12 17:58
Duplicate of https://github.com/flathub/app.organicmaps.desktop/issues/83

**Closed by Ferenc-** 2024-11-12 17:58 UTC
