### ISSUE TITLE
Improve address formating

### ISSUE THREAD

**Issue by muralito** [organicmaps/organicmaps#6426] opened 2023-10-31 00:33 UTC
**Describe the issue**
In Uruguay, the displayed addresses are not formatted to the standard use here.

**Steps to reproduce**
It happens in the text displayed in the search results, and in the text displayed in the POI info.

**Expected behaviour**
In Uruguay the address text should be formatted as:
The most simple format, for displaying in the list:
addr:street addr:housenumber, addr:city, addr:country (note no "," between street and housenumber) (if there is nohousenumber=yes it should diplay "S/N")

if there is info about the suburb or neighbourhood it is optional, and if there is screen space it could be displayed as
 addr:street addr:housenumber, addr:suburb/neighbourhood, addr:city, addr:country

When the address data is displayed in the POI data, it could be diplayed in multiline, like a postal address.
addr:street addr:housenumber (also addr:housename if it is tagged)
addr:suburb/neighbourhood
addr:postalcode addr:city 
addr:country

**System information:**
 - Operating system and its version: The issue appears in several Android versions
 - Organic Maps version: 2023.09.22-27-FDroid
 - Device Model: The issue appears in several phones and tablets.

**Comment by RedAuburn** [comment] 2023-11-13 18:20
Duplicate of #616

**Closed by RedAuburn** 2023-11-13 18:20 UTC
Labels: UI, Address
