### ISSUE TITLE
[android] Need wrap_content or something for the Track's info.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#9726] opened 2024-11-23 18:44 UTC
![image](https://github.com/user-attachments/assets/5c81e690-ac74-41d2-b764-84ac46b412d6)

**Comment by Shubham-344** [comment] 2024-12-16 13:47
I want to work on this issue, can you please assign this to me?

**Comment by RedAuburn** [comment] 2024-12-16 15:34
> I want to work on this issue, can you please assign this to me?

Please read https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md#code-contributions

**Comment by Mynkara08** [comment] 2024-12-26 04:38
I have a doubt whether this issue is caused by the language or the font size of the device , When I increased the font size on my phone ,the issue became appreant.

**Comment by pastk** [comment] 2024-12-26 07:15
Its most likely font size.

**Comment by Mynkara08** [comment] 2024-12-26 07:34
Thank you for clarifying. I’m already working on resolving the issue and testing it with different font sizes to ensure it functions seamlessly across all settings.

**Closed** 2024-12-30 10:42 UTC
Labels: Good first issue, Android, UI
