### ISSUE TITLE
Multiple optional routes to the same destination

### ISSUE THREAD

**Issue by sharmaachintya08** [organicmaps/organicmaps#5037] opened 2023-04-25 08:17 UTC
**INTRODUCTION**
If we search for a path from Destination A to Destination B, the map should show all the possible paths from Destination A to Destination B, if any other paths are available

**STEPS TO REPRODUCE**
1. we put **from**  destination and **to** destination
2. map highlights multiple paths
3. Any path can be selected, depending upon the user.

**EXAMPLE**
This feature is very much showed or used in google maps, where we have more than 1 paths to reach from destination A to destination B and the map shows the potential shortest path.

![khanna(2)](https://user-images.githubusercontent.com/80171589/234222709-4ccc65ff-e801-4cad-b5a3-2eb3d948947f.png)

**Comment by Altonss** [comment] 2023-04-25 10:31
This is a duplicate of other issues like https://github.com/organicmaps/organicmaps/issues/1183 https://github.com/organicmaps/organicmaps/issues/3975, and a first support work started here https://github.com/organicmaps/organicmaps/pull/3447.

**Closed** 2023-04-25 11:19 UTC
Labels: Enhancement
