### ISSUE TITLE
Ask for confirmation before aborting navigation

### ISSUE THREAD

**Issue by jofrev** [organicmaps/organicmaps#836] opened 2021-07-10 20:58 UTC
At the moment, pressing back immediately aborts an ongoing navigation.

I think it might be good to ask the user for confirmation first in case they pressed back accidentily. It's not that much of a hassle having to confirm compared to setting up the entire route again possibly having to add several waypoints, too.

I understand this might not be an issue for most people, but it happens quite often to me during bike trips to be honest, and I'd appreciate it a lot if you considered implementing this.
If you don't have time for this, but approve of it nevertheless, I'd be happy to do it myself.

I considered opening a discussion, too, but felt like this wasn't really worth it since its such a small feature request.

For what its worth, I'm currently running version `2021.07.04-16-g05a2bc44cf-FDroid` on Android 11.

**Comment by biodranik** [comment] 2021-07-11 07:23
You mean a hardware or software "system" back button, right? Now user in most cases:
1) Selects a point on the map
2) Presses the "route to" button
3) Starts Navigation.

I see more value if the "back" button will return to the previous state instead of asking for confirmation. In my example, it's returning to the state (2), where the destination point is selected.

However, for complex routes with intermediate points, additionally asking for a confirmation makes sense. What do you think?

**Comment by jofrev** [comment] 2021-07-11 21:14
> You mean a hardware or software "system" back button, right?

Yup, that's what I was talking about.

> I see more value if the "back" button will return to the previous state instead of asking for confirmation. In my example, it's returning to the state (2), where the destination point is selected.
> 
> However, for complex routes with intermediate points, additionally asking for a confirmation makes sense. What do you think?

In my opinion aborting an ongoing navigation should always be a two-step process (pressing "back" then confirming the abortion in a dialog for example) even if the route is not a complex one. But that might be just a personal preference.

However, I like your idea of returning to step (2) as you described it above. This would make editing the route quite easy.  
The dialog asking the user if they really want to abort (assuming you decide to implement it) could also provide a third option "edit destination" or something like this, which would return the app to step (2).  
The option "yes" would abort the navigation and return to normal state (pre (1) if you will).  
The last option "no" would simply close the dialog and continue the ongoing navigation.  
This would be kind of a combination of our two ideas.  What's your opinion on this?

**Comment by biodranik** [comment] 2021-07-11 21:51
It sounds a bit complicated for users. If you're actively navigating by car or by bike, it's not an easy task to read the dialog title and then choose one option out of three.

If you cancel a route normally (without a back button), it's already a several clicks process: open the bottom panel and press stop. If I understood your use-case correctly, you try to resolve an accidental click on it. But that fix ideally should not make the life of others (who use the back button consciously) harder.

**Comment by jofrev** [comment] 2021-07-12 12:34
> It sounds a bit complicated for users. If you're actively navigating by car or by bike, it's not an easy task to read the dialog title and then choose one option out of three.

You're right, it probably is.

> If you cancel a route normally (without a back button), it's already a several clicks process: open the bottom panel and press stop.

In this case the confirmation dialog is not necessary, I totally agree. It's quite clear what happens next, if "stop" is pressed, and it shouldn't happen on accident, too.

> If I understood your use-case correctly, you try to resolve an accidental click on it. But that fix ideally should not make the life of others (who use the back button consciously) harder.

Yeah, ideally it shouldn't, but the possible negative impact of accidentally aborting a navigation seems to be greater than the additional effort the dialog would inflict on those consciously doing it, at least for me (personally).

It's a matter of personal preference in the end. There are valid points for both approaches, I guess, and I understand your argument. I even share it.

**Comment by arnaudvergnet** [comment] 2022-01-24 21:55
Completely agree with @jofrev. A simple confirm dialog is needed when clicking the Android system back button. While on a long trip, I accidentally clicked on it and it removed the route. As the trip was several hours long with intermediate points, it took about 30 seconds to add back the stops and calculate the route.

A simple dialog would not make the life of users more difficult. Cancelling a route is not an action users do all the time, and users are used to having to confirm destructive actions (like deleting files on the computer, closing without saving, etc).

As the stop button on the panel is not easily accessible, I agree that it may not be useful to add it here. But the Android back button can be very easily activated by accident.

**Comment by biodranik** [comment] 2022-01-25 09:17
We can try this fix and see what users will say. If many people complain, we'll revert it.

**Comment by pastk** [comment] 2022-01-26 15:36
There is a related annoying thing - if a user selects a POI or a point on the map while in navigation mode then a bottom sheet expands and gets populated with the info - as usual. Now if a user presses the android back button then an expected behavior is to de-select the selected point (this is how it works in non-navigation mode). But contrary to this the android back button exits navigation mode completely.
It would be great if this behavior could be fixed altogether.

**Comment by arnaudvergnet** [comment] 2022-02-01 08:27
After some discussion in https://github.com/organicmaps/organicmaps/pull/1941#issuecomment-1022181046, we decided it would be better to make the user go back to the route planning screen on Android back button press to follow other apps behavior.

**Comment by arnaudvergnet** [comment] 2022-02-01 08:28
Duplicate of https://github.com/organicmaps/organicmaps/issues/1403

**Closed** 2022-02-01 19:47 UTC
Labels: Good first issue, Android, UX, Navigation
