### ISSUE TITLE
Can not delete imported GPX track

### ISSUE THREAD

**Issue by pressing-buttons** [organicmaps/organicmaps#7376] opened 2024-02-12 21:00 UTC
I have imported a folder of GPX tracks into OrganicMaps. After a while I did no longer need them, and I tried to delete them. This worked for all but one. Tapping on the track name in the list/folder only shows the map with the track. A long tap inside the favorite list doesn't do anything. 

I am aware that this isn't very detailed, but if there is any "debug option" that will reveal more information I please let me know and I will provide it. I also have looked in the filesystem, but couldn't find an obvious place where the track is stored, so I could delete it from there. 

**System information:**
 - Android 8.1
 - Organic Maps version: 2023.09.27-FDroid
 - bq Aquaris X Pro

**Comment by biodranik** [comment] 2024-02-13 01:17
This is a duplicate of https://github.com/organicmaps/organicmaps/issues/1531

**Closed by biodranik** 2024-02-13 01:17 UTC
