### ISSUE TITLE
Localized Wikipedia articles 

### ISSUE THREAD

**Issue by Nekothegamer** [organicmaps/organicmaps#5906] opened 2023-09-02 10:13 UTC
Wikipedia articles in POIs are awesome, but there's something about it that bothers me.

All articles are displayed in english by default, it would be much better if they'd display in the system/app language instead, and if there's a Wikipedia article about a POI that isn't in the language set on the system/app THEN it defaults to english

it's much better this way than all articles being in english, it brings a better experience as a whole

**Comment by Jean-BaptisteC** [comment] 2024-03-25 18:24
Duplicate of #3599

**Closed by Jean-BaptisteC** 2024-03-25 18:24 UTC
Labels: Enhancement
