### ISSUE TITLE
Assign a color to each list

### ISSUE THREAD

**Issue by 12425** [organicmaps/organicmaps#8338] opened 2024-05-30 17:01 UTC
⚠ Have you searched for similar, already existing issues?
Yes.

**Is your feature request related to a problem? Please describe.**
I'd like to assign a color to all bookmarks in the same list, so that I don't have to change the color for each new bookmark.

**Describe the ideal solution**
When we edit or create a list, we can select a color for the list.
* Bookmarks and Tracks -> click 3-dot button of a list -> Edit, and
* Bookmarks and Tracks -> Create a new list

And then, when we add a new bookmark and choose the list, it will automatically have the assigned color.

**Describe alternatives you have considered**
Or, when we open a list, provide a way to assign a color to all the bookmarks in this list

**Additional context**
Use case:
I'd like all parks shown as green, all libraries shown as blue in the map.
Today I add park1, I have to choose green.
Tomorrow I add lib2, I have to choose blue.
After that I add park3, I have to choose green again. Every time I have to choose the color if the category is different from last time.

**Comment by pastk** [comment] 2024-06-03 17:08
A duplicate of https://github.com/organicmaps/organicmaps/issues/1805, please track it there

**Comment by Friptick** [comment] 2024-06-22 16:40
@pastk Instead of letting this dupe attract votes and comments and so dilute the issue's importance, why not delete it? You could paste the content above into #1805 as an addendum.

**Comment by pastk** [comment] 2024-06-22 19:32
Right.

**Closed by pastk** 2024-06-22 19:32 UTC
Labels: Duplicate
