### ISSUE TITLE
A better icon for public transport shelter

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2319] opened 2022-03-30 11:11 UTC
The current `amenity=shelter` icon doesn't look good in urban setting:

![Screenshot_1648637264](https://user-images.githubusercontent.com/18434508/160821293-90bcab6e-a32b-4745-9117-e2a93fc4fe81.png)

So either make it more generic or use a different icon for `amenity=shelter shelter_type=public_transport`, e.g. https://www.openstreetmap.org/way/946557410

**Comment by Vanshitgupta9717** [comment] 2022-04-07 06:36
I Wanna Work On This Issue

**Comment by Vanshitgupta9717** [comment] 2022-04-07 06:37
I want to work on this issue

**Comment by Vanshitgupta9717** [comment] 2022-04-07 06:39
I want to work on this issue. Please assign this to me and since I am new to this repo so please guide me through it.

**Comment by pastk** [comment] 2022-04-07 08:58
> I want to work on this issue. Please assign this to me and since I am new to this repo so please guide me through it.

Changing/adding icons is described in [the docs](https://github.com/organicmaps/organicmaps/blob/master/docs/STYLES.md#how-to-add-a-new-icon).

Once you have a new icon please post it here so that we can review. Thanks!

**Comment by endim8** [comment] 2022-04-10 13:51
Agreed that public_transport needs a new icon, here is an overview of most-used tags
<img width="350" alt="Screenshot 2022-04-10 at 03 51 40" src="https://user-images.githubusercontent.com/26939824/162599403-9aa6e373-0fb7-49ef-8fb9-ff05b8cfb6ae.png">

Maybe the cross-beam should be removed too?
<img width="485" alt="Screenshot 2022-04-10 at 14 51 16" src="https://user-images.githubusercontent.com/26939824/162621439-458aeeb3-b109-485a-a902-605894b4c5ab.png">

**Comment by endim8** [comment] 2022-06-07 00:25
<img width="64" src="https://user-images.githubusercontent.com/26939824/172269978-dfa7e33b-61a5-43c4-9e11-ecc42cf32ba8.svg"><img width="64" src="https://user-images.githubusercontent.com/26939824/172269979-0c7fdd70-15fb-4b40-94c0-5e497518babe.svg"><img width="64" src="https://user-images.githubusercontent.com/26939824/172269980-770eb800-b71e-4e6e-aaed-a6645acdc9d9.svg"><img width="64" src="https://user-images.githubusercontent.com/26939824/172270413-002639f7-bb3b-4a09-bcd0-126d7d7f5e81.svg"><img width="64" src="https://user-images.githubusercontent.com/26939824/172270481-98d2762c-439c-422d-9821-ff9371c04ee6.svg">

tried a few different icons, not really happy with any of them but maybe they'll spark some ideas :)

**Comment by biodranik** [comment] 2022-11-24 16:23
The second one looks interesting, maybe make the bench smaller, like 1/4 of the current width. And likely the roof too.

**Comment by kevinvaddoriya1** [comment] 2023-04-06 12:35
i'm working on this issue

**Comment by muralito** [comment] 2023-04-23 22:33
The icon set seems good as you can represent all the choices for public_transport=platform, but in most maps this are represented with a just a bus (or train) symbol.

what about simplify the symbol, at least for most of the zooms, using just bus symbol (when there is no shelter info or shelter=no) and almost the same symbol but with a "chevron" covering the bus when there is a shelter. The additional info can be displayed when you select the platform, or when the zoom is large enough.

**Comment by biodranik** [comment] 2023-04-24 06:42
It's an interesting idea, would be great to see how it looks on the map in the light and dark style.

**Comment by vng** [comment] 2023-09-01 13:38
@RedAuburn @dvdmrtnz @j13m126 
Hey folks! Seems like it is stuck now, but it will make the look and feel much better by just adding the new amenity-shelter-public_transport type, right?

**Comment by RedAuburn** [comment] 2023-09-01 17:55
> @RedAuburn @dvdmrtnz @j13m126 Hey folks! Seems like it is stuck now, but it will make the look and feel much better by just adding the new amenity-shelter-public_transport type, right?

definitely :) it'd be good to include the type in generator even if we haven't decided on an icon yet

on that note, how about something like this:
![image](https://github.com/organicmaps/organicmaps/assets/26939824/fc5728a6-0775-44b5-ab3f-e21fd701c2c5)

**Comment by vng** [comment] 2023-09-01 18:12
Sorry, bit it looks like gallows :)

**Comment by RedAuburn** [comment] 2023-09-01 20:17
> Sorry, bit it looks like gallows :)

😂 good point

**Comment by patepelo** [comment] 2023-10-13 12:08
Is the same icon for train platform needed? 


![image](https://github.com/organicmaps/organicmaps/assets/23003127/bd5e1602-b207-44d9-b9f2-64ef633802f1)

**Comment by euf** [comment] 2024-03-09 10:25
I'd second Roentgen icons, they are good indeed

**Comment by biodranik** [comment] 2024-03-09 10:41
Did someone already try to see how these icons look on low and high resolution devices?

**Comment by pastk** [comment] 2024-04-12 08:46
@organicmaps/styles anyone wants to prepare an icon svg for inclusion into the app?
Based on https://github.com/organicmaps/organicmaps/issues/2319#issuecomment-1326614675
We need just an `-m` size

**Comment by patepelo** [comment] 2024-04-15 09:55
> @organicmaps/styles anyone wants to prepare an icon svg for inclusion into the app? Based on [#2319 (comment)](https://github.com/organicmaps/organicmaps/issues/2319#issuecomment-1326614675) We need just an `-m` size

WDYT about the first variant here, is from Roentgen but with the shield removed for simplicity.

![imagen](https://github.com/organicmaps/organicmaps/assets/23003127/c62d3b87-e691-4f86-9383-cb505cfd9a77)

Or this second one (as-is):
![imagen](https://github.com/organicmaps/organicmaps/assets/23003127/0524d194-b1f6-44f0-a593-c0f0efcab00f)

**Comment by pastk** [comment] 2024-04-15 10:02
I think its better to show a bench rather than a floor.
But actually both options are fine if they look recognizable when small.

**Comment by patepelo** [comment] 2024-04-15 12:12
Please vote thumps up or down for this one:
![322435476-c62d3b87-e691-4f86-9383-cb505cfd9a77](https://github.com/organicmaps/organicmaps/assets/23003127/b92fa991-79ee-42f3-8dec-8215b7fe98aa)
Or post alternative propositions.

**Comment by Misalf-git** [comment] 2024-04-15 13:42
> ![322435476-c62d3b87-e691-4f86-9383-cb505cfd9a77](https://github.com/organicmaps/organicmaps/assets/23003127/b92fa991-79ee-42f3-8dec-8215b7fe98aa)

My imagination somehow takes a wrong turn with a shelter seen from the side - I see a weird shopping trolley. Maybe I'd get it when rendered on the map near a road though.

An alternative of the current shelter might be easier to recognize?
![shelter_m+pt.png](https://github.com/organicmaps/organicmaps/assets/72605561/7514d65a-652a-47b9-8c47-0ed5bc547363)

**Comment by biodranik** [comment] 2024-04-15 20:31
Maybe something like this (but with a flat roof)?

![image](https://github.com/organicmaps/organicmaps/assets/170263/0eff3021-a86c-4df6-88ad-b1319ced3e8e)

**Comment by patepelo** [comment] 2024-04-20 22:45
![image](https://github.com/organicmaps/organicmaps/assets/23003127/725e42a3-0511-4e37-adfe-fd14116d5119)

**Comment by patepelo** [comment] 2024-04-20 22:46
![image](https://github.com/organicmaps/organicmaps/assets/23003127/1e8df1e5-9972-4dfc-b9e2-90cacf477673)

**Comment by muralito** [comment] 2024-04-21 00:17
IMHO these icons do not reflect the main function of the element they represent, taking a public transport bus.

I would prefer something that reflect both facts, (bus or train)+shelter.
Some examples are in this site http://icons.a3.kyiv.ua/ (Transport icons of Kyiv, CC-BY-SA-4.0 license, can be adapted and forked) , like the bus shelter https://github.com/agentyzmin/icons.a3.kyiv.ua/blob/master/src/svg/Bus%20Station.svg

**Comment by biodranik** [comment] 2024-04-21 12:48
What about tram or trolley bus stops? Or cable car stops? Ideally, they all should be distinguished. Or one universal icon for each type of transport should be used. How about modifying existing blue transport icons by adding some "cover"?

**Comment by RedAuburn** [comment] 2024-04-21 13:01
> What about tram or trolley bus stops? Or cable car stops? Ideally, they all should be distinguished.

i'm not so sure this distinction is needed, the transport type icon will be on the `public_transport=platform` node/way. the main useful information is that it's a shelter.

**Comment by muralito** [comment] 2024-04-21 13:23
> What about tram or trolley bus stops? 

In the "Transport icons of Kyiv" there are icons for bus, bus+shelter, train, train+shelter, trolley, tram, funicular (cable car), and port.

> Ideally, they all should be distinguished. Or one universal icon for each type of transport should be used. 

I think it's better to distinguish them.

> How about modifying existing blue transport icons by adding some "cover"?

That is another possibility. I like the blue color for public transport, but any color that it's easily distinguished in the map could work well. 

What about adding a new layer with public transport info to the "Styles and map layers" ?

**Comment by muralito** [comment] 2024-04-21 14:06
> the main useful information is that it's a shelter

That depends. The problem in this issue is that OM was (or is at least in version 2024.03.31) drawing public transport POIs tagged with shelter=yes, as if they were amenity=shelter. In those cases the main useful information is that it is a public transport platform and you can wait for a bus/train/... there.

The same could be said if the POI is tagged with bench=yes, the main useful information still is that is a public transport station, not that it is a bench.

There is another problem that i see now searching for examples, a public transport platform like this https://www.openstreetmap.org/node/2153258332 is shown without icon, only his name.
![image](https://github.com/organicmaps/organicmaps/assets/7611868/ea52b3b3-d886-4bdd-9e29-196c30ec2ce5)


The problem is also that others bus stops tagged highway=bus_stop + bus=yes + public_transport=platform are displayed with bus icon.
e.g. https://www.openstreetmap.org/node/10612672629
![image](https://github.com/organicmaps/organicmaps/assets/7611868/18a13c4f-fc76-47c4-be96-aaf10447c538)

and others public_transport=platform (tagged with shelter=yes) are displayed as shelters
e.g. https://www.openstreetmap.org/node/2153307549
![image](https://github.com/organicmaps/organicmaps/assets/7611868/1c77a13b-3903-4d19-9717-f3f711592284)


In all these cases, the main information is that they are public transport platforms.

**Comment by pastk** [comment] 2024-04-21 17:28
There are many `amenity=shelter shelter_type=public_transport` without a particular PT (bus, train...) tagging. So we need a neutral icon anyway.
- https://github.com/organicmaps/organicmaps/pull/7899

**Comment by pastk** [comment] 2024-04-25 13:16
> ![image](https://private-user-images.githubusercontent.com/23003127/324209505-1e8df1e5-9972-4dfc-b9e2-90cacf477673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA4NjQsIm5iZiI6MTcxNDA1MDU2NCwicGF0aCI6Ii8yMzAwMzEyNy8zMjQyMDk1MDUtMWU4ZGYxZTUtOTk3Mi00ZGZjLWI5ZTItOTBjYWNmNDc3NjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzMDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MGFlYzVmNGI1YTZkZjk2Y2YxOTc4ZGE2N2RjZmZhZjk0ODNlNTg0ZmM0MGQ0MWIzNTFjZDRlYzQ1ZjEzNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FYfOTkZJOCuJyd7Xho14D1zMGPz0UGT3PWEe-Hwgyr4)

@patepelo Could you please prep it as an svg (light+night, m size only) please? Would be great to include it into the upcoming release!

**Comment by RedAuburn** [comment] 2024-05-16 14:37
fixed by https://github.com/organicmaps/organicmaps/pull/8007

**Closed by RedAuburn** 2024-05-16 14:37 UTC
Labels: Good first issue, Icons
