### ISSUE TITLE
[search] Organic Maps can't find a monument (and a garden)

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#973] opened 2021-08-01 02:35 UTC
Hi guys

I am using Organic Maps now for several reasons. I've been an OSM contributor for more than a decade by now and noticed the search function wasn't working at all for this element called Monumento a El Santo in Mexico City. The monument is in a little urban garden which is named following the monument there, this garden is also impossible to find in Organic Maps. Initially, I tried to find the element with no caps, then I tried to find it exactly as named in OSM with no coincidence. The element is at 19.452103, -99.129937.

I am using Organic Maps 2021.07.08-6-g73931f7918-FDroid with data version 21070806.

**Comment by biodranik** [comment] 2021-08-01 09:47
Thanks! Both objects are found flawlessly on iOS.

Do you have maps installed on an SD card or on the internal memory? Which device are you using? What exactly are you typing in the search field, and do you have the monument visible on the map at this moment? I assume that this issue is similar to #968

**Comment by CENTSOARER** [comment] 2021-08-01 13:36
Organic Maps, and actually everything is in the internal phone memory. My SD card is there but not being used. I did search "monumento a el santo", found nothing, went to it on the map and saw it there as "Monumento a El Santo", thought maybe if I searched for it with the exact caps Organic Maps would find it, but no. Then I test for the garden and nothing. This is a Moto G6 (Ali) device.

In reality I was trying to find out why Organic Maps gives you coordinates in an unknown location instead of a location based on enclosing elements and the nearest street. I am sorry if the issue is duplicated, I do not even know any Cyrillic alphabet, but this is not an issue with time of search or radius of search.

**Comment by biodranik** [comment] 2021-08-01 17:15
I've just tried it on iOS, and it works. On my Moto G6, without a referenced patch, it doesn't find the result if it's not in the viewport (to find something not in the viewport or not nearby, you need to add a city/town/village name in the search string).

**Comment by biodranik** [comment] 2021-08-01 19:07
Another test case for a slow search on Android: "Rua Ari Carneiro Fernandes, São Paulo"

**Comment by pastk** [comment] 2022-01-28 20:10
I tried those searches on android with the current stable 2022.01.15-3 and both monument and the garden searches worked fine for me - so I guess this part is fixed.

However searching for "el caminero" didn't show any results containing "caminero", but many "el" and "camino" results.
When searched for "caminero" e.g. "Tacos El Caminero" was found.
I think its the same issue as in #1376, so I'll close this one as a duplicate for now.

**Closed by pastk** 2022-01-28 20:10 UTC
Labels: Bug, Android, Search
