### ISSUE TITLE
Location indicator touches bottom panel

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#4842] opened 2023-03-23 18:14 UTC
**Describe the issue**
I used my tablet for navigation today and noticed that the location indicator touches the bottom panel while navigating in portrait mode. In pedestrian and also in car navigation (although it might change at higher speeds, idk). 
**Steps to reproduce**

**Expected behavior**
The location indicator should be totally visible even at lower speeds in both (portrait and landscape mode)

**Screenshots**

https://user-images.githubusercontent.com/7961926/227310749-a130943c-7d83-40a4-87f7-959a468aba23.mp4

https://user-images.githubusercontent.com/7961926/227310791-6e2302e7-62e3-4797-9c6d-f46aef3d7ecf.mp4

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.05-5-Google
- Device: Samsung Galaxy S6 lite

**Additional context**
The location indicator doesn't touch the bottom panel in landscape mode as the panel is clipped to the left.

**Comment by Jean-BaptisteC** [comment] 2023-03-23 18:43
Duplicate of #3441

**Comment by Jean-BaptisteC** [comment] 2023-05-20 20:11
@j13m126 please retry with latest version

**Comment by j13m126** [comment] 2023-07-02 18:50
Sorry, I missed that. Yes, it's fixed now. I guess this issue can be closed. @Jean-BaptisteC

**Closed** 2023-07-02 19:06 UTC
