### ISSUE TITLE
Bookmark removal is extremely easy

### ISSUE THREAD

**Issue by 532910** [organicmaps/organicmaps#7573] opened 2024-03-11 22:49 UTC
![Screenshot_20240312-014201_Organic Maps.png](https://github.com/organicmaps/organicmaps/assets/14617699/f07569ae-6c9f-4575-b949-10b88e01dc6e)

Possible solutions are:
- hide removal button to some next step screen
- ask for confirmation
- add ability to revert removed bookmark.

**Comment by Jean-BaptisteC** [comment] 2024-03-12 05:33
Duplicate of #1173

**Closed by Jean-BaptisteC** 2024-03-12 05:33 UTC
