### ISSUE TITLE
TTS without GAPPs. eSpeak. Ivona

### ISSUE THREAD

**Issue by jybghdog** [organicmaps/organicmaps#7073] opened 2024-01-04 13:01 UTC
I share my experience with TTS' without GAPPs. In OM 2023.12.20-4-Web, I think since the latest version, it didn't happen before, when using the Ivona TTS engine the "Voice Instructions" setting is cleared on reboot (LineageOS 20). When you enter "Voice Instructions" it says "Unavailable" when the TTS engine is installed and working. To fix it, I have to "force close" OM. After that, I can activate Ivona and the test works correctly and navigation. After that, as stated above, if I power off/reboot, it comes back as "Unavailable" and I have to force close and activate again.
I have checked that with the eSpeak engine this does not happen, the configuration is maintained with reboots, confirming that the problem is with the Ivona engine and occurs with some recent update of the app, it did not happen when I installed Ivona some time ago.

**Comment by Jean-BaptisteC** [comment] 2024-02-26 21:29
Duplicate of #6527

**Closed by Jean-BaptisteC** 2024-02-26 21:29 UTC
Labels: Android, TTS
