### ISSUE TITLE
Directions in the background

### ISSUE THREAD

**Issue by KillerKingSolo** [organicmaps/organicmaps#8868] opened 2024-08-06 17:40 UTC
Organic Maps does not say your directions when you go to a different app or you turn off your phone and when you go back to the app, it has to recalibrate the path and figure out where you are. It would be nice like other apps where you can have to directions running in the background and be doing something else on your phone.

**Comment by RedAuburn** [comment] 2024-08-06 18:19
it already has background directions, have you allowed notifications for the app?

**Comment by KillerKingSolo** [comment] 2024-08-06 18:20
It shouldn't need notifications to say the directions in the background if it gives you a post notification every turn that's very annoying. It should just say it in the background.

**Comment by KillerKingSolo** [comment] 2024-08-06 18:25
Also, for some reason every time I try to add tags it just doesn't add tags for GitHub. It keeps removing them and then I can't add them afterwards.

**Comment by matheusgomesms** [comment] 2024-08-07 09:06
Duplicate of #6940.

**Closed by matheusgomesms** 2024-08-07 09:06 UTC
Labels: Duplicate
