### ISSUE TITLE
Measure distance

### ISSUE THREAD

**Issue by HiddenLeveI** [organicmaps/organicmaps#4139] opened 2022-12-23 01:47 UTC
This is a feature request:

You guys should add a feature where you can measure distances between places like what google earth has. It would be helpful for knowing how many miles I'm running.

**Comment by biodranik** [comment] 2022-12-23 07:20
What exactly do you mean? Is it something similar to #1452 ?

**Comment by mxdanger** [comment] 2022-12-24 00:28
Organic Maps already has route distance. If you mean straight-line measuring, then this would be a duplicate of #1452 as mentioned above.

**Comment by HiddenLeveI** [comment] 2022-12-24 15:29
Yes, I meant like #1452

**Comment by mxdanger** [comment] 2022-12-24 23:22
Alright so this should be closed as a duplicate of #1452

**Closed** 2023-02-15 20:31 UTC
