### ISSUE TITLE
Show osm ID of features

### ISSUE THREAD

**Issue by dpriskorn** [organicmaps/organicmaps#5053] opened 2023-04-28 11:30 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to add shelters to Wikidata when out and about and I need the id og the object if they are already in osm but I can't get it from organic maps 
![Screenshot_20230428-132735_Organic Maps.png](https://user-images.githubusercontent.com/68460690/235136278-41e1e427-c6e9-4494-978b-d89c7a1a3776.png)

I can easily get the title and coordinates and that is super nice 🙂

**Describe the solution you would like**
Show the id and make it copy on long press like the other information

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
- Attach any examples, screenshots, or screen recordings from other apps that help us to better understand the idea.

**Additional context**

**Comment by endim8** [comment] 2023-04-28 12:07
Duplicate of https://github.com/organicmaps/organicmaps/issues/1597 

Why do you need the ID for Wikidata?

**Comment by dpriskorn** [comment] 2023-04-29 19:20
I'm adding it to the feature on the campsite there

**Comment by dpriskorn** [comment] 2023-04-29 19:22
I found out that osm focus reborn already cover my usecase well 😀
Closing

**Closed** 2023-04-29 19:22 UTC
Labels: Enhancement

**Comment by endim8** [comment] 2023-04-29 19:33
you might also like https://github.com/Zverik/every_door :)
