### ISSUE TITLE
Allow adding a new place in OSM while navigating

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4891] opened 2023-03-31 07:43 UTC
It is not possible now to activate Add Place feature to add a new place into osm.org if navigation is active. Some users want to use it while walking, or even while driving, without cancelling the navigation mode.

We need to think about the UX for it. Can the "Add Place" functionality be activated from the expanded navigation dashboard, by, for example, pressing a "+" button there?

**Comment by Jean-BaptisteC** [comment] 2023-03-31 08:35
Similar of https://github.com/organicmaps/organicmaps/issues/265

**Comment by RedAuburn** [comment] 2023-11-01 21:16
closing as duplicate of #265

**Closed by RedAuburn** 2023-11-01 21:16 UTC
Labels: Editor, UX, Navigation
