### ISSUE TITLE
Allow adding OSM Notes

### ISSUE THREAD

**Issue by fancsali** [organicmaps/organicmaps#9003] opened 2024-08-18 09:04 UTC
⚠ Have you searched for similar, already existing issues? - Yes.

**Is your feature request related to a problem? Please describe.**

I find the simplicity and streamlined nature of the app very much appealing. I am considering switching to Organic Maps as my main mapping tool. 

However, I'm also an OSM contributor, and the only reason I've got other OSM apps on my phone is for adding notes that I can action later on my more comfy desktop setup (as opposed to just adding places).

**Describe the ideal solution**
Like the "add place" a menu item (or button) to add a note directly. 

**Describe alternatives you have considered**
Using another app _alongside_, but that has a few issues:
- Need to keep switching 
- Need to download and managemaps twice

**Additional context**
...

**Comment by map-per** [comment] 2024-08-18 17:04
This looks like a duplicate of #266

**Comment by biodranik** [comment] 2024-08-18 18:25
Adding a note to an existing place using Edit Place is already working, right? So we're talking only about notes added somewhere on the empty map area, right?

**Comment by map-per** [comment] 2024-08-19 15:19
Yes, you can add a note to an existing POI, but you can not place a note in an arbitrary position.

E.g. you can not mark the exact position of a watering_place within a forest. You can however add a note to the forest (it will be placed in the centre of the forest)

**Closed** 2024-11-24 19:58 UTC
Labels: Editor
