### ISSUE TITLE
Valid name with an apostrophe not found

### ISSUE THREAD

**Issue by richlv** [organicmaps/organicmaps#3420] opened 2022-09-16 11:40 UTC
Searched for "Ben's Fish and Chips" while in London, found nothing.
Was sure it's not mapped, until I walked to it and attempted to map it...

Turns out, it is only found if I search for "Bens Fish and Chips", omitting the apostrophe.

Issue #1262 handled something similar recently, and some changes were merged on August 11th in #3128, but this behaviour was observed with Organic Maps 2022.08.23-3.

Object in OSM: https://www.openstreetmap.org/node/5009891423 .

**Comment by richlv** [comment] 2022-09-17 14:54
Same with 2022.09.15-2 .
The first result for "ben’s fish and chips" is "South Park".

**Comment by Jean-BaptisteC** [comment] 2024-01-20 20:17
Fixed in 2024.01.09-6-Google

**Closed by Jean-BaptisteC** 2024-01-20 20:17 UTC
Labels: Search

**Comment by richlv** [comment] 2024-01-22 11:29
Hi, what is that name, is "-Google" somehow related?
Was it supposed to be a link to a commit or such?

**Comment by biodranik** [comment] 2024-01-22 11:39
@richlv do you still reproduce the issue on the latest January Organic Maps version?

**Comment by richlv** [comment] 2024-01-22 12:44
Haven't tried it, don't want to download extra maps right now :)
Curious about the mentioned name - if that is a version number, why is there "-Google"?
For example, was this fixed for Android only?

**Comment by Jean-BaptisteC** [comment] 2024-01-22 13:01
Google is the type of version app:
- Google version include library to use Google Play Services location
- Fdroid version doesn't include this library
Correction is fixed on IOS and Android, this code is shared between all platforms

**Comment by richlv** [comment] 2024-01-22 13:50
Heya, thanks - still not sure how "-Google" came into play here, but glad to hear it's supposed to be working OK in all platforms now :)

**Comment by Jean-BaptisteC** [comment] 2024-01-22 14:00
Because, I have tested on this version :)
