### ISSUE TITLE
Saving calculated Routes

### ISSUE THREAD

**Issue by crueter** [organicmaps/organicmaps#9603] opened 2024-11-03 15:32 UTC
⚠ Have you searched for similar, already existing issues?
Yes

**Is your feature request related to a problem? Please describe.**
Route calculation can take a while, especially on very long trips. This can delay travel by several minutes and is generally inconvenient.

**Describe the ideal solution**
The ability to "save"/bookmark calculated routes. This would allow us to calculate the route in advance and be able to load it up at-will.

**Describe alternatives you have considered**
Calculating the route a few minutes before I leave and praying the app doesn't reload.

**Additional context**

**Comment by map-per** [comment] 2024-11-03 16:24
Looks like a duplicate of #1785

**Comment by crueter** [comment] 2024-11-03 16:35
That thread is 3 years old and all its recent activity seems to focus primarily on exporting/importing. Saving routes is a higher priority for me, and unless the two features go hand-in-hand then these are separate issues.

**Comment by biodranik** [comment] 2024-11-03 17:50
This is clearly a duplicate. Exporting and importing are already working for tracks, but not for routes.

**Closed by biodranik** 2024-11-03 17:50 UTC

**Comment by 0709wiwiwi** [comment] 2024-11-09 15:37
@crueter
A previously calculated TBT track saves you either or in the app itself or as an exported file. 
Cruiser offers both options either internally or by export as .kurviger or gpx (gpz) navigation track file.  
After re-import offers an immediately ready to useTBT navigation without any delaying (modifying) recalculation required. 
Do not be fooled by "track", because although technically a gpx track it contains all necessary elements to immediately start up a 100% faithful TBT navigation.  Not convinced ? 
Import the attached gpz file (without .txt) in Cruiser and navigate.  Import in Locus map works the same simple way.
To test you can use Cruiser free and start an 'on sofa' navigation simulation. 
At import select gpz automatic (Overlay+routing). Then press the navigation button and select simulation.
Know a compact gpz file is simply a zipped gpx file that you can import directly into both Cruiser and Locus.
[1_Sudetenland_1_2.gpz.txt](https://github.com/user-attachments/files/17688475/1_Sudetenland_1_2.gpz.txt)


Translated with DeepL.com (free version)
