### ISSUE TITLE
Saved bookmark hides POI details

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#4124] opened 2022-12-20 17:03 UTC
Saving a bookmark on a POI causes its details to be then hidden:

https://user-images.githubusercontent.com/29158971/208723965-e5cc70f5-dd61-4b2b-8991-c80b33407081.mp4

**Comment by Jean-BaptisteC** [comment] 2022-12-20 17:34
Duplicate of #2825

**Closed** 2022-12-21 10:29 UTC
Labels: Duplicate
