### ISSUE TITLE
Sync OpenStreetMaps changes made before login

### ISSUE THREAD

**Issue by ioctl-user** [organicmaps/organicmaps#840] opened 2021-07-11 09:51 UTC
I have created some changes of places without logging in. After that I have entered OSM login, but those changes were not synced. I didn't find any button to force this. Seems, it's a bug.

Version 2021.07.04 from F-Droid.

**Comment by biodranik** [comment] 2021-07-11 14:24
Can you please type ?edits in the search field? What is displayed there?

**Comment by ioctl-user** [comment] 2021-07-11 18:33
"Uploaded: 0"

**Comment by biodranik** [comment] 2021-07-11 18:49
That could be a bad sign of a bug. Normally, edits should be saved before you log in to be uploaded later. But in your case, by some reason, edits have been lost.

Was the app uninstalled before a new version is installed?

**Comment by biodranik** [comment] 2021-07-11 18:51
Also, did you move maps to the SD card in the old version?

**Comment by ioctl-user** [comment] 2021-07-11 19:34
I have installed new version with ADB after edits and before login. The older one was installed by fdroid app directly. At that, other data like maps and bookmarks was not lost.

I didn't move maps to SD. Old version stored it's data in /data/data/ directory.

My edits were disappered, but it's not a big problem. For now I repeated some of them. They appear in ?edits menu, but Uploaded still 0. How to commit them?

**Comment by biodranik** [comment] 2021-07-11 20:14
It's a nasty bug that edits disappeared. If you're logged in, they should be uploaded automatically when the app goes into the background.

**Comment by ioctl-user** [comment] 2021-07-12 07:44
> If you're logged in, they should be uploaded automatically when the app goes into the background.

It's still not after 12 hours.

**Comment by biodranik** [comment] 2021-07-12 08:14
That's a bug, definitely. Can you please record adb logs while editing some features, and then switching to another app?

**Comment by ioctl-user** [comment] 2021-07-13 09:03
My yesterday edit still exist on my local map, so, I cannot redo it. Also I would prefer filter output, please let mi know if I should extend filter expression. Here is ```adb logcat | grep -i maps``` output starting from moment when maps was active and then other app become active for a few minutes:


```07-13 11:56:26.548  7903  7903 I MapsmeCore: maps/Framework.cpp:393 PauseSurfaceRendering()  Pause surface rendering.
07-13 11:56:26.548  7903  7903 I BaseActivityDelegate: MwmActivity: onPause() activity: com.mapswithme.maps.MwmActivity@6ada846
07-13 11:56:26.558  7903  7903 I MapsmeCore: maps/Framework.cpp:291 DetachSurface()  Detach surface started. destroySurface = 1
07-13 11:56:26.559  7903  7903 I MapsmeCore: maps/Framework.cpp:304 DetachSurface()  Destroy surface.
07-13 11:56:26.562  7903  7903 I MapsmeCore: maps/Framework.cpp:326 DetachSurface()  Detach surface finished.
07-13 11:56:26.574  7903  7903 I BaseActivityDelegate: MwmActivity: onStop() activity: com.mapswithme.maps.MwmActivity@6ada846
07-13 11:56:26.574  7903  7903 I MapsmeCore: maps/Framework.cpp:880 Java_com_mapswithme_maps_Framework_nativeRemovePlacePageActivationListener()  Remove global map object listener
07-13 11:56:27.618  7903  7987 I OsmUploadService: onHandleWork: Intent { cmp=app.organicmaps/com.mapswithme.maps.background.OsmUploadService }```

**Comment by biodranik** [comment] 2021-07-13 09:27
Please record a log using `adb logcat -v color --pid=$(adb shell pidof app.organicmaps)`

**Comment by ioctl-user** [comment] 2021-07-13 11:21
Clear log, start logcat, activate maps, deactivate maps, run other app, wait about minute, stop logcat:

```07-13 14:16:36.348 12328 12413 I OsmUploadService: onHandleWork: Intent { cmp=app.organicmaps/com.mapswithme.maps.background.OsmUploadService }
07-13 14:16:38.740 12328 12328 I BaseActivityDelegate: MwmActivity: onStart() activity: com.mapswithme.maps.MwmActivity@6ada846
07-13 14:16:38.741 12328 12328 I MapsmeCore: maps/Framework.cpp:840 Java_com_mapswithme_maps_Framework_nativePlacePageActivationListener()  Set global map object listener
07-13 14:16:38.742 12328 12328 I LocationUtils: Available location providers: passive gps
07-13 14:16:38.756 12328 12328 I BaseActivityDelegate: MwmActivity: onResume() activity: com.mapswithme.maps.MwmActivity@6ada846
07-13 14:16:38.770 12328 12328 I BaseActivityDelegate: MwmActivity: onPostResume() activity: com.mapswithme.maps.MwmActivity@6ada846
07-13 14:16:38.783 12328 12328 I MapsmeCore: maps/Framework.cpp:331 AttachSurface()  Attach surface started.
07-13 14:16:38.794 12328 12328 I MapsmeCore: maps/Framework.cpp:375 AttachSurface()  Recover surface, viewport size: 1080 2355
07-13 14:16:38.796 12328 12328 I MapsmeCore: maps/Framework.cpp:381 AttachSurface()  Attach surface finished.
07-13 14:16:38.796 12328 12328 I MapsmeCore: maps/Framework.cpp:409 ResumeSurfaceRendering()  Resume surface rendering.
07-13 14:16:39.741 12328 12328 I LocationHelper: Provider 'com.mapswithme.maps.location.AndroidNativeProvider@3d29c1a' is already started
07-13 14:16:50.569 12328 12328 I MapsmeCore: maps/Framework.cpp:393 PauseSurfaceRendering()  Pause surface rendering.
07-13 14:16:50.569 12328 12328 I BaseActivityDelegate: MwmActivity: onPause() activity: com.mapswithme.maps.MwmActivity@6ada846
07-13 14:16:50.575 12328 12328 I MapsmeCore: maps/Framework.cpp:291 DetachSurface()  Detach surface started. destroySurface = 1
07-13 14:16:50.575 12328 12328 I MapsmeCore: maps/Framework.cpp:304 DetachSurface()  Destroy surface.
07-13 14:16:50.579 12328 12328 I MapsmeCore: maps/Framework.cpp:326 DetachSurface()  Detach surface finished.
07-13 14:16:50.595 12328 12328 I BaseActivityDelegate: MwmActivity: onStop() activity: com.mapswithme.maps.MwmActivity@6ada846
07-13 14:16:50.595 12328 12328 I MapsmeCore: maps/Framework.cpp:880 Java_com_mapswithme_maps_Framework_nativeRemovePlacePageActivationListener()  Remove global map object listener
07-13 14:16:51.670 12328 12413 I OsmUploadService: onHandleWork: Intent { cmp=app.organicmaps/com.mapswithme.maps.background.OsmUploadService }
```

**Comment by biodranik** [comment] 2021-07-13 15:45
Is there any app/device setting related to the app's connections in the background?

**Comment by ioctl-user** [comment] 2021-07-13 16:04
I cannot recall this. Other apps like messengers work in background fine.

However, this phone firmware very buggy itself, so, it may be root of problem.

**Comment by rtsisyk** [comment] 2023-11-01 07:50
I am closing this ticket because it's been a while and a lot of things have changed. OSM sync is now triggered every time when the app goes background. The missing button "Sync right now" is a different UX issue and let's track it difference.

**Closed by rtsisyk** 2023-11-01 07:50 UTC
Labels: Bug, Android

**Comment by biodranik** [comment] 2023-11-01 09:14
@ioctl-user can you please check if your issue is still reproduced with the most recent OM version?

**Comment by ioctl-user** [comment] 2023-11-01 15:06
> @ioctl-user can you please check if your issue is still reproduced with the most recent OM version?

Issue is fixed in recent versions.
