### ISSUE TITLE
Show Collection Times for Mail Drop Boxes (amenity=postbox)

### ISSUE THREAD

**Issue by DicePenguin** [organicmaps/organicmaps#8741] opened 2024-07-20 23:44 UTC
⚠ Have you searched for similar, already existing issues?
Yes

I think it would be worthwhile if pickup times (collection_times=*) for USPS, UPS, Fed-Ex, etc, drop boxes could be displayed and edited using the interface similar to the way we can "Add Opening Hours" to businesses.

**Comment by Jean-BaptisteC** [comment] 2024-07-21 05:28
Duplicate of #2431

**Closed by Jean-BaptisteC** 2024-07-21 05:28 UTC
Labels: Enhancement
