### ISSUE TITLE
Small scale visualization of downloaded map areas

### ISSUE THREAD

**Issue by JonathanDoughty** [organicmaps/organicmaps#6018] opened 2023-09-13 19:53 UTC
I am frustrated when, if I am planning a trip, the only way to insure that the areas I am going to need available offline is to pan and zoom my way around the extent of the area I am planning to visit.

Related: I'd like to see a map layer that would depict the rough geographic outlines of areas that I've already downloaded, or that need updates, in addition to the folder views of areas to download or update. Currently I can only guess where the boundaries of downloaded areas are by looking for extra detail.

Use case: Imagine I am going on a bike tour of Belgium or United Kingdom. Either I have to know the names of the provinces/regions I am going to visit or I have to pan and zoom my way around the intended tour route (assuming I know that well enough in advance) on a largish-scale map view of Belgium / UK to insure that I am prompted to download the areas that I may encounter during my tour. If I miss observing that a province/region boundary is near but does not overlap the expected route I may end up _not_ downloading coverage for where nearby points of interest might be located for end of day meet ups.

Organic Maps would be improved if the user could get a visualization - a map layer - usable at the smallest scale that would show where there are 'holes' in downloaded coverage. 

Even better would be some color coding to indicate where maps already downloaded have updates available and let the user queue those for updating. Users could be prompted / request to update by zooming in those only when that map layer is visible. This would be especially useful when users' bandwidth is limited and they only want to update a single area near to where they are currently located. 

Still better would be a way for users to visualize where they may have maps downloaded that are no longer needed so that they could delete those from local storage, without having to navigate down and up the folder hierarchy. That way if/when areas are downloaded by mistake that can be easily undone.

**Comment by dvdmrtnz** [comment] 2023-09-13 20:24
Osmand shows downloaded regions shaded in green when zoomed out:

![](https://github.com/organicmaps/organicmaps/assets/47610359/a00fd142-82c6-48f4-a6ff-d72e6ffc33f5)

**Comment by pastk** [comment] 2023-09-17 13:14
Duplicate of https://github.com/organicmaps/organicmaps/issues/1356

Please track the progress and share ideas in the existing issue!

**Closed by pastk** 2023-09-17 13:14 UTC
Labels: Enhancement
