### ISSUE TITLE
HK subway

### ISSUE THREAD

**Issue by cffung** [organicmaps/organicmaps#1242] opened 2021-09-03 07:18 UTC
How to report or suggest the subway update ?

**Comment by biodranik** [comment] 2021-09-03 10:03
What is the mistake? Is it already fixed in OSM?

**Comment by cffung** [comment] 2021-09-03 10:39
OSM updated but Organicmap not

**Comment by biodranik** [comment] 2021-09-03 16:10
In which city? How can we test and check that the issue is fixed?

**Comment by cffung** [comment] 2021-09-06 07:51
Hong Kong, please refer to the official website
http://www.mtr.com.hk/en/customer/services/system_map.html

**Comment by dikkechill** [comment] 2022-03-16 20:24
Hi cffung, 
There are a number of issues with the current Hong Kong OpenStreetMap data, hence the subway map doesn't show in OrganicMaps at the moment.
You can find a list of the issues here: https://cdn.organicmaps.app/subway/china.html under Hong Kong.

**Closed** 2024-01-14 17:17 UTC
Labels: Bug, Map Data, Metro
