### ISSUE TITLE
Wikipedia description not visible when node is pinned

### ISSUE THREAD

**Issue by keunes** [organicmaps/organicmaps#3337] opened 2022-09-04 12:26 UTC
Many nodes have their Wikipedia info displayed when opening the node. However, when pinning the node, this Wikipedia info gets hidden.

This is not ideal when traveling, when you prepare your pins (things to visit) and cannot easily read offline Wikipedia info when you arrive to your pinned location.

![Imagepipe_1.jpg](https://user-images.githubusercontent.com/11229646/188313389-7c5eaa97-d7b6-4c33-bff0-c72daa5fb046.jpg) ![Imagepipe_0.jpg](https://user-images.githubusercontent.com/11229646/188313394-06cb87ce-7e26-4d8f-b4ed-13fb3b1bb2e0.jpg)

I would advocate for keeping the same view when an item is pinned and when it is not. Or, if not desired, to at least have the 'Description' heading collapsed or have a way to open the offline (stored) full description text.

**Comment by arnaudvergnet** [comment] 2022-09-04 14:10
Duplicate of https://github.com/organicmaps/organicmaps/issues/2825

**Comment by keunes** [comment] 2022-09-04 17:43
Sorry, don't know why I didn't find that one when I was searching. Thanks!

**Closed** 2022-09-04 17:43 UTC
