### ISSUE TITLE
Add current road speed limit when navigating or when driving but not navigating (and cycling?)

### ISSUE THREAD

**Issue by J0shuaM** [organicmaps/organicmaps#5930] opened 2023-09-04 02:23 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example:
I'm always frustrated when [...]

**Describe the solution you would like**
Ability to always view speed limit (when you are paranoid about speed cameras and already know where you are going)

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
![osmand-menus](https://github.com/organicmaps/organicmaps/assets/143977378/10db8503-02e3-49a8-b0ec-afcc3b53846d)
![speed_limit_widget-a19cefbe403b7aeb0ede98ebf8e9338a](https://github.com/organicmaps/organicmaps/assets/143977378/26c6efc5-86a5-41d3-87be-e40ae8ad3fbc)

**Comment by Jean-BaptisteC** [comment] 2023-09-04 04:33
Duplicate of #2968

**Comment by biodranik** [comment] 2023-09-04 05:32
Duplicate of #952

**Closed by biodranik** 2023-09-04 05:32 UTC
Labels: Enhancement
