### ISSUE TITLE
[CarPlay] Hide inactive traffic icon

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#8449] opened 2024-06-12 14:17 UTC
We may implement it later, now it only confuses users:

![image](https://github.com/organicmaps/organicmaps/assets/170263/0d2d9915-e819-4a90-acd2-37328532ec6b)

CC @kirylkaveryn @fabwu

**Comment by fabwu** [comment] 2024-06-12 16:16
@biodranik So you want us to remove the traffic light symbol?

![image](https://github.com/organicmaps/organicmaps/assets/6050639/b9d49709-d8a1-441d-afb4-21dcb8f56eaa)

**Comment by biodranik** [comment] 2024-06-12 16:22
Yes please )

**Comment by Jean-BaptisteC** [comment] 2024-06-12 16:43
Duplicate of #868

**Closed** 2024-06-12 19:01 UTC
Labels: CarPlay
