### ISSUE TITLE
Wrong display of opening hours

### ISSUE THREAD

**Issue by rac-HH** [organicmaps/organicmaps#9035] opened 2024-08-20 15:13 UTC
**Describe the issue**
"off" in opening hours is displayed as whole day open (24 hours).

**Steps to reproduce**
1. E.g. confirm opening hours here: https://www.openstreetmap.org/node/7124117749/history/4
     opening_hours: Mo-Sa 08:00-20:00; Su,PH off
3. Use Organic Maps (Android) with german maps
4. Search "Bruchsal, Stegwiesenstraße 4" - Select "Aldi Süd"
5. See Opening hours:
    Mo-Sa 8:00 - 20:00
   So "Ganztägig (24 Stunden)"  = "whole day"

**Expected behaviour**
So, PH: "geschlossen"  =  "closed"

**Screenshots**
![Screenshot_20240820-170604](https://github.com/user-attachments/assets/b2e1f28f-301f-4479-a15e-80deede34d55)

**System information:**
 - Operating system and its version: Android 10
 - Organic Maps version: 2024.08.15-21-FDroid
 - Device Model: TeraCube

**Additional context**
-

**Comment by matheusgomesms** [comment] 2024-08-23 09:18
Duplicate of #1575

**Closed by matheusgomesms** 2024-08-23 09:18 UTC
