### ISSUE TITLE
Bus routes are not shown in public transport Kochi

### ISSUE THREAD

**Issue by pravi** [organicmaps/organicmaps#5722] opened 2023-08-15 07:27 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example:
I'm always frustrated when I can't find bus routes which are already mapped. 

**Describe the solution you would like**
Organic maps should also show bus routes.

**Describe alternatives you have considered**
- OSMAnd has this already.
- Attach any examples, screenshots, or screen recordings from other apps that help us to better understand the idea.

**Additional context**

**Comment by Jean-BaptisteC** [comment] 2023-08-15 08:39
Please check similar issues

**Comment by RedAuburn** [comment] 2023-08-15 08:44
duplicate of https://github.com/organicmaps/organicmaps/issues/2502

**Closed by RedAuburn** 2023-08-15 08:44 UTC
Labels: Enhancement
