### ISSUE TITLE
[ios] The map is moved when "Add place" is selected from Place Page or from the menu

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1095] opened 2021-08-13 20:59 UTC
It's strange because I have already selected a place on the map with a long tap and pressed "Add a place," expecting that it will be added exactly at the currently selected place on the map. This bug requires additional unnecessary actions from the user.

**Comment by map-per** [comment] 2024-09-28 17:27
closing this issue as duplicate of #9122 because the newer issue has a video

**Closed by map-per** 2024-09-28 17:27 UTC
Labels: iOS, Editor, UX
