### ISSUE TITLE
[Routing] Save as file

### ISSUE THREAD

**Issue by Shohreh** [organicmaps/organicmaps#4118] opened 2022-12-20 02:45 UTC
Hello,

I have a suggestion for routing: Make it possible to save it in a file, so that it's permanent and error-safe. Currently, it's gone if the user closes the app.

Cheers,

**Comment by biodranik** [comment] 2022-12-20 06:59
It's a duplicate of #1785

**Closed by biodranik** 2022-12-20 06:59 UTC
Labels: Duplicate, Routing
