### ISSUE TITLE
Show `operator` field for some objects

### ISSUE THREAD

**Issue by soshial** [organicmaps/organicmaps#8406] opened 2024-06-07 12:36 UTC
**Is your feature request related to a problem? Please describe.**
Usually the name for some objects (ATM, parcel lockers etc.) is empty, but [operator is usually there](https://www.openstreetmap.org/node/3525961464/history/7). In the "Map View" Organic Maps ignores operator field, but shows the address instead.

<img src="https://github.com/organicmaps/organicmaps/assets/100644/a82b7d25-7caa-4f24-8f60-d2beac7fc5f0" width="300" /><img src="https://github.com/organicmaps/organicmaps/assets/100644/2711a086-9922-49cd-92a7-b6ca180fdd09" width="300"  />

**Describe the ideal solution**
Take the operator field (depending on language) and show it on map.

**Additional context**
Extracted into separate issue from https://github.com/organicmaps/organicmaps/issues/6329#issuecomment-1989159316

**Comment by Jean-BaptisteC** [comment] 2024-06-07 17:13
Duplicate of #8039

**Closed by Jean-BaptisteC** 2024-06-07 17:13 UTC
Labels: Enhancement
