### ISSUE TITLE
Priorities of multiple types in a single feature - for naming (rendering is fixed)

### ISSUE THREAD

**Issue by Misalf-git** [organicmaps/organicmaps#1392] opened 2021-10-09 13:38 UTC
![shelter_bench.png](https://user-images.githubusercontent.com/72605561/136659829-45682600-c766-475a-a7e7-68756802971f.png)

("Parkbank" is german for "bench")

50.990302, 7.058869
https://omaps.app/84JGAMwAVj

**Comment by pastk** [comment] 2022-01-31 18:52
Another example is `amenity=shelter` + `bench=yes` here https://www.openstreetmap.org/node/720550914
![Screenshot_1643653448](https://user-images.githubusercontent.com/18434508/151854457-f0e97073-a2d2-464d-8dc5-185e6ad7be8e.png)

**Comment by pastk** [comment] 2022-01-31 19:08
Our mechanism to prioritize several types coexisting inside one feature doesn't work here
as we need to keep both benches and shelters in the low priority list here:

https://github.com/organicmaps/organicmaps/blob/c4f4f7a7f478c0331e5c98eb1b8b7bc194639ccf/indexer/feature_data.cpp#L117-L144

But the list is not order-sensitive. So its just both of them having same low priority compared to types not in the list.

Its possible to refactor it to make the list case-sensitive, but an overall better solution would be to use z-index from the styles - its not hardcoded and all/most of the types are prioritized there already. And this list above could be used for some special types like psurface and hwtag if needed.
What do you think @vng ?

**Comment by biodranik** [comment] 2022-01-31 20:00
I would not set a style dependency. Then the same feature may display different info after switching styles.

**Comment by pastk** [comment] 2022-01-31 20:06
Do you have a situation in mind when we'd want to draw feature B over the A, but see it named A still?

**Comment by pastk** [comment] 2022-01-31 20:20
But I have a pro-using-z-index example: 
https://www.openstreetmap.org/way/78047524
has `highway=track` and `piste:type=nordic`
On a "regular"/"summer" map we'd want to show it as a track and name as a track.
On a ["Snow map"](https://github.com/organicmaps/organicmaps/issues/1577#issuecomment-1025788515) we'd want to display it as a piste and name as such too.

**Comment by vng** [comment] 2022-01-31 20:37
Make shelter _better_ than bench, no?

**Comment by pastk** [comment] 2022-01-31 22:17
> Make shelter _better_ than bench/waste_busket, etc, no?

Introduce another list of "useful types" in addition to "useless types"?  So we'll have 3 priority tiers instead of two.
But I think we need 4 already:
1. bus_stop
2. public_transport = platform
3. shelter
4. bench

Also it'll

**Comment by biodranik** [comment] 2022-12-15 17:21
What does it mean, an area Park, marked with Bench?.. Each bench should be mapped separately, no?

**Comment by vng** [comment] 2022-12-15 17:39
Oh, probably, it means that park in general has benches, but this is hilarious .. Ok, I can make _park_ type higher than _bench_, but ...

**Comment by biodranik** [comment] 2022-12-15 17:48
That's clearly a mapping mistake, right? Benches should be drawn ON TOP of the park area.

**Comment by pastk** [comment] 2023-01-21 15:11
This issue is similar to #655

**Comment by pastk** [comment] 2023-01-21 15:14
> > Make shelter _better_ than bench/waste_busket, etc, no?
> 
> Introduce another list of "useful types" in addition to "useless types"? So we'll have 3 priority tiers instead of two. But I think we need 4 already:
> 
>     1. bus_stop
> 
>     2. public_transport = platform
> 
>     3. shelter
> 
>     4. bench

Partly this issue could be solved by preserving e.g. `bench=yes`, `shelter=yes` as secondary tags / attributes of the main feature tag, which is a bus stop here.
Both PP and map icon should show the primary/main feature. 
See a similar issue at https://github.com/organicmaps/organicmaps/issues/655#issuecomment-1067333596

**Comment by biodranik** [comment] 2023-01-28 14:08
Our current types-system does not support primary and secondary styles, like OSM tags are doing. The main question: can we guess/hardcode the priorities and avoid introducing primary/secondary types? What are the cases where it won't work? E.g. when both options are valid:

amenity=primary
secondary=yes

and

amenity=secondary
primary=yes

**Comment by pastk** [comment] 2023-09-17 15:21
Rendering of a proper/main (priority-wise) icon was fixed in #4590.

So now the issue is about displaying a proper corresponding title in the place page.
We should discard the "UselessTypes" system and refer to style-set priorities instead.

**Closed** 2024-02-09 17:54 UTC
Labels: Bug, Map Data, Styles, Classificator
