### ISSUE TITLE
Frequent app crashes on iOS 16.5 and higher

### ISSUE THREAD

**Issue by hay** [organicmaps/organicmaps#5396] opened 2023-06-25 21:52 UTC
**Describe the issue**
Since iOS 16.5 and later the app seems to be very unreliable. My wife updated to iOS 16.5.1 and since then the app crashes every time in just a second or two after launching. This happened also after rebooting the phone, force closing the app and even reinstalling it. Unfortunately she’s lost all her bookmarks. 

I’m seeing comparable behavior on my phone (which is still on 16.5) but it’s still somewhat semi-usable, but also crashes often. 

I have a feeling, but this is just a hunch, that the crashes occur more often on my phone when I’m editing and adding bookmarks. 

If that is useful i could provide crash logs. 

**System information:**
 - Operating system and its version: iOS 16.5 (my phone) and 16.5.1 (my wife’s phone)
 - Organic Maps version: 2023.06.04-12
 - Device Model: iPhone 12 mini (mine) and iPhone 13 mini (wife’s)

**Comment by biodranik** [comment] 2023-06-26 04:30
Crash logs are very useful. Can you please send them at ios@organicmaps.app or attach here?

If app was not reinstalled, you can copy bookmarks folder to mac using Finder and [iOS File Sharing](https://support.apple.com/en-us/HT210598) and send them to us to investigate/restore.

**Comment by hay** [comment] 2023-06-26 20:10
[Organic Maps-2023-06-25-084434.ips.txt](https://github.com/organicmaps/organicmaps/files/11873711/Organic.Maps-2023-06-25-084434.ips.txt)

**Comment by hay** [comment] 2023-06-26 20:12
[Organic Maps-2023-06-25-120329.ips.txt](https://github.com/organicmaps/organicmaps/files/11873759/Organic.Maps-2023-06-25-120329.ips.txt)

**Comment by hay** [comment] 2023-06-26 20:13
@biodranik thanks, i’ve attached two crash logs. The first one is from my wife's phone, the second one from my phone.

**Comment by biodranik** [comment] 2023-06-27 16:34
@vng @rokuz It looks like a Drape crash that is caused by some non-standard data to draw.

@hay What map area/town/city was displayed on your phones when they started to crash? Did you have the latest maps downloaded?

```
dp::LineRawBatch::BatchData(ref_ptr<dp::GraphicsContext>, ref_ptr<dp::AttributeProvider>) (in Organic Maps) + 1328
dp::IndicesRange dp::Batcher::InsertPrimitives<dp::LineRawBatch, std::__1::vector<int, std::__1::allocator<int> > >(ref_ptr<dp::GraphicsContext>, dp::RenderState const&, ref_ptr<dp::AttributeProvider>, std::__1::unique_ptr<dp::OverlayHandle, std::__1::default_delete<dp::OverlayHandle> >&&, unsigned char, std::__1::vector<int, std::__1::allocator<int> >) (in Organic Maps) + 240
dp::Batcher::InsertLineRaw(ref_ptr<dp::GraphicsContext>, dp::RenderState const&, ref_ptr<dp::AttributeProvider>, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::unique_ptr<dp::OverlayHandle, std::__1::default_delete<dp::OverlayHandle> >&&) (in Organic Maps) + 152
dp::Batcher::InsertLineRaw(ref_ptr<dp::GraphicsContext>, dp::RenderState const&, ref_ptr<dp::AttributeProvider>, std::__1::vector<int, std::__1::allocator<int> > const&) (in Organic Maps) + 48
df::AreaShape::DrawArea3D(ref_ptr<dp::GraphicsContext>, ref_ptr<dp::Batcher>, m2::Point<double> const&, m2::Point<double> const&, ref_ptr<dp::Texture>) const (in Organic Maps) + 1832
df::AreaShape::Draw(ref_ptr<dp::GraphicsContext>, ref_ptr<dp::Batcher>, ref_ptr<dp::TextureManager>) const (in Organic Maps) + 216
df::BackendRenderer::AcceptMessage(ref_ptr<df::Message>) (in Organic Maps) + 8184
df::MessageAcceptor::ProcessSingleMessage(bool) (in Organic Maps) + 76
df::BackendRenderer::RenderFrame() (in Organic Maps) + 56
std::__1::__function::__func<df::BaseRenderer::IterateRenderLoop()::$_1, std::__1::allocator<df::BaseRenderer::IterateRenderLoop()::$_1>, void ()>::operator()() (in Organic Maps) + 32
dp::RenderFrameMediator(std::__1::function<void ()>&&) (in Organic Maps) + 44
df::BaseRenderer::IterateRenderLoop() (in Organic Maps) + 60
df::BackendRenderer::Routine::Do() (in Organic Maps) + 184
```

```
dp::LineRawBatch::BatchData(ref_ptr<dp::GraphicsContext>, ref_ptr<dp::AttributeProvider>) (in Organic Maps) + 1328
dp::IndicesRange dp::Batcher::InsertPrimitives<dp::LineRawBatch, std::__1::vector<int, std::__1::allocator<int> > >(ref_ptr<dp::GraphicsContext>, dp::RenderState const&, ref_ptr<dp::AttributeProvider>, std::__1::unique_ptr<dp::OverlayHandle, std::__1::default_delete<dp::OverlayHandle> >&&, unsigned char, std::__1::vector<int, std::__1::allocator<int> >) (in Organic Maps) + 240
dp::Batcher::InsertLineRaw(ref_ptr<dp::GraphicsContext>, dp::RenderState const&, ref_ptr<dp::AttributeProvider>, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::unique_ptr<dp::OverlayHandle, std::__1::default_delete<dp::OverlayHandle> >&&) (in Organic Maps) + 152
dp::Batcher::InsertLineRaw(ref_ptr<dp::GraphicsContext>, dp::RenderState const&, ref_ptr<dp::AttributeProvider>, std::__1::vector<int, std::__1::allocator<int> > const&) (in Organic Maps) + 48
df::AreaShape::DrawArea3D(ref_ptr<dp::GraphicsContext>, ref_ptr<dp::Batcher>, m2::Point<double> const&, m2::Point<double> const&, ref_ptr<dp::Texture>) const (in Organic Maps) + 1832
df::AreaShape::Draw(ref_ptr<dp::GraphicsContext>, ref_ptr<dp::Batcher>, ref_ptr<dp::TextureManager>) const (in Organic Maps) + 216
df::BackendRenderer::AcceptMessage(ref_ptr<df::Message>) (in Organic Maps) + 8184
df::MessageAcceptor::ProcessSingleMessage(bool) (in Organic Maps) + 76
df::BackendRenderer::RenderFrame() (in Organic Maps) + 56
std::__1::__function::__func<df::BaseRenderer::IterateRenderLoop()::$_1, std::__1::allocator<df::BaseRenderer::IterateRenderLoop()::$_1>, void ()>::operator()() (in Organic Maps) + 32
dp::RenderFrameMediator(std::__1::function<void ()>&&) (in Organic Maps) + 44
df::BaseRenderer::IterateRenderLoop() (in Organic Maps) + 60
df::BackendRenderer::Routine::Do() (in Organic Maps) + 184

```

**Comment by vng** [comment] 2023-06-27 16:50
Seems like I've patch it already.
https://github.com/organicmaps/organicmaps/commit/b269834946b2c0674e6c28f6be97849e0d01a0d5

Good to know area to ensure.

**Comment by biodranik** [comment] 2023-06-28 05:29
@hay you may try to install the latest beta version https://testflight.apple.com/join/lrKCl08I and see if it fixed the crash.

**Comment by biodranik** [comment] 2023-06-29 15:37
@hay thanks! @vng looks like a "too big" big feature was somewhere in `Canada_Quebec_Quebec.mwm`, it would be great to find it and to properly handle in the future.

**Comment by rokuz** [comment] 2023-06-29 22:34
Hey! I'm not sure about "too big" feature. @hay could you please provide an approximate place where it crashes? Probably specific shop or street? It can really help to reduce area of search

**Comment by hay** [comment] 2023-06-30 17:18
@rokuz unfortunately i can’t give an exact place, but the crashes occurred when we were around the village of Baie-Saint-Paul.

**Comment by hay** [comment] 2023-06-30 20:18
I’ve also seen crashes when my wife (who’s on the current non-beta version) browses around the village of Cap Chat. I don’t see the same behaviour on the beta, but loading and rendering tiles when zoomed in is very slow. Or is that because this is a debug build?

**Comment by biodranik** [comment] 2023-07-01 09:29
It is a release build. Very strange that it's slow. At least it works and doesn't crash, right?

Can you please try to zoom to some other place, close OM, reinstall it again from the AppStore, and see if it is not slow?

@strump can you please try to install beta version from the TestFlight and check if there is any regression in rendering  (or build the release from the beta branch)? Could it be caused by helicopter-related fixes?

**Comment by hay** [comment] 2023-07-01 11:31
@biodranik the slowness definitely seems to be caused by the Quebec map. I’ve made a video of me zooming around Quebec compared to Amsterdam, the latter is fine, but Quebec is slow. This is with the beta build, i’ll try and see what happens with the current stable release

https://youtu.be/6ODxikoQZrs

**Comment by biodranik** [comment] 2023-07-01 19:43
@vng @rokuz any ideas about the slow rendering? That beta already has the https://github.com/organicmaps/organicmaps/commit/b269834946b2c0674e6c28f6be97849e0d01a0d5 patch applied.

**Comment by strump** [comment] 2023-07-02 10:07
@biodranik I added route type check on every draw. See [drape_frontend/frontend_renderer.cpp](https://github.com/organicmaps/organicmaps/pull/5381/files#diff-a65a461f9a3b80dd53df31dec18efa1e3e1f35a667cb6dac2d332889251a6e2aR1436)

```cpp
if (m_buildingsFramebuffer->IsSupported() && !m_routeRenderer->IsHelicopterRoute())
{
  // ...
}
```

Maybe this flag should be cached in `m_routeRenderer` and updated only on route rebuild?
The same is true for `bool RouteRenderer::HasTransitData()` flag which is called on every draw.

**Comment by biodranik** [comment] 2023-07-02 10:52
@strump thanks for mentioning it. @vng @rokuz do you have better ideas on how to implement it?

**Comment by vng** [comment] 2023-07-02 13:04
I asked in src PR. Why this check is needed here? It is of course not about slow, but anyway.

**Comment by rokuz** [comment] 2023-07-03 12:05
Hey! @biodranik @vng wrt slow rendering, possibly it's an an old issue. If map has long/large polygons near coatlines. It's not friendly for mobile GPU, since it breaks GPU cache for "tile rendering" technique that's used widely on mobile GPUs. It's required to improve geometry generator to avoid this issue.

**Comment by hay** [comment] 2023-07-09 23:24
I’m now running the ⁦2023.07.05-4⁩ beta and it seems the issue with slow rendering tiles is fixed. I’ve also not seen any new crashes. Maybe leave this issue open for a couple of days but otherwise i think it’s fixed. Thanks for all the work!

**Comment by biodranik** [comment] 2023-07-09 23:36
@strump it likely proves that there is an issue in the helicopter code, because 2023.07.05 beta was released without helicopter.

**Comment by biodranik** [comment] 2023-12-24 14:07
I assume that this issue is resolved. Please reopen it if it's not.

**Closed by biodranik** 2023-12-24 14:07 UTC
Labels: iOS, CrashReports
