### ISSUE TITLE
Category search in the Editor ignores actual displayed category names and uses categories.txt synonyms only

### ISSUE THREAD

**Issue by ioctl-user** [organicmaps/organicmaps#3496] opened 2022-09-27 15:46 UTC
При добавлении места на карту в списке выбора типов объектов есть "Памятник", однако, он не ищется. Но если набрать слово "Монумент", то памятник находится.

Вторая особенность полезная, а первая явно нет.
Остальные категории не проверял, возможно там тоже есть ошибки.

**Comment by biodranik** [comment] 2022-09-29 22:35
There is some bug there, it doesn't work in some other languages too.

**Comment by pastk** [comment] 2024-06-14 18:07
Looks like the search for categories in the Editor uses only terms from `categories.txt` and ignores translations from `types_strings.txt`.

E.g.
- "Agricultural Shop" (`shop-agrarian`) is not searchable at all as its absent in categories.txt.
- "Artwork Shop" can't be found via the "artwork" search, but could be found by "art" (the only synonym in categories.txt is "Arts")
- `historic-monument` has only "Монумент" ru synonym in categories.txt though its names as "Памятник" in types_strings.txt, hence the issue in the OP

**Comment by pastk** [comment] 2024-10-24 15:13
Duplicate of
- https://github.com/organicmaps/organicmaps/issues/3260

**Closed** 2024-10-24 15:20 UTC
Labels: Bug, Duplicate, Editor, Search
