### ISSUE TITLE
Add star ratings / reviews

### ISSUE THREAD

**Issue by ProgramminCat** [organicmaps/organicmaps#9373] opened 2024-09-27 13:06 UTC
Kinda like this:
![Screenshot_20240927-090026~2](https://github.com/user-attachments/assets/15dcd10c-d2bb-4741-aabd-63578b18e610)

**Comment by ProgramminCat** [comment] 2024-09-27 13:07
Maybe use something like this? https://lib.reviews/

**Comment by RedAuburn** [comment] 2024-09-27 13:22
please follow https://github.com/organicmaps/organicmaps/issues/2758 :)

Duplicate of #2758

**Closed by RedAuburn** 2024-09-27 13:22 UTC
Labels: Enhancement
