### ISSUE TITLE
Disable zooming to current location at app start

### ISSUE THREAD

**Issue by Outlet2048** [organicmaps/organicmaps#934] opened 2021-07-26 18:56 UTC
It would be nice if the app wouldn't always fly to my current position after opening the app

If I want to see my current location then I can just click the button
But

If I close the app after having zoomed elsewhere then it should stay there, even after restarting

If I close the app with the app tracking my current location then it should probably zoom back to my position after reopening

**Comment by biodranik** [comment] 2021-07-26 19:53
I assume it's Android, right? Because it works properly on iOS. @rtsisyk @vng can you please take a look? It probably broke after refactoring.

**Comment by AlertSubject** [comment] 2021-07-26 20:41
Yes this is android related. The behavior has always been like that if I'm not mistaken

**Comment by amo-f77** [comment] 2021-07-27 12:00
My Android version works correctly.
If I am viewing a location away from where I am located and close the app, then restart, it stays at that location.

When I'm away from my current location, the `settings.ini` file has the following line:
`LastLocationStateMode=NotFollow`
And the app obeys it.
`ScreenClipRect=`  Contains the last viewed location.

When it's set to follow my location the line is:
`LastLocationStateMode=Follow`

**Comment by biodranik** [comment] 2021-07-27 20:28
@amo-f77 @AlertSubject Do you have F-Droid or Google Play version installed? In the GP version there is a setting "Use Google Play Services" for location, it may interfere somehow.

**Comment by amo-f77** [comment] 2021-07-28 01:34
@biodranik, I'm using Google play version `2021.07.08-6-g73931f7-Google`, with Google Play Services Enabled.

Today I saw the behavior reported by @AlertSubject.
Opening the App to check my version and settings this morning it did try to follow me and I had to wiggle the map around to stop it. Maybe it's time related to when the app was last run, as to whether it follows or not.

I will experiment with the two versions I have installed. In one I'll Disable Google Play services and the other I'll leave Enabled. Wait and see what happens tomorrow.

**Comment by csidirop** [comment] 2021-07-28 07:08
I had exactly this issue with maps.me all the time. I'll test it with organicmaps.

**Comment by csidirop** [comment] 2021-07-28 07:41
Okay, just opened the map and it did it again:

https://user-images.githubusercontent.com/43964592/127283431-4cd91c9f-1aea-47a4-a763-3b0dbb5cd977.mp4

**Comment by biodranik** [comment] 2021-07-28 15:32
@csidirop with GP services enabled or disabled? FDroid or GP?

**Comment by csidirop** [comment] 2021-07-28 15:37
Its the gp version (2021.07.08-6-g.....-Google) and with services enabled.

Personally I dont mind, I git used to that lomg ago, but I'll help where I can.

**Comment by biodranik** [comment] 2021-07-28 15:47
Thanks for confirming it! @rtsisyk please try to reproduce it and then let's fix it ASAP, it's an annoying regression.

**Comment by amo-f77** [comment] 2021-07-29 00:33
Results of my simple tests on an Android 7.1.1 Tablet. One with google play enabled, the other disabled.

After 6.5 hours since App closed, both stayed at the location far away from my current location. Success.
The next day, more than 12 hours since closing app, they both jumped to my location. Fail.

App obeys NotFollow for some time and then ignores it. Independent of google play services enabled for location. 
An extended amount of time or a date change appears to trigger it.

**Comment by AlertSubject** [comment] 2021-07-29 00:45
This seems to be the case on my phone as well. I open the app once every few days and it always does it after not being opened for some time

**Comment by csidirop** [comment] 2021-07-29 06:24
I had similar behavior: Closing App and even stopping it don't triggers the movement, after I reopening OMap after few mins, 30 min, after three hours. But this morning it did it again.
It looks like that it happend after long time, but the time I took the footage the APP was max. one hour closed. probably rather less.

Would it help if I enable the protocol?

**Comment by tguen** [comment] 2021-08-19 06:38
If you tap the location button to make the map follow your location, then close the app, it will continue following you as soon as you reopen the app. If you don't want it to jump to your position when you open it, you just have to disable location following by manually moving the map away from your location before closing the app. This is poor UX and should be changed.

**Comment by sanketgarade** [comment] 2022-05-22 01:12
> I assume it's Android, right? Because it works properly on iOS.

It happens on iOS too. (and even on iPadOS.) But not everytime.

**Comment by biodranik** [comment] 2022-05-22 12:52
Can you please check it with the latest Android beta?
And also describe the exact steps to reproduce the issue on both iOS and Android.

**Comment by sanketgarade** [comment] 2022-05-22 15:34
> Can you please check it with the latest Android beta? 
I don't have an android device unfortunately.

> And also describe the exact steps to reproduce the issue on both iOS and Android.
This is for iOS. I haven't noticed any exact pattern to be honest. But it is usually when I open OM after a long time since it was last opened. In between I may have used other apps as well. I will try to observe if there is any preceding pattern when this issue is observed henceforth and will let you know.

**Comment by jwmh** [comment] 2023-06-27 06:20
This can be an option in Settings.
Maybe add a category called “UI Tweaks” 
?

**Comment by rtsisyk** [comment] 2023-11-01 07:52
Sorry, what was the bug? The app doesn't search for location on the start if location was disabled before ("crossed out" location icon).

**Comment by rtsisyk** [comment] 2023-11-23 07:25
I am closing this ticket due to inactivity. Please feel free to re-open if the problem continues to occur in the latest version.

**Closed by rtsisyk** 2023-11-23 07:25 UTC
Labels: Bug, Android, Need Feedback, GPS

**Comment by biodranik** [comment] 2023-11-23 10:24
The current behavior is that OM flies back to the current position after 30 hours of inactivity. But! There could be a bug that OM doesn't extend the 30-hour inactivity period if the app was launched before 30 hours passed. Can please someone check it?
