### ISSUE TITLE
Editing a church does not allow to change the name

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#4986] opened 2023-04-15 10:06 UTC
**Describe the issue**
Whenever you edit the entry of a church, there is no field to change the name

**Steps to reproduce**
1. Go to any church
2. Click on edit entry
3. No field for the name

**Expected behavior**
Be able to change the name of the church

**System information:**
 - Operating system and its version: Android
 - Organic Maps version: 2023.04.02-7-Google

**Comment by janusbenissa** [comment] 2023-04-15 14:11
You can't edit names also not in other buildings.
You have to do that directly in OSM

**Comment by simonschaufi** [comment] 2023-04-15 23:14
Changing the name of a restaurant works.

**Comment by biodranik** [comment] 2023-04-17 21:56
It's to protect some objects from vandalism. We may consider enabling editing for validated "power OSM users". Was the initial church name incorrect?

**Comment by simonschaufi** [comment] 2023-04-17 22:37
Yes it was incorrect. Modern free churches change their names once in a while. It happens way more often than we think.

**Comment by Jean-BaptisteC** [comment] 2024-02-06 20:45
Is it possible to get number of changes from OSM API to enable expert editor?

**Comment by biodranik** [comment] 2024-02-06 21:07
Yes, although it's easy to create "many" changes in OSM. There should be a separate issue about it.

**Comment by pastk** [comment] 2024-04-02 19:53
> It's to protect some objects from vandalism. We may consider enabling editing for validated "power OSM users". Was the initial church name incorrect?

Actually names of churches are editable, but only when they're mapped as separate points. If they're mapped as buildings then name editing doesn't work.
I don't see logic here, looks like a bug or some technical limitation in the current Editor code...

**Comment by pastk** [comment] 2024-04-02 20:37
- duplicate of  #433

**Comment by simonschaufi** [comment] 2024-04-03 07:42
Yes, I can confirm that the building is the source of the problem.

**Comment by pastk** [comment] 2024-04-03 09:13
Ok let's track it in https://github.com/organicmaps/organicmaps/issues/433

**Closed** 2024-04-03 09:14 UTC
Labels: Editor
