### ISSUE TITLE
Allow "name" tag to be added separately

### ISSUE THREAD

**Issue by sanketgarade** [organicmaps/organicmaps#3378] opened 2022-09-09 11:15 UTC
When adding a place to OSM via the OM app, and when the phone's language is not the same language which should go into the `name=*` tag on OSM, then the below issue happens. 

Example in India, the community consensus is that English names should go into the `name=*` tag and local language (which varies by the state you are in) names should go into `name:lang=*` tag. 

My phone's (iOS) preferred language is set to Marathi (`mr`), so when I add a place in OM, it asks for Marathi name but puts it into the `name=*` tag, and doesn't touch the `name:mr=*`. (Of course it give options to add additional language where I usually add the English name `name:en` tag also.)

But the result is that the `name=*` contains Marathi name instead of English. And also the `name:mr=*` tag (which should contain the Marathi name) is never added. 

Instead of this, it would be better to have finer control on the name tags, where I can add the `name`, and `name:mr` tags separately. Below is a screenshot from the [Every door](https://every-door.app/) app which does this easily. It even allows to simply duplicate the text in the `name` tag into the `name:mr` tag or vice verse simply by clicking the arrows icon on the right side.

![image](https://user-images.githubusercontent.com/74632379/189338587-8bc0afbd-7dce-45c6-a9c1-64575f146050.png)

**Comment by biodranik** [comment] 2022-09-11 22:55
@vng can we use generator/region_meta.cpp and data/countries_meta.txt for that? Is it used at the moment? Do we store that meta info inside mwm files? If yes, can it be extracted for the Editor?

**Comment by vng** [comment] 2022-09-12 04:15
We already use meta for lang selection. Can't say for sure what happens in editor.

"it asks for Marathi name but puts it into the name=* tag, and doesn't touch the name:mr=*" This is a bug. Our editor was designed to add _local only_ name:lang tags (AFAIR), because there are always tagging wars with generic name tag in OSM for different regions.

More complicated logic when editing objects. We advice edit names fields in local languages (and here we (should) use meta), but also _override_ (AFAIR) generic name tag if edited name was taken from this generic tag.

We already have some open issues about names in editor.

I still think that having generic editable name tag is not a good idea.

**Comment by sanketgarade** [comment] 2022-09-16 18:58
> This is a bug. 

Yup it is. I confirmed it today by adding a place and observing the resultant data later on OSM. If you want I can share screenshots. 

About adding the `name` tag, I wish it was there since that helps to see the name on OSM.org and other sites/apps, if any, which show the `name` name, which otherwise would be displayed blank. 

Also I saw that if you go to add "add a language" and scroll to the bottom of the list then it lists one option as "default / native for each country". Does this go into the `name` tag?

**Comment by biodranik** [comment] 2022-09-24 22:25
The logic may be more complicated because we have some tricky rules on how to display the name on the map. But let's focus on the issue:
1. It should be clear how to reproduce it.
2. For anyone editing it should be clear that the default `name` is "default/native for each country" value.
3. Original names should not be broken in OSM after edits in OM.

This is an important problem that should be fixed properly. Can you help to carefully test and fix it?

**Comment by sanketgarade** [comment] 2022-09-25 08:31
> It should be clear how to reproduce it.

1. Set phone language (preferred language in iOS) to Marathi `mr` (or your language). 
2. In OM, open the "add a place to map" editor. Under the place name section add a name under the first label, "Marathi" (or your language).
3. Save the place and later check on OSM.org for the same node. The name will be visible under the `name` tag instead of the `name:mr` tag.

**Comment by Timmy-Tesseract** [comment] 2022-10-28 05:09
I've noticed a related issue. 

When I'm trying to modify the name of an existing POI that only has default name tag OM creates an additional name:en tag while the incorrect name variant still remains.

Example 1:
Default name tag corrected, but wrong variant copied into name:en
https://www.openstreetmap.org/node/1260313856/history

Example 2:
Default name tag remains wrong, corrected variant is additionally added as name:en
https://www.openstreetmap.org/node/4122536091/history

**Comment by map-per** [comment] 2024-04-25 15:03
The `name` tag can now be edited directly (see: #6257)

**Closed by map-per** 2024-04-25 15:03 UTC
Labels: Editor
