### ISSUE TITLE
[Android] For some POIs "Wikipedia" button does nothing

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#7400] opened 2024-02-16 10:57 UTC
**Description**
Some POIs have long description from Wikipedia, but tap on "Wikipedia" button doesn't navigate to Wikipedia page.

**Steps to reproduce**
1. Navigate to `41.897597, 12.454697` and select "Santa Maria delle Grazie alle Fornaci" chirch
2. Tap "Wikipedia" button
3. Nothing happens

**Expected behaviour**
User should navigate to Wikipedia article.

**Screenshots**
<img src="https://github.com/organicmaps/organicmaps/assets/720808/fd29f40f-a772-443f-80c1-747f143f8384" width="300px" alt="Santa Maria delle Grazie alle Fornaci"/>

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: master branch, commit `7e9b4a5`

**Other POIs with same behaviour**

* https://osm.org/way/63112440
* https://osm.org/way/64121803

**Comment by Jean-BaptisteC** [comment] 2024-02-16 13:46
Duplicate of #5182

**Closed by Jean-BaptisteC** 2024-02-16 13:46 UTC
Labels: Android, Wikipedia
