### ISSUE TITLE
Add "Inside view"

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#3954] opened 2022-11-23 15:55 UTC
Detect if you're inside the building and show an interior map view, with the exterior map view blurred or dimmed, so the interior is in focus. We couldn't need to figure out where exactly should we go to inside, because we barely see trough the buildings, it would make navigation a lot easier, and more intuitive.

I'll post a concept art later here.

**Comment by dvdmrtnz** [comment] 2022-11-23 20:37
https://github.com/organicmaps/organicmaps/issues/1308

**Comment by pastk** [comment] 2023-06-14 18:01
Closing as a duplicate of #1308

**Closed by pastk** 2023-06-14 18:01 UTC
Labels: Raw Idea
