### ISSUE TITLE
saved points for shops get a generic 'shop' icon instead of the icon of the map point

### ISSUE THREAD

**Issue by joachim-n** [organicmaps/organicmaps#7682] opened 2024-03-25 07:41 UTC
**Describe the issue**

Different kinds of shop have different icons on their map points. But if I save one of them, it gets a generic 'shopping bag' icon.

**Steps to reproduce**
1. Find a map point that's a shop with a specialised icon
2. Save it
3. The saved point marker shows a generic icon

**Expected behaviour**
Show the same icon as the map point.

**Screenshots**

In this screenshot, the uppermost saved point near the station is a bakery, but it's not showing the bakery icon:

![IMG_4271](https://github.com/organicmaps/organicmaps/assets/105262/6c56508b-56f1-4ef2-a6a5-48c9459cc0e3)

**System information:**
 - Operating system and its version: iOS 15.8
 - Organic Maps version: 2024.03.07-1
 - Device Model: iPad Air 2

**Additional context**
Please add any other context or comments here that may be useful.

**Comment by RedAuburn** [comment] 2024-03-25 09:31
duplicate of https://github.com/organicmaps/organicmaps/issues/6950 👍️

**Closed by RedAuburn** 2024-03-25 09:31 UTC
