### ISSUE TITLE
[ios] Wikipedia text is unreadable in the dark mode

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#5364] opened 2023-06-19 14:28 UTC
Works in the Place Page:

![image](https://github.com/organicmaps/organicmaps/assets/170263/850bbbe9-b262-4483-a543-6e1a57967a49)

Doesn't work in the full article view:

![image](https://github.com/organicmaps/organicmaps/assets/170263/4cbdf135-e7ef-496d-b900-8a475b6d599e)

**Comment by dvdmrtnz** [comment] 2023-06-19 16:48
Duplicate of https://github.com/organicmaps/organicmaps/issues/3042

**Comment by d4f5409d** [comment] 2023-06-20 08:46
Why does Organic Maps look so much better on iOS? 😅

**Closed** 2023-08-15 20:16 UTC
Labels: Good first issue, iOS, UI
