### ISSUE TITLE
Traffic Lights in OM

### ISSUE THREAD

**Issue by johnwgoodin** [organicmaps/organicmaps#4371] opened 2023-01-29 23:14 UTC
I left this issue with the developer…

What’s your opinion on it Would you like Traffic Lights in Routing or something you could toggle on or off as a layer?

If traffic lights are already present in OpenStreetMaps perhaps you can make it a Layer you can toggle off or on like you do for Terrain and Subway. If at all possible make it part of the next OpenStreetMaps data. Most of the time in clear weather it’s not really necessary. But when the weather gets really iffy it can be a life saver.

**Comment by biodranik** [comment] 2023-01-30 08:15
The plan is to show traffic lights on the route during the navigation as Apple Maps does. In other cases, they are not needed and only pollute the map.

**Comment by Jean-BaptisteC** [comment] 2024-01-28 19:39
Duplicate of #3987

**Closed by Jean-BaptisteC** 2024-01-28 19:39 UTC
Labels: Duplicate, Navigation
