### ISSUE TITLE
Show Alternate Routes 

### ISSUE THREAD

**Issue by Rosedog09** [organicmaps/organicmaps#5382] opened 2023-06-22 17:55 UTC
Show Alternate Routes and difference in arrival time to allow user to select which route to take. Similar to google maps screenshot.
![Screenshot_20230622-125353](https://github.com/organicmaps/organicmaps/assets/86130469/00391d7d-e0c3-40a0-b0b0-5c0a80a053b3)

**Comment by Jean-BaptisteC** [comment] 2023-06-22 18:05
Duplicate of #2237

**Closed by Jean-BaptisteC** 2023-06-22 18:05 UTC
Labels: Duplicate, Enhancement
