### ISSUE TITLE
Easier access to routing options

### ISSUE THREAD

**Issue by arnaudvergnet** [organicmaps/organicmaps#3090] opened 2022-08-04 12:02 UTC
In current OM versions (at least on Android) users must click the settings icon in the navigation bottom sheet then scroll all the way down to find the routing options. 

~~When planning, there is not even a way to access the settings if no routing option is already set.~~ When planning, there is a button only in car mode.

It would be good to add buttons to open the routing options in the planning header and the navigation bottom sheet.

**Comment by biodranik** [comment] 2022-08-06 10:06
Shouldn't route options be chosen in the route planning mode, before starting navigation? How other apps allow editing route options during the trip?

**Comment by arnaudvergnet** [comment] 2022-08-09 12:13
Route options will often be set when planning the trip but sometimes you may change your mind while navigating and for example decide to avoid toll roads. Having a shortcut to edit route options and recalculate the route would make this process easier.

**Comment by biodranik** [comment] 2022-10-08 15:09
There is an important moment in the current implementation to consider. Now, until we implement #1183 and alike, only one, the fastest route is built. And routing options are shown ONLY if there is something to avoid on the built route, e.g. if it has an unpaved road, a toll, a ferry, or a highway. If routing options are not displayed, then now it means that the built route won't change if a user plays with these options.

That behavior can be used even with alternate routes, although the chance that something "to avoid" will be in the route will be very high. Even more, an alternate route may already include the "avoid highway" variant. But that's another topic.

At the moment, there is a bug: routing "avoid" options are used also for foot and cycling navigation, although the panel is not displayed in these modes. It should be displayed, which is important to avoid confusion. Many users complained to us that route was not built for them, but it was caused by some "avoid" options enabled in settings.

@arnaudvergnet can you please take a look if it's hard to fix?

**Comment by rtsisyk** [comment] 2022-10-20 08:47
A good catch. This is a feature imparity with iOS. iOS does have a toolbar where you can select routing options during planning without opening Setting screen. Android doesn't. This imparity is nice to fix.

**Comment by vng** [comment] 2022-10-22 11:51
https://github.com/organicmaps/organicmaps/pull/3690

**Comment by biodranik** [comment] 2023-02-16 11:10
We've already implemented it :)

**Closed by biodranik** 2023-02-16 11:10 UTC
Labels: Routing, UX
