### ISSUE TITLE
Allow to selectively clear search history

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4063] opened 2022-12-10 11:13 UTC
It will be very convenient, especially after implementing the "more often items are at the top" logic.

**Comment by pm4rcin** [comment] 2022-12-10 13:54
Do you mean cleaning one entry from history when long-press and click?

**Comment by biodranik** [comment] 2022-12-11 10:19
There are several native ways to delete list entries on Android and iOS. Long tap, swipe to the left or right, cross button, etc.

**Comment by Jean-BaptisteC** [comment] 2024-01-28 19:00
Duplicate of #7185

**Closed by Jean-BaptisteC** 2024-01-28 19:00 UTC
Labels: Search

**Comment by slackuj** [comment] 2024-06-09 11:26
> There are several native ways to delete list entries on Android and iOS. Long tap, swipe to the left or right, cross button, etc.

I don't find this working on Android.And why is this issue marked closed? Has it been resolved?

**Comment by Jean-BaptisteC** [comment] 2024-06-09 11:36
This issue has been closed because it's a duplicate of another issue
