### ISSUE TITLE
A problem with HK subway line

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#253] opened 2021-03-20 13:57 UTC
> There is a problem with the display of this subway line, the actual direction is not displayed like this

![2021-03-20 16 56 06](https://user-images.githubusercontent.com/1799054/111871849-3959f680-899d-11eb-9e1e-8c6d10368907.jpg)

![2021-03-20 16 56 00](https://user-images.githubusercontent.com/1799054/111871847-37903300-899d-11eb-9e7e-ce938219694d.jpg)

Reported by @DGLEL in TG group

**Comment by vng** [comment] 2021-03-21 08:31
Well, this behaviour is by design. We don't promise that subway trace is drawn the same way as on schemes ..
Main here is stops sequence. According to this https://www.travelchinaguide.com/images/map/hongkong/metro.jpg
blue line has next sequence near airport: Tsing Yi, Airport, Asia Expo. The same sequence is drawn and connected in the app.

Probably, we will use route geometry like https://www.openstreetmap.org/relation/5317238 someday in future.

**Comment by alexashh** [comment] 2021-04-14 18:50
I have similar problem in Nizhny Novgorod, Russia. subway line is flying above river, instead of going over corresponding bridge.
![image](https://user-images.githubusercontent.com/16898090/114763164-2dc6d900-9d6b-11eb-8565-c4585f8eccf5.png)

**Comment by pastk** [comment] 2024-11-23 11:18
- closing in favor of same but more generic https://github.com/organicmaps/organicmaps/issues/7067

**Closed by pastk** 2024-11-23 11:18 UTC
Labels: UI, Metro
