### ISSUE TITLE
Subtitle type changes to wrong value after bookmarking POI

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#8330] opened 2024-05-30 00:27 UTC
https://www.openstreetmap.org/way/1152366455

If you bookmark this POI, it turns from `fast food` to `retaining wall`

https://github.com/organicmaps/organicmaps/assets/26939824/7174601e-2bc2-4b1b-987d-1fe1326d6ec6

**Comment by Jean-BaptisteC** [comment] 2024-05-30 05:11
Duplicate of #2168

**Closed by Jean-BaptisteC** 2024-05-30 05:11 UTC
Labels: Bug, Bookmarks and Tracks, Core
