### ISSUE TITLE
Add a function called return home

### ISSUE THREAD

**Issue by drugdeliverthatwantprivacy** [organicmaps/organicmaps#7042] opened 2024-01-01 13:41 UTC
After taking a trip or going for a run very far, there are times when I don't know how to get home or the quickest way to get back, 😖to get back I have to scan the street and the door of the building 😑😤 making the process very tiring

One solution to this tedious task for the average user would be to simply have an option called return home when you are going to type something in the search bar.

Another option would be to add special markers called home (with the icon of a 🏠 house ) and work (with the icon of a 💼 suitcase) to organic maps and allow in the list of markers directly the option to establish a route to said marker, without having to zoom in and out of the map to see where the marker is

**Comment by Jean-BaptisteC** [comment] 2024-01-01 13:43
Duplicate of #1133

**Closed by Jean-BaptisteC** 2024-01-01 13:43 UTC
Labels: Duplicate
