### ISSUE TITLE
Opening hours not parsed correctly: "day off"

### ISSUE THREAD

**Issue by gorgobacka** [organicmaps/organicmaps#8218] opened 2024-05-19 11:38 UTC
⚠ Have you searched for similar, already existing issues? Yes, but I haven't found one.

**Describe the issue**
The value "day off" in opening_hours is not respected. In the app it looks like the poi is open the whole day. And it's the same for the editing mode. (See the attached screenshots) 
But in reality it's the opposite.

Example POI: https://www.openstreetmap.org/node/1231635290
Opening hours: Tu-Fr 07:00-18:00; Sa 07:00-11:00; Mo,Su,PH off

**Steps to reproduce**
Open a poi that uses "off" in opening hours to indicate that it's closed the whole day.

**Expected behaviour**
The app should show that it's closed the whole day. Same for the edit screens.

**Screenshots**
![Screenshot_20240519-132751.png](https://github.com/organicmaps/organicmaps/assets/10488441/f5539acc-7e89-4526-8580-c76f17502f43)
![Screenshot_20240519-132853.png](https://github.com/organicmaps/organicmaps/assets/10488441/52c456c4-d9c6-4059-9b16-5c78728960c6)
![Screenshot_20240519-132907.png](https://github.com/organicmaps/organicmaps/assets/10488441/45b339d4-e074-419a-8dc2-a51fd565c1a5)

**System information:**
 - Operating system and its version: Android
 - Organic Maps version: 2024.05.11-3-FDroid

**Comment by matheusgomesms** [comment] 2024-05-19 21:14
Duplicate of #1575?

**Comment by RedAuburn** [comment] 2024-05-19 22:45
yup duplicate, but a good test case, thanks for the report :)

Duplicate of https://github.com/organicmaps/organicmaps/issues/1575

**Closed by RedAuburn** 2024-05-19 22:45 UTC
Labels: Opening Hours
