### ISSUE TITLE
Unable to get informations about speed radar during gps mode

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#2624] opened 2022-05-26 08:13 UTC
<img src="https://user-images.githubusercontent.com/87148630/170446212-38661c33-ea45-4e86-a039-e688973e292a.png" width="300">

App version: 2022.05.20-4-Google
Android 12 - Pixel 6

How reproduce:

- Search destination with speed radar on the road
- Start GPS
- Near speed radar (when radar is red)
- Click on radar icon or speed icon
- Title of object is not show, Arrow is hide and GPS coordinates = 0,0
- Screenshot are take from Dijon, France

**Comment by arnaudvergnet** [comment] 2022-06-01 06:26
Duplicate of https://github.com/organicmaps/organicmaps/issues/1657

**Closed** 2022-06-01 06:44 UTC
Labels: Bug, Good first issue, Android
