### ISSUE TITLE
When the system font size is large, certain interfaces may display errors

### ISSUE THREAD

**Issue by felixng1988** [organicmaps/organicmaps#7831] opened 2024-04-05 23:55 UTC
⚠ Have you searched for similar, already existing issues?

**Describe the issue**
Please write a clear and concise description of the issue here.
I found a bug in Organic Maps and I hope the Organic Maps team can fix it. The bug occurs when users set a larger font size, causing certain interfaces in Organic Maps, like the OpenStreetMap details and location names on the edit location page, to display abnormally. This issue only disappears when the font size is set to smaller sizes

**Steps to reproduce**

**Expected behaviour**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.
https://t.me/organicmaps/39354

**System information:**
LineageOS 20, Android 13
Redmi Note 9 5G (cannon)

**Additional context**
Please add any other context or comments here that may be useful.
2024.03.31-8-Web

**Comment by Jean-BaptisteC** [comment] 2024-04-06 05:52
Duplicate of #4774

**Closed by Jean-BaptisteC** 2024-04-06 05:52 UTC
