### ISSUE TITLE
[ios] Copy contact email address in clipboard if no mail client is installed

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#5986] opened 2023-09-09 12:22 UTC
...and notify users about it.

![выява](https://github.com/organicmaps/organicmaps/assets/170263/ce111ead-b90b-495f-ab09-438fd7610614)

**Comment by Jean-BaptisteC** [comment] 2024-03-25 18:27
Duplicate of #5948

**Closed by Jean-BaptisteC** 2024-03-25 18:27 UTC
Labels: Good first issue, iOS
