### ISSUE TITLE
Subway (layer=-1) Is Not Show On Map

### ISSUE THREAD

**Issue by toygarlk** [organicmaps/organicmaps#5126] opened 2023-05-11 22:21 UTC
If train road have a layer=-1 and tunnel=yes tag, this is not show on map. I drop example link, please fix it.

https://www.openstreetmap.org/way/23045034

**Comment by biodranik** [comment] 2023-05-12 01:49
@vng is map pollution in big cities the main reason we don't draw tunnels? Or is it a bug?

**Comment by vng** [comment] 2023-05-12 13:10
https://github.com/organicmaps/organicmaps/issues/2245

Also we already had similar discussions before.

**Comment by pastk** [comment] 2023-06-14 17:59
Closing as a duplicate of #2245

**Closed by pastk** 2023-06-14 17:59 UTC
Labels: Styles, Metro
