### ISSUE TITLE
The lane assist goes out of the screen for 5+ lanes

### ISSUE THREAD

**Issue by alensiljak** [organicmaps/organicmaps#8096] opened 2024-05-05 20:22 UTC
⚠ Have you searched for similar, already existing issues?

#1404 

**Describe the issue**
When having 5+ lanes, the right-most lanes go outside the visible area on the screen.
This is especially impacting if need to turn right.

**Steps to reproduce**
1. Navigate to a location
2. Drive on a street with 5+ lanes

**Expected behaviour**
All the lanes should be visible on the screen. Preferably scaled. 

**Screenshots**
tba

**System information:**
 - Operating system and its version: Android 14
 - Organic Maps version: 2024.03.31-8-Google
 - Device Model: Pixel 7

**Additional context**
n/a

**Comment by Jean-BaptisteC** [comment] 2024-05-05 20:23
Duplicate of #5002

**Closed by Jean-BaptisteC** 2024-05-05 20:23 UTC
