### ISSUE TITLE
OM compute by default weird path in walking mode when an lake is near

### ISSUE THREAD

**Issue by NovaliX-Dev** [organicmaps/organicmaps#3251] opened 2022-08-25 06:34 UTC
I wanted to try the new algorithm as it's more faster, so I ask OM to compute the path Lausanne -> Geneve and it gave me this :

![image](https://user-images.githubusercontent.com/79244938/186586601-085675bd-fc34-40b0-a72a-097590f3a127.png)

Where i expected that :

![image](https://user-images.githubusercontent.com/79244938/186586705-b4742b68-5574-419f-b418-b061b77590c4.png)

As we can see, OM by default takes the ferry paths. For other uses, this is perfectly fine, but this is problematic for hiking (when we want to avoid vehicles uses like cars and ferrys).

So what i propose is to notice the user that there are ferrys that are taken (like in the car mode when one or more options to avoid some kind of path are turned on). This way, he can easily turn the option to avoid taking ferrys if he wants to. It's easier than diving into the settings and find this options himself.

What do you think about that ?

**Comment by NovaliX-Dev** [comment] 2022-08-25 06:37
This seems also to happen in bicycle mode ([issue #2703](https://github.com/organicmaps/organicmaps/issues/2703)

**Comment by biodranik** [comment] 2022-08-27 20:27
This is a known issue. The UI code should be fixed to properly display "avoid" panel if the route goes through some of the ways that can be avoided, the same as it is done already for a car.

Is there anyone brave enough to take a look at existing Android and iOS code and fix it? It could be a simple "if" or "switch/case" fix.

**Comment by palucki** [comment] 2022-10-17 19:49
@biodranik does it sound like an issue for a novice in the project?

**Comment by biodranik** [comment] 2022-10-17 21:41
Please check, it should be already fixed in the master branch/in the upcoming release.

"Avoid" options now should be visible for walking and cycling modes too.

**Comment by palucki** [comment] 2022-10-18 18:52
okay, so the issue can be closed?

**Comment by biodranik** [comment] 2022-10-18 21:48
Only if it's fixed :)

**Comment by vng** [comment] 2022-10-22 11:50
https://github.com/organicmaps/organicmaps/pull/3690

**Comment by palucki** [comment] 2022-10-24 18:38
The issue is fixed with the above PR.
![image](https://user-images.githubusercontent.com/7307022/197600599-0e218eba-a187-4ce3-820c-fb6e65ea215a.png)

I think it can be closed now.

**Comment by biodranik** [comment] 2022-10-24 21:17
Thanks for testing and confirming it!

**Closed by biodranik** 2022-10-24 21:17 UTC
Labels: Good first issue, Routing, UI
