### ISSUE TITLE
[routing] Exit and reenter highways on ramps.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#3033] opened 2022-07-27 10:20 UTC
1. https://www.openstreetmap.org/#map=18/51.89793/4.97840 because [this](https://www.openstreetmap.org/way/193114533) link has maxspeed=130.
2. https://www.openstreetmap.org/#map=17/51.95501/5.02950 because [this](https://www.openstreetmap.org/way/7105514) link has maxspeed=130.

**Comment by vng** [comment] 2022-07-30 17:52
3. https://www.openstreetmap.org/#map=17/55.41067/10.05602 from right to left, because link has maxspeed=130.
4. https://www.openstreetmap.org/#map=16/53.5152/9.9159 from north to south by A7, because link has maxspeed=100.

**Comment by Donnnno** [comment] 2022-07-31 19:51
Is this the same as these errors?

![image](https://user-images.githubusercontent.com/31142286/182042750-63861054-4353-4d09-ab16-29aa1629f724.png)
![image](https://user-images.githubusercontent.com/31142286/182042754-375e16af-7baf-4c87-b5b1-76a2ebdbb66a.png)

**Comment by vng** [comment] 2022-07-31 20:14
Yes, if links have bigger speed than main motorway in OSM.

**Comment by Donnnno** [comment] 2022-07-31 21:07
Ah, is r)yhere anything I can do about it to fix it (maybe in OSM?).

**Comment by biodranik** [comment] 2022-08-01 04:38
At first, it should be checked if the data is real, e.g. if links do have higher speed limits than the motorway in the reality.
The algorithm also should be improved, now it doesn't penalize any turns.

**Comment by Donnnno** [comment] 2022-08-01 04:54
Ah okay, I'll check it.

For me, this phenomen happens like every time while being on a highway in the netherlands. Probably 2-4 times per route

**Comment by vng** [comment] 2022-08-01 06:47
@Donnnno Yes, I talked with some Dutch OSM mappers and they confirm that its OK. Here is the comments:
```
Counterintuitively, the maxspeed on this on-ramp is 130 km/h instead of the lower speed posted on the main road due to it having only a G1 (start motorway) sign at the start
```
https://wiki.openstreetmap.org/wiki/Reduced_speed_limit_on_Dutch_motorways

**Comment by vng** [comment] 2022-08-01 10:07
5. From (55.812527, 49.133837) -> To (55.830214, 49.13403)

**Comment by Donnnno** [comment] 2022-08-01 11:48
@vng so, what should I change in that case?

**Comment by vng** [comment] 2022-08-01 13:41
Just check ground truth, that map is correct according to the signs on the ground.

**Comment by Donnnno** [comment] 2022-08-01 18:24
I checked some places, unfortunately those were already right, so the Organic maps algorithm should be fixed instead of the map in these cases.

**Comment by mimi89999** [comment] 2022-08-13 19:24
I also have the same issue![Screenshot_20220813-111441.png](https://user-images.githubusercontent.com/8530546/184507965-d2f1b9e0-551e-4b4b-9cce-c1b481b39030.png)

**Comment by biodranik** [comment] 2022-08-13 22:17
> I also have the same issue. In my case the speed on the ramp is exactly the same as the speed on the main way. https://www.openstreetmap.org/#map=19/32.20137/34.81964
> 
> ![Screenshot_20220813-111441.png](https://user-images.githubusercontent.com/8530546/184507965-d2f1b9e0-551e-4b4b-9cce-c1b481b39030.png)
 
@vng looks like the algorithm chooses the shortest path :) The penalty for leaving/entering the highway are mandatory...

**Comment by vng** [comment] 2022-08-14 04:55
I know it, turn penalties is not a straight forward task to implement.

**Comment by Donnnno** [comment] 2022-08-14 09:02
osmand managed to do it somehow, maybe there's something to find there?

**Comment by mimi89999** [comment] 2022-08-14 10:02
Shouldn't there be a small time penalty for each crossroad?

**Comment by biodranik** [comment] 2022-09-24 13:58
Another example here: https://www.openstreetmap.org/way/6463138#map=19/53.17047/6.33635&layers=D

It should be fixed when we add a penalty for turns/exists and maybe some crossings (how it should be handled in the link above?).

**Comment by chereskata** [comment] 2022-10-23 17:20
I can confitm the issue.

It does it with higher speed on the on-links (Near 50.818648, 5.72007)

![1](https://user-images.githubusercontent.com/87526889/197406111-fb202312-1213-43f0-b9d1-21ce75ea49bd.PNG)

as well as with identical speed on the links (Near 51.497738, 7.380912) 

![2](https://user-images.githubusercontent.com/87526889/197406135-bbb0f136-9204-44f6-a708-91255b846447.PNG)

**Closed** 2022-10-31 18:11 UTC
Labels: Routing

**Comment by biopsin** [comment] 2022-11-01 14:16
Sorry Im late to the party but I have alot of this off/on ramp in norway too. If these needs to be fixed individually I can dump a list of coordinates this weekend if needed?

**Comment by nach0** [comment] 2023-11-07 11:44
I reopen this issue as I am having the same problem now in road https://www.openstreetmap.org/way/428968512, Organic Maps routes me through the ramps in both ways: https://www.openstreetmap.org/way/123313861 and https://www.openstreetmap.org/way/123313863. In this case I don't see speed limit data in OSM for the road nor the ramps.

I made [a note on the OSM map](https://www.openstreetmap.org/note/3877169#map=19/43.37256/-3.42788) when this happened (thinking it was a mapping error) and other user reviewed it and said it's fixed. I tested with the newest beta (map data from 03 Nov 2023) and the problem is still there. OsmAnd. doesn't have this problem. See screenshots.

![Screenshot_20231107-121515_OsmAnd~](https://github.com/organicmaps/organicmaps/assets/1169440/3a246c7b-c7f8-4006-8790-0557709351e7)
![Screenshot_20231107-120205_Organic Maps (Beta)](https://github.com/organicmaps/organicmaps/assets/1169440/dfed9156-c3c6-4c4c-bd14-06f07e3cd6b4)

**Comment by vng** [comment] 2023-11-07 14:23
@nach0 Confirm. The bug was introduced when we started predicting an approx/average speed for highways without maxspeed tag. I will fix the algo.

BTW: do you know the actual speed limit there?

**Comment by nach0** [comment] 2023-11-07 14:36
@vng thank you for the very quick response. Unfortunately I don't know the speed limit, I was there as a tourist some months ago and noticed this issue. I have followed it, but I have not been back to that place.
