### ISSUE TITLE
CarPlay UI covers scale bar

### ISSUE THREAD

**Issue by verhovsky** [organicmaps/organicmaps#8513] opened 2024-06-21 08:40 UTC
You can see it peeking out in the bottom left here

![image](https://github.com/organicmaps/organicmaps/assets/5687998/035c31cc-8045-433d-96b3-69ae99c8283d)

**Comment by biodranik** [comment] 2024-06-21 22:00
It's a duplicate of https://github.com/organicmaps/organicmaps/issues/804

**Closed by biodranik** 2024-06-21 22:00 UTC
Labels: CarPlay
