### ISSUE TITLE
Wikipedia article is hidden when you set bookmark

### ISSUE THREAD

**Issue by csidirop** [organicmaps/organicmaps#3321] opened 2022-09-02 06:40 UTC
I don't know if this is known or maybe intended, but setting a bookmark hides the Wikipedia article. Plus, I can't find a way to show it again. 

Tested on multiple points.
The screen recording is too big for github at this moment, I can add it later if needed.

Version: 2022.08.23-5-Google

**Comment by biodranik** [comment] 2022-09-02 11:07
Please check github for duplicate issues.

**Comment by arnaudvergnet** [comment] 2022-09-02 13:53
Duplicate of https://github.com/organicmaps/organicmaps/issues/2825

**Comment by csidirop** [comment] 2022-09-02 18:27
Oh, I must have missed it somehow

**Closed** 2022-09-02 20:00 UTC
