### ISSUE TITLE
Auto dark mode doesn't work on Android 9.0

### ISSUE THREAD

**Issue by xmha97** [organicmaps/organicmaps#480] opened 2021-06-02 20:02 UTC
Hello,
I'm using Android 9.0 on Xiaomi Mi 6.
When dark mode enable on my phone,  Dark mode is not activated on Organic Maps.
![2021_06_03_00_30_55.jpg](https://user-images.githubusercontent.com/23485114/120544833-17e8a280-c403-11eb-862f-58dca272b18c.jpg)
![2021_06_03_00_30_32.jpg](https://user-images.githubusercontent.com/23485114/120544868-246cfb00-c403-11eb-9b2b-47c779a500f4.jpg)

**Comment by xmha97** [comment] 2021-06-02 20:16
This sounds like a duplicate of #453

**Comment by xmha97** [comment] 2021-06-02 20:18
This sounds like a duplicate of #366

**Comment by rtsisyk** [comment] 2021-06-04 05:41
Yes, this is a duplicate of #366. This bug is confirmed. Please subscribe to #366.

**Closed by rtsisyk** 2021-06-04 05:41 UTC
