### ISSUE TITLE
Add option to disable location services startup popup

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [organicmaps/organicmaps#1517] opened 2021-11-06 11:04 UTC
Everytime the app boots and if the location services are disabled a popup appears informing the user to enable the service. After a while this can get a bit annyoing, so I propose let's add a checkbox at least after the 2nd time this appears to be able to disable it and/or add a settings entry making it possible to disable it.

**Comment by biodranik** [comment] 2021-11-06 19:21
Duplicate of #1128

**Comment by IHateTheProgrammingClass** [comment] 2021-11-07 09:34
@biodranik Should I close?

**Comment by biodranik** [comment] 2021-11-07 09:45
Probably yes, it would be easier to track only one.

**Closed** 2021-11-07 10:14 UTC
