### ISSUE TITLE
Render access restrictions

### ISSUE THREAD

**Issue by jmarchon1** [organicmaps/organicmaps#5814] opened 2023-08-24 18:39 UTC
I would like to see access restrictions in OSM rendered in Organic Maps. Currently, highways such as driveways with a tag like `access=private` are rendered the same as ones without that tag. A slightly different color or pattern, such as that used by OSM Carto, would be nice to see to indicate that these highways are not publicly accessible.

**Comment by pastk** [comment] 2023-08-25 17:24
We've been discussing this issue in https://github.com/organicmaps/organicmaps/issues/1454 already.

**Comment by jmarchon1** [comment] 2023-08-26 05:07
Oops, my quick search must have missed that. Sorry for the duplicate, in that case.

**Comment by pastk** [comment] 2023-08-26 13:16
Duplicate of https://github.com/organicmaps/organicmaps/issues/1454

**Closed by pastk** 2023-08-26 13:16 UTC
Labels: Styles
