### ISSUE TITLE
UI during navigation: Header UI is a bit small and missing exit

### ISSUE THREAD

**Issue by waterytart** [organicmaps/organicmaps#7588] opened 2024-03-14 04:02 UTC
The header on the top of the screen showing the next step of the navigation (ie, exit towards road this and that) is a bit small and hard to read while navigating (Pixel 7, I'm a motorcycle user). Compared to the size of the signs on Gmaps or OSM, it's almost normal text size, which makes it hard to figure while driving. Additionally it's missing the highway/road exit number, which in many points it can be a  lot more informative than the road/direction it's heading to, as that might not match the road signs. But the exit number would be very decisive in matching the correct point to the map.

**Describe alternatives you have considered**
- How do you solve this issue now with Organic Maps or other apps?
OSM, Gmaps and Magic Earth all show bigger banner texts for the road instructions. Not all of them follow the road exit numbers, but this would be a very useful feature.

**Comment by fitojb** [comment] 2024-03-14 06:48
I agree; please see PR #7060.

Duplicate of #5316

**Closed by fitojb** 2024-03-14 06:48 UTC
Labels: Enhancement
