### ISSUE TITLE
App thinks that location services are disabled while they aren't

### ISSUE THREAD

**Issue by PetbkA** [organicmaps/organicmaps#2454] opened 2022-04-24 08:41 UTC
**OS**: LineageOS 19.0 (Android 12)
**OM**: 2022.03.23-4-Google

I have all location services enabled in OS. For OM they're allowed with precise location and only while using the app.

However, when I'm starting the app, warning that location services are disabled appears after some seconds. Meanwhile location detection works OK in OM, the problem is only in the warning.

Here are the [logs](https://github.com/organicmaps/organicmaps/files/8549294/OM_20220424_False_LocationDisabled.zip.zip) and the [video](https://user-images.githubusercontent.com/22843816/164968176-bf41f81b-b724-49b4-b424-4f50b4d68e77.mp4)

**Comment by biodranik** [comment] 2022-04-24 12:53
A duplicate of #2400

**Closed** 2022-04-26 20:21 UTC
Labels: Bug, Android, GPS
