### ISSUE TITLE
Show speed limit all the time during car navigation

### ISSUE THREAD

**Issue by simonschaufi** [organicmaps/organicmaps#4985] opened 2023-04-15 09:56 UTC
**Is your feature request related to a problem? Please describe.**
When I'm driving by car, I want to see all the time what is the speed limit of the current road. OSM has this information but it is not displayed in Organic Maps.

**Describe the solution you would like**
Add the speed limit on the screen whenever it is available in osm, preferably in the top (right) corner.

**Describe alternatives you have considered**
- Google Maps has this feature since a long time

**Additional context**

![grafik](https://user-images.githubusercontent.com/941794/232206913-0c9bbaa3-9840-44f5-add7-d0f5544671bc.png)

Related: #3711 #4628

**Comment by Altonss** [comment] 2023-04-15 10:46
Is this maybe a duplicate of https://github.com/organicmaps/organicmaps/issues/952 ?

**Comment by simonschaufi** [comment] 2023-04-15 23:11
Yes, it's a duplicate. Sorry for that. Can I sponsor the development of this feature?

**Comment by Altonss** [comment] 2023-04-15 23:20
Some work has started in this PR https://github.com/organicmaps/organicmaps/pull/3817
But for the feature sponsor, I can ping @biodranik :)

**Comment by simonschaufi** [comment] 2023-04-16 06:06
I just noticed that maps.me has implemented this feature already. Since Organic maps and Maps.me are very similar, why not have a look at their implementation?

**Comment by pm4rcin** [comment] 2023-04-16 15:46
> I just noticed that maps.me has implemented this feature already. Since Organic maps and Maps.me are very similar, why not have a look at their implementation?

Because maps.me is no longer open source. The source code you mentioned in other thread is really old. Last commit is from 2021.

**Comment by simonschaufi** [comment] 2023-04-17 07:13
Oh yes, thanks for the hint. They should archive the repo...

**Closed** 2023-09-02 18:24 UTC
Labels: Duplicate
