### ISSUE TITLE
Transit times

### ISSUE THREAD

**Issue by Shadowspear123** [organicmaps/organicmaps#7579] opened 2024-03-13 05:45 UTC
In urban areas where the population is heavily reliant on public transportation, it is handy feature in a map to have the departure timing of the subway/buses when one taps on a station. An example of this can be seen in both Apple Maps and Google Maps, if you got to a major American city (ex NYC or the Bay Area) and tap on an MTA or BART station, it will show you the upcoming departure times. 

**Describe the ideal solution**
It would be very convenient and feasible for this feature to be added to Organic maps. There are many ways to add this feature to the app, ranging from APIs directly from the transit associations to pre made projects by other people online. Adding this feature would eliminate one of the reasons many people in urban areas still use google and apple maps.

**Comment by uis246** [comment] 2024-03-31 00:02
Is there some sort of public transport schedule tag? Because metro systems I know don't have public schedules and tends to follow intervals instead.

**Comment by Shadowspear123** [comment] 2024-04-01 11:49
I can only speak for the cities I’m familiar with, but yes most major cities in the US have some sort of schedule. I know the the BART and MTA do for a fact

**Comment by Jean-BaptisteC** [comment] 2024-04-07 12:50
Duplicate of #3730

**Closed by Jean-BaptisteC** 2024-04-07 12:50 UTC
Labels: Metro, Public Transport
