### ISSUE TITLE
[ios] Add Test TTS voice button like on Android

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7552] opened 2024-03-09 16:05 UTC
Note that there is an easter egg in the TTS voice test button on Android that should be ported too )

**Comment by Jean-BaptisteC** [comment] 2024-03-09 17:59
Duplicate of #6850

**Closed by Jean-BaptisteC** 2024-03-09 17:59 UTC
Labels: Good first issue, iOS

**Comment by biodranik** [comment] 2024-03-09 22:22
😄 thanks J.B., my memory is lost with 2K issues 🤦
