### ISSUE TITLE
boundary=protected_area hatch reduces the readability of the map

### ISSUE THREAD

**Issue by not-available-username** [organicmaps/organicmaps#1450] opened 2021-10-21 08:20 UTC
Protected areas are displayed with the hatch that makes very hard to read isolines and others elements, please refer to attached screenshots. The filling should be replaced with a polyline? May be visible also with low zoom level, in order to be able to see the whole area.

![IMG_1399](https://user-images.githubusercontent.com/92886370/138237216-902fbd78-3cd4-439e-8920-e093a689ec5d.PNG)
![IMG_1400](https://user-images.githubusercontent.com/92886370/138237224-4aa229d0-55a7-4ec6-97f0-da50297175ec.PNG)

**Comment by pastk** [comment] 2022-01-27 13:59
Duplicate of #1222

**Closed by pastk** 2022-01-27 13:59 UTC
Labels: Duplicate, Styles

**Comment by pastk** [comment] 2022-02-01 15:39
Fixed in #1979

**Comment by pastk** [comment] 2022-02-04 15:40
Fixed in #1979
