### ISSUE TITLE
download update for maps without app update

### ISSUE THREAD

**Issue by userforsource** [organicmaps/organicmaps#8148] opened 2024-05-12 10:48 UTC
I find an issue that whenever i get a app update it includes an map update also but why so
Maps can be updated without updating the app. If someone wants to keep a older version of app they can but not required to update the app to get maps update.

**Comment by matheusgomesms** [comment] 2024-05-12 13:12
Duplicate of #851.

**Closed by matheusgomesms** 2024-05-12 13:12 UTC
Labels: Enhancement
