### ISSUE TITLE
Investigate crash on Android

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3747] opened 2022-10-29 12:46 UTC
@arnaudvergnet can you please check it?

While we're deciding how to fix this labels styling I would like to get some feedback about styling and help with crashing android app.
 
I changed white outline in dark mode to dark outline and fixed changing outline in label for `leisure=park` and `leisure=garden` to test how it will look.
<details>
<summary> Examples </summary>

![Screenshot_20221013_134742](https://user-images.githubusercontent.com/2056282/195594470-267a5a64-af94-4e47-a5db-d204f4926047.png)
![Screenshot_20221013_134804](https://user-images.githubusercontent.com/2056282/195594485-b75515d2-0712-4242-bf4b-07ecbf61a7f5.png)
![Screenshot_20221013_135401](https://user-images.githubusercontent.com/2056282/195594491-40044e1e-7974-4f5b-a52d-39702d5b43f3.png)
![Screenshot_20221013_140000](https://user-images.githubusercontent.com/2056282/195594505-080770b0-8570-4d61-a4bc-8385ba4e4bb0.png)
![Screenshot_20221013_140051](https://user-images.githubusercontent.com/2056282/195594517-52e8291f-5cb1-4260-814e-da2432d87e6e.png)
</details>

How do you like it? For me it looks quite good. The dark outlines are more subtle than in day theme (I didn't changed them since last time, you can see the day theme examples [in my previous post](https://github.com/organicmaps/organicmaps/pull/3386#issuecomment-1273816503)) because of lower contrast. 
But I don't want to make just the outline for dark theme bigger, because I want to keep day and night icons mostly the same, just with different color values. Though, I would also consider making garden outline a big bigger in day and night theme if you think it's not enough.

I fixed the mentioned `node|z17-[leisure]` line with the approach I described before (replaced it with `[leisure=value]` selectors of all the tags that we support, minus the conflicting nature ones, and minus the one handled in this Icons.mapcss file). If we want to be sure that these selectors for `leisure=value` are unnecessary then we would probably have to check it manually POI by POI.

However I have different problem. The application is crashing when I change the theme in android emulator. I changed just the styling files and added some icons so I have no idea how it affects android code. Maybe someone can help?

It crashes when I go back from settings menu to map after changing theme:
![crash_when_changing_theme](https://user-images.githubusercontent.com/2056282/195595561-80b590a2-ee6a-4a27-ac77-a280c036c3bc.gif)

logs:
```
2022-10-13 14:02:38.217 12853-12853/app.organicmaps.debug D/AndroidRuntime: Shutting down VM
2022-10-13 14:02:38.232 12853-12853/app.organicmaps.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.organicmaps.debug, PID: 12853
    java.lang.IllegalStateException: Fragment MapButtonsController{6872b0f} (a85e2ada-b875-44a9-96a7-3ab5600d045b) not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
        at com.mapswithme.maps.maplayer.MapButtonsController.updateMenuBadge(MapButtonsController.java:184)
        at com.mapswithme.maps.maplayer.MapButtonsController$1.onGlobalLayout(MapButtonsController.java:96)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3352)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:832)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2022-10-13 14:02:38.280 12853-12853/app.organicmaps.debug I/Process: Sending signal. PID: 12853 SIG: 9
```

It's throwing error in _MapButtonsController.java_, look like pretty new code. However I don't get this crash on latest master, just in my branch (that's based on latest master). This is really confusing for me because my changes are basically in styling only.

> 79 commits ahead? Something is wrong here, please, make correct rebase above master.

@vng  yep, sorry, I messed up a bit, should be good now. Now it's based on master and PR is to master (the previous @biodranik  comment about merging it to beta was when this PR was about removing unnamed garden icons, but the code changed to just replacing icons to the one without circle background, so maybe it can be merged to master now?)

_Originally posted by @mpawelski in https://github.com/organicmaps/organicmaps/issues/3386#issuecomment-1277549819_

**Comment by Jean-BaptisteC** [comment] 2022-10-29 16:17
I think crash is similar with this #3640

**Comment by arnaudvergnet** [comment] 2022-10-29 21:04
I can't reproduce this, works fine on my end. If you look at the dates, https://github.com/organicmaps/organicmaps/pull/3386#issuecomment-1277549819 was posted 4 days before https://github.com/organicmaps/organicmaps/pull/3666. So my guess is this was the same issue as https://github.com/organicmaps/organicmaps/issues/3640 and so was also fixed by https://github.com/organicmaps/organicmaps/pull/3666.

**Comment by mpawelski** [comment] 2022-10-30 09:44
I didn't try to reproduce it again (I need to figure out how to compile from console and run android app on actual device, Android Studio and its debugger is too slow for me).

But I remember debugging this and seeing that it actually crash in the place that your fix changed (in `requireContext();`). 
So yep, if you can't reproduce it then it's probably fixed.

**Closed** 2022-10-30 09:47 UTC
Labels: Android, CrashReports
