### ISSUE TITLE
What3Words (W3W) integration

### ISSUE THREAD

**Issue by serrq** [organicmaps/organicmaps#7038] opened 2024-01-01 10:17 UTC
Imagine being able to divide the surface of the entire planet into perfectly 3x3 (meters) square tiles, and give each of them a specific name, consisting of only three words.

Now, these words define a geographic location accurate enough to identify a man.

What advantage?

Three simple words are a unique address in the world.

Easy to remember and to pronounce (if you suggest it to a voice command).

https://what3words.com/

**Comment by Jean-BaptisteC** [comment] 2024-01-01 11:10
I guess, you want API what3words will be integrated into organics maps because we don't know how to generate these codes.
I have checked how to use this API, this API is not free (45$ per month)
Using this API requires to use there library (we can not know which data is collected by API) and a lot of data is collected when users use their app:
- https://what3words.com/privacy 
- https://reports.exodus-privacy.eu.org/fr/reports/com.what3words.android/latest/

But we try to improve user experience to share position location, by supporting (not fully #457) https://en.wikipedia.org/wiki/Open_Location_Code which has a similar logic, we know using coordinates position is not easy for everyone :)

**Closed** 2024-01-01 13:30 UTC
Labels: Enhancement

**Comment by astrojuanlu** [comment] 2024-01-01 18:34
also, duplicate of #3437
