### ISSUE TITLE
Add toggle to remove kayak

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#6967] opened 2023-12-24 22:01 UTC
In this PR https://github.com/organicmaps/organicmaps/pull/6720 you created a toggle to remove crap links. But closed it some why.

So…

Dear @licaon-kter please add “anti feature”. That still not implemented this and closed PR

![IMG_1605](https://github.com/organicmaps/organicmaps/assets/154763692/014c3e1e-4ccc-4abb-a595-5df4fd8ed499)
![IMG_1606](https://github.com/organicmaps/organicmaps/assets/154763692/28641ff8-aec1-4968-83af-aaf175e348c7)
![IMG_1607](https://github.com/organicmaps/organicmaps/assets/154763692/1f270707-c33b-4b48-b784-d99812de485e)
![IMG_1608](https://github.com/organicmaps/organicmaps/assets/154763692/23953491-57e3-41e0-85a9-0c96822e82aa)

**Comment by pastk** [comment] 2023-12-25 06:18
Note that #6720 is not closed, but a work in progress.

**Comment by fitojb** [comment] 2023-12-25 08:17
Duplicate of #6720, and can't help but note that this person immediately deletes their account to avoid taking accountability for their trolling. As we say in Spanish, _[tira la piedra y esconde la mano](https://tureng.com/en/spanish-english/tirar%20la%20piedra%20y%20esconder%20la%20mano)_... And yes, I consider this person a troll for their blatant entitlement in calling open-source efforts "crap"...

**Closed by fitojb** 2023-12-25 08:17 UTC

**Comment by Ping5784** [comment] 2023-12-27 08:04
@fitojb not because this. Only because GitHub don’t like self hosted mail. It flags such accounts after some time

**Comment by Ping5784** [comment] 2023-12-27 08:05
Also @fitojb OM indeed open source (great!) but kayak crap is privacy intrusive + proprietary

**Comment by mnalis** [comment] 2024-01-01 16:37
> Only because GitHub don’t like self hosted mail. It flags such accounts after some time

@ghost does it? I've been using self-hosted email account on github for years without any issues. But I do keep civil, and do not engage in vandalism / issue spamming / other shady practices when trying to promote my point of view.

> OM indeed open source (great!) but kayak crap is privacy intrusive + proprietary

_That_ I agree completely. 

It is just a shame that some people spam issues with throwaway accounts, thus making other people that care about very real kayak privacy issue (like me) seem less credible -- using throwaway account and issue spamming just cheapens those issues for everyone and makes it less likely people will agree with points (e.g. _"we'll I do agree there are privacy issues, but there is no way I'm going to associate myself with those vandals who can't engage in civil discourse, so I'll just stay silent"_)

I'd wish if those ghosts would stop doing that throwaway account shenanigans, and just express their opinions in a civil way (so they won't get banned), if they intend for their (and our) words to have any weight.

**Comment by Kasi78** [comment] 2024-01-08 22:36
[They got anti feature 😂](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14082/diffs?commit_id=cdf6baa74e0f222ebb210ae63ca4d51a4b3807a8)

https://github.com/organicmaps/organicmaps/issues/7119 

I can’t stop laughing. Greed kills the project

**Comment by licaon-kter** [comment] 2024-01-08 22:42
Kasi78 can you and the other ghosts stop with the vandalism?

You're really hurting your cause...

**Comment by Ueri780** [comment] 2024-01-10 18:27
@licaon-kter 
> Kasi78 can you and the other ghosts stop with the vandalism?
> 
> You're really hurting your cause...

Sorry if I bothered you. I really appreciate F-Droid (and only F-Droid) team work. Have a nice day!

**Comment by biodranik** [comment] 2024-01-10 22:39
@licaon-kter am I correctly understanding that removing specific releases/apks from the Fdroid metadata will make them unavailable for downloading on the Fdroid website and in the Fdroid app? If not, then how is it usually done?

**Comment by licaon-kter** [comment] 2024-01-10 22:46
We can disable them, if you want them gone, yes.

Why?

**Comment by biodranik** [comment] 2024-01-13 19:42
@licaon-kter because the whole app/all versions are tagged, instead of only mentioned releases. Can you please help and remove those OM releases wrongly tagged as "contains ads", and then make sure that FDroid metadata on the mobile and desktop versions has been properly updated?

**Comment by licaon-kter** [comment] 2024-01-13 20:59
The AF flag is shown for the installable version, the main repo keeps last 3, all affected.

The Archive has the rest.

Indeed the UI/webpage does not make it individually clear. Known issue.

**Comment by biodranik** [comment] 2024-01-13 21:17
@licaon-kter can you please help with the removal of those 3 releases from FDroid?

**Comment by licaon-kter** [comment] 2024-01-13 21:36
@biodranik you have a new release that doesn't have this issue and you want to remove those 3 that have?

**Comment by biodranik** [comment] 2024-01-13 22:24
@licaon-kter 3 existing releases should be removed in any case, please help to do that. If we knew in advance about that retroactive mislabeling, not based on the existing FDroid rules, the situation would be very different.

**Comment by pastk** [comment] 2024-01-14 06:35
> @biodranik you have a new release that doesn't have this issue and you want to remove those 3 that have?

Actually the co-founders (@biodranik, @vng, @rtsisyk) are considering to stop F-Droid releases (they didn't give a go to the last "2024.01.09-5-android" release tag already) for undefined time (until the F-Droid AF labelling issue is resolved somehow I guess). I hope they'll make their decision finally and will announce it ASAP.

There is no consensus of OM developers on this decision (e.g. I'm against it) and it wasn't discussed with users at all.

With that in mind, removing the last three AF-tagged releases will be a massive drawback for the new F-Droid OM users. I'm against it.

**Comment by licaon-kter** [comment] 2024-01-14 09:32
_"The labelling issue"_ can be fixed with https://github.com/organicmaps/organicmaps/pull/6720 making them **opt-in**, but that's already known, yes?

**Comment by licaon-kter** [comment] 2024-01-14 09:33
I'm not against disabling those versions, but this seems to be a user hostile action as they don't get the latest bug fixes. :(

**Comment by Renompe** [comment] 2024-01-14 10:14
@biodranik @pastk @vng and @rtsisyk 

Are you really going to toss F-Droid community away just because of your ambitions and greed?

[Read topic](https://discuss.privacyguides.net/t/organic-maps-adding-kayak-referral-links-to-mobile-app/15382/) about you on PG. You got hated.

Maybe it’s just better to remove link or add toggle as in https://github.com/organicmaps/organicmaps/pull/6720 said?

What’s blocking you from adding opt-in option? What happening to project that had been warm for community in the past?

Devs, is this all your real target? Do you want to make your community upset only because some cents? Maybe it’s better to understand situation and make consensus that will make everyone happy?

**Comment by licaon-kter** [comment] 2024-01-14 10:28
Renompe: Stop with the ghost accounts, your opinion will be dismissed if you behave like this.

**Comment by biodranik** [comment] 2024-01-14 12:28
To clarify: @pastk guessing or interpretation of the situation is wrong.

@licaon-kter we're working on another solution. Please proceed with the removal of the mislabeled releases, this is a pre-requisite of the upcoming Organic Maps build for FDroid.

**Comment by mnalis** [comment] 2024-01-14 21:56
> we're working on another solution

That's great to hear @biodranik ! It would help calm down a situation a lot if you could divulge what you're working on? Maybe [one of those suggested solutions](https://github.com/organicmaps/organicmaps/issues/6668#issuecomment-1873434366)? It would be great if you can add link here to that branch/repo/PR or at least a description of it! And maybe an approximate timeline for implementation? 

I certainly hope it would fare better than PR https://github.com/organicmaps/organicmaps/pull/6720

> Please proceed with the removal of the mislabeled releases

I'm not very knowledgable about the subject, but since f-droid keeps only last 3 releases in its release repository, and all last 3 releases of OrganicMaps are now antifeature-tainted, I'm wondering what would be the result of removing all 3 versions @licaon-kter ? Making OrganicMaps **completely unavailable** on F-droid until (and if) the day no-ads version is published? _**Or**_ only **unavailable until next run** (when it would fetch and recompile last untainted version)?

(also, if I understand correctly that AF are inherited from last release automatically, it would probably mean that auto-updates would need to be disabled too for Organic Maps, so antifeature-afflicted versions are not pulled-in unless vetted as having no anti-features manually)

**Comment by licaon-kter** [comment] 2024-01-15 06:06
The previous 3 ones come back @mnalis

**Comment by licaon-kter** [comment] 2024-01-15 10:45
@biodranik done https://gitlab.com/fdroid/fdroiddata/-/commit/f6e9b2101ed9822c2739376aa853ab48a9ab8254

**Comment by biodranik** [comment] 2024-01-20 18:24
@licaon-kter Should these builds be deleted from the metadata file? The Fdroid store still has these builds and misinforms users that OM "Contains ads".

**Comment by licaon-kter** [comment] 2024-01-20 18:52
@biodranik read https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client same aplies
