### ISSUE TITLE
OM no longer updates through F-DROID

### ISSUE THREAD

**Issue by krza** [organicmaps/organicmaps#7367] opened 2024-02-11 18:59 UTC
Hi,

I know post 7218 which is about this topic. However, there is a lengthy discussion only which I am not really interested in. My only question is when I can get updates again for my OM which I had installed through F-DROID. To be honest I am kind of bewildered that there was no kind of information to the users and actually no clear way to find out what is wrong. Only here I found the reason but this is not a place a regular user would look for it.

Is there any news? Or is there a workaround? Do I need to uninstall it and installig from the Google Play Store again? If so, how can I keep all my app settings and the list of downloaded maps?

Thanks,
Kristian

**Comment by fitojb** [comment] 2024-02-11 21:58
Closing as duplicate of #7218.

There is no need to open separate issues for the same topic; use the Discussions tab instead.

I recommend you to join the chat (Matrix and Telegram are bridged together) and read the backlog behind this post: https://t.me/organicmaps/37434 (context is always good, and very important in this case…)

**Closed by fitojb** 2024-02-11 21:58 UTC

**Comment by krza** [comment] 2024-02-12 16:58
You are referring to a _Telegram_ channel? Seriously?

**Comment by fitojb** [comment] 2024-02-13 05:04
No, I mentioned both Telegram AND Matrix; you have options. Jeez
