### ISSUE TITLE
[android] Crash in search::LocalityFinder::LoadVicinity

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#6414] opened 2023-10-29 17:51 UTC
- Monkey on api=28
- [video](https://storage.googleapis.com/test-lab-tfv1dx2ft95t8-yibm740y7szh2/2023-10-29_17%3A29%3A28.417207_sZKy/MediumPhone.arm-28-en-portrait/video.mp4)
- [logcat](https://storage.googleapis.com/test-lab-tfv1dx2ft95t8-yibm740y7szh2/2023-10-29_17%3A29%3A28.417207_sZKy/MediumPhone.arm-28-en-portrait/logcat)
- [firebase](https://console.firebase.google.com/u/0/project/omapsapp/testlab/histories/bh.7a38003b1edbc7b5/matrices/6468472138749398611/executions/bs.4f24749b520fc4b)

```
     *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/sdk_gphone_arm64/generic_arm64:9/PSR1.210301.009.B6/9767327:userdebug/dev-keys'
Revision: '0'
ABI: 'arm64'
pid: 7820, tid: 7995, name: Thread-14  >>> app.organicmaps.debug <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '/home/runner/work/organicmaps/organicmaps/android/app/src/main/cpp/app/organicmaps/core/logging.cpp:45: void jni::AndroidLogMessage(LogLevel, const SrcPoint &, const std::string &): assertion "false" failed'
    x0  0000000000000000  x1  0000000000001f3b  x2  0000000000000006  x3  0000000000000008
    x4  0000000000008080  x5  0000000000008080  x6  0000000000008080  x7  0000000000000038
    x8  0000000000000083  x9  0acd930b7c29a040  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 00000000653e988c  x14 0000f424dc48d280  x15 0000a6933aabffd0
    x16 00000075cde722c8  x17 00000075cddb0040  x18 00000075299fcf10  x19 0000000000001e8c
    x20 0000000000001f3b  x21 00000075299ff4f0  x22 00001e8c00001e8c  x23 0000007531cbc5f8
    x24 00000075299ff570  x25 0000007529902000  x26 00000075d251e5e0  x27 0000000000000000
    x28 0000007ff1761680  x29 00000075299fd670
    sp  00000075299fd630  lr  00000075cdda4cc0  pc  00000075cdda4ce8
backtrace:
    #00 pc 0000000000021ce8  /system/lib64/libc.so (abort+116)
    #01 pc 0000000000022064  /system/lib64/libc.so (__assert2+36)
    #02 pc 000000000208de28  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (jni::AndroidLogMessage(base::LogLevel, base::SrcPoint const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+336)
    #03 pc 0000000002df2104  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (MwmSet::LockValueImpl(MwmSet::MwmId const&, MwmSet::EventList&)+940)
    #04 pc 0000000002df3894  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (MwmSet::GetMwmHandleByIdImpl(MwmSet::MwmId const&, MwmSet::EventList&)+104)
    #05 pc 0000000002f0d92c  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #06 pc 0000000002df3780  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #07 pc 0000000002df369c  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (MwmSet::GetMwmHandleById(MwmSet::MwmId const&)+100)
    #08 pc 000000000222dd64  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (MwmSet::GetMwmHandleById(MwmSet::MwmId const&) const+36)
    #09 pc 000000000319ae5c  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #10 pc 000000000319ae00  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #11 pc 000000000319aaac  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #12 pc 000000000319a974  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #13 pc 000000000319a870  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #14 pc 0000000003035bcc  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #15 pc 00000000030357dc  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (search::LocalityFinder::LoadVicinity(m2::Point<double> const&, bool, bool)+780)
    #16 pc 0000000002f4704c  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #17 pc 0000000002f46868  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (search::Ranker::MakeResult(search::RankerResult const&, bool, bool) const+896)
    #18 pc 0000000002f47f9c  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (search::Ranker::UpdateResults(bool)+892)
    #19 pc 000000000303e278  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (search::PreRanker::UpdateResults(bool)+148)
    #20 pc 000000000300a2bc  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (search::Processor::Search(search::SearchParams)+1444)
    #21 pc 0000000003009acc  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (search::Engine::DoSearch(search::SearchParams, std::__ndk1::shared_ptr<search::ProcessorHandle>, search::Processor&)+368)
    #22 pc 00000000030f82b8  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #23 pc 00000000030f8244  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #24 pc 00000000030f81f4  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #25 pc 00000000030f81c8  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #26 pc 00000000030f723c  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #27 pc 0000000003056ae8  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #28 pc 0000000003056a90  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (std::__ndk1::function<void (search::Processor&)>::operator()(search::Processor&) const+28)
    #29 pc 0000000003009924  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (search::Engine::Message::operator()(search::Processor&)+32)
    #30 pc 0000000003007928  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (search::Engine::MainLoop(search::Engine::Context&)+696)
    #31 pc 00000000030f3264  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #32 pc 00000000030f31c0  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #33 pc 00000000030f3124  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (_ZNSt6__ndk16__bindIMN6search6EngineEFvRNS2_7ContextEEJPS2_NS_17reference_wrapperIS3_EEEEclB7v170000IJEEENS_13__bind_returnIS6_NS_5tupleIJS7_S9_EEENSD_IJDpOT_EEEXsr22__is_valid_bind_returnIS6_SE_SI_EE5valueEE4typeESH_+48)
    #34 pc 00000000030f30e4  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #35 pc 00000000030f309c  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (_ZNSt6__ndk128__invoke_void_return_wrapperIvLb1EE6__callIJRNS_6__bindIMN6search6EngineEFvRNS5_7ContextEEJPS5_NS_17reference_wrapperIS6_EEEEEEEEvDpOT_+20)
    #36 pc 00000000030f3078  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #37 pc 00000000030f2270  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (_ZNSt6__ndk110__function6__funcINS_6__bindIMN6search6EngineEFvRNS4_7ContextEEJPS4_NS_17reference_wrapperIS5_EEEEENS_9allocatorISC_EEFvvEEclEv+24)
    #38 pc 0000000002151e70  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #39 pc 00000000020c445c  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (std::__ndk1::function<void ()>::operator()() const+20)
    #40 pc 00000000037726c8  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so (threads::SimpleThread::ThreadFunc(std::__ndk1::function<void ()>&&)+24)
    #41 pc 00000000030f1930  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #42 pc 00000000030f18c8  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #43 pc 00000000030f1658  /data/app/app.organicmaps.debug-ItQuT-MTthgWmMOiJvydXQ==/lib/arm64/liborganicmaps.so
    #44 pc 0000000000081080  /system/lib64/libc.so (__pthread_start(void*)+36)
    #45 pc 0000000000023510  /system/lib64/libc.so (__start_thread+68)
```

**Comment by biodranik** [comment] 2023-10-29 20:35
@vng 
```
10-29 10:38:20.006: D/OMcore(7820): search/geocoder.cpp:590 operator()(): US_California_Chico geocoding complete.
10-29 10:38:20.006: I/OMcore(7820): search/geocoder.cpp:394 operator()(): Total geocoding time: 0.0495811 seconds
10-29 10:38:20.006: D/OMcore(7820): search/pre_ranker.cpp:288 FilterRelaxedResults(): Flush relaxed results number: 0
10-29 10:38:20.010: D/OMcore(7820): search/ranker.cpp:852 MakeRankerResults(): PreRankerResults number = 176
10-29 10:38:20.026: W/OMcore(7820): platform/platform_android.cpp:132 GetReader(): Can't get reader for: /storage/emulated/0/Android/data/app.organicmaps.debug/files/230920/US_California_Chico.mwm in scope f
10-29 10:38:20.026: D/OMcore(7820): platform/platform_android.cpp:37 ~DbgLogger(): Source for file /storage/emulated/0/Android/data/app.organicmaps.debug/files/230920/US_California_Chico.mwm is f
10-29 10:38:20.026: E/OMcore(7820): indexer/mwm_set.cpp:304 LockValueImpl(): Can't create MWMValue for US_California_Chico Reason FileAbsentException /home/runner/work/organicmaps/organicmaps/platform/platform_android.cpp:133, "File not found /storage/emulated/0/Android/data/app.organicmaps.debug/files/230920/US_California_Chico.mwm"
10-29 10:38:20.026: E/OMcore(7820): core/logging.cpp:45 AndroidLogMessage(): CHECK(level < g_LogAbortLevel) 3 3 Abort. Log level is too serious 3
```

**Comment by Jean-BaptisteC** [comment] 2023-10-29 21:29
Duplicate of #4099

**Closed** 2023-10-30 04:40 UTC
Labels: Duplicate, Android, CrashReports, Search
